### ISSUE TITLE
Wishlist: Bring back Graphite Docs

### ISSUE THREAD

**Issue by friedger** [stacksgov/Stacks-Grants#10]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> What problems do you aim to solve? How does it serve the mission of a user owned internet?

There are many word processing online services like Google Docs, Dropbox Paper, Box, .. however, all of them require to take an account from them, I can't bring my own account, in particular our Blockstack accounts.

There was already a good word processing online service using gaia storage and Blockstack Auth called Graphite Docs. It is open source, but the app is no longer hosted. This project would bring back the service to Blockstack users.

## Project Overview

> What solution are you providing? Who will it serve?

This project will review the code base of graphite docs hosted at https://github.com/Graphite-Docs/graphite and upgrade the auth mechanism to Blockstack Connect. Finally, the app will be deployed to new domain.

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

1. Review the code base
1. Replace legacy auth with Connect
1. Prepare landing page
1. Market the new launch
1. Deploy the app

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Budget: 1500$
Milestone 1 - 500$: Release with Connect as auth method
Milestone 2 - 1000$: Launched application with launch party

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?

This is a wish list project. If you think that you can provide the code changes and the marketing this is your opportunity

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

## Community and Supporting Materials

> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

Graphite Docs was one of the top apps in 2019!

Source code: https://github.com/Graphite-Docs/graphite

**Comment by friedger** [comment]
As the main feature I would like to see is collaboration and we don't have a good decentralized solution for radiks yet, I will close this for now in favor of a radiks proposal.

**Comment by lrettig** [comment]
> As the main feature I would like to see is collaboration and we don't have a good decentralized solution for radiks yet, I will close this for now in favor of a radiks proposal.

This makes me think that it would be nice to have a "depends on" field for the wishlist: e.g., "we want feature X but it depends on feature Y which is also in the wishlist."
