### ISSUE TITLE
Amortize - Allows Homeowners to exchange 5% of the future value of their home for Bitcoin. 

### ISSUE THREAD

**Issue by murarjam630** [stacksgov/Stacks-Grants#125]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

There is currently 20 Trillion worth of Bitcoin trapped in owner occupied single family homes in America. The only way for homeowners to access this Bitcoin right now is to sell their home or take out a loan against it. Not only will Amortize help people onboard to a user owned internet, but it will allow for decentralized homeownership. The current mortgage industry operates more like a 30 year lease agreement. People do not actually own their homes until they pay 30 years of interest. With Amortize... there's no extra debt, no interest, and no monthly payments. Just people exchanging the equity locked in their home for Bitcoin. 

[www.amortize.io](url)

**Project Overview**
What solution are you providing? Who will it serve?

Amortize is offered to all owner occupied homeowners in America with at least 20% equity in their homes. We provide a way for them to exchange 5% of the future value of their home for Bitcoin. A portion of their Bitcoin is held in a smart contract until they sell their home, and a portion is paid to the homeowner upfront to initiate the agreement. Payments are made according to the Amortize Schedule which is a customized hybrid reverse amortization schedule. 

Calculator:

[www.amortize.io/estimate](url)

The Amortize DEX will allow people from across the world to invest in a market that is currently unaccessible to all retail, and most institutional investors - Owner occupied single family homes. Investors can lock Bitcoin in an Amortize contract to earn 3.5-5% annual yield (for a stake in all homes), and traders can exchange tokens backed by actual real estate from 48 cities in America using our DEX. Amortize holders can provide liquidity to the DEX to earn yield. 

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

Components included a decentralized exchange, 48 city tokens, 1 Amortize token, and an NFT containing an encrypted record of the deed on IPFS for every home equity purchase agreement. V1 will require manually deployment of smart contract via a centralized entity. V2 will integrate Chainlink to Zillow Zestimate API to accurate price new tokens minted and keep track of the values of the city pools. V3 can be fully decentralized pending regulatory approval and adoption of Bitcoin/Smart Contracts at the county level. (Digital/Decentralized recording of Deeds on chain)

**Budget and Milestones**

I am not seeking a grant at this time, but appreciate the opportunity to apply for one. I have enough funds to get me through development, but I am not a developer =[ 

Please connect me with a developer or development team who I can compensate for this project. Thanks!

**Comment by philipdesmedt** [comment]
@murarjam630 not sure if still relevant, but feel free to DM on Stacks discord (pipje#2872), I can connect you to some people who are working on something with real estate & tokenization that could be relevant.
