### ISSUE TITLE
Stacks Nigeria Chapter Application

### ISSUE THREAD

**Issue by ogasky** [stacksgov/Stacks-Grants#127]
**Help us understand your vision for your Stacks Chapter by answering the following questions:**

**1. What about Stacks are you most excited about? Please be specific. (For example, you could be excited about “recruiting more Stackers” or “bringing DeFi to Bitcoin”.)**
Nigeria has a population of over two hundred million people, and is one of the African countries with large number of software developers and web designers. Presently block-chain technology is becoming the new tech order in Nigeria but there is no strong community to help educate more people on it. Thus the urgent need for the Stacks Nigeria Chapter to be established. We are excited that the Nigeria block chain technology will be well positioned with Stacks.

**2. Why are you so excited about this? How do you think it can help your community?**
We believe that Stacks will help educate more people in Nigeria about cryptocurrency and block-chain technology, and in no distance time will be accepted by all as a legal means of business transactions in Nigeria. And since there are a large number of tech communities in Nigeria, Stacks can easily be leveraged on these tech communities for future advancement. Also, I wish to state here that crypto and block-chain technology is gaining good ground in Nigeria and thus the there is need for the opening of Stacks Nigeria Chapter. it is key to note that I and my team started the GitLab Nigeria Community in May 2019 and within 2 years we created a national awareness, you can see from this link https://www.meetup.com/GitLab-Nigeria-Community/ and this I believe we can still do for the Stack Nigeria Community to gain full presence across the various cities in Nigeria.

**3. What do you think is the single most effective thing you can do to bring Stacks to your community?**
As a tech community manager, I will leverage on existing communities towards bringing Stacks to my Community by organizing meetups in different cities and tertiary institutions to create awareness of Stacks, this will involve social media campaign and swags distributions to meetups attendees. There will be other Stacks cities leads and volunteers that will help promote Stacks too.

**4. What are your goals for your Stacks Chapter for the next 3 months? 6 months? 1 year?**
- In 3 months, we intend to organize the first Stacks Nigeria hackathon on Blockchain. as well as Stacks meetups to educate and train a thriving developer community on Blockchain, Crypto and Clarity Language and this meetups will be monthly in different cities of Nigeria.
- In 6 months, we intend to host Nigeria’s largest conference on Blockchain. This will help in creating awareness of Blockchain Technology and its use cases, Web 3.0, Stacks Tools and above all policy awareness which will lead to Blockchain and Crypto Regulation of Nigeria.
- In one year, we want to introduce 200 hard-core Stacks developers to Stacks Community, identify developers who can build at least one of the Wish List grants and lastly, make Stacks the most active crypto network for developers in Nigeria.

**5. How do you plan to achieve those goals? (You can share broad strategies here.)**
In order to achieve these goals above, I will employ the following strategies:
- Organize meetups and hackathons
- Leverage on existing communities
- Recruit ambassadors in tertiary institutions
- Engage Influencers and Celebrities
- Produce Movies and Documentaries
- Produce Swags
- Activate offline publicity
- Engage in Social Media Publicity
- Organize talk shows

**6. If you have growth goals (e.g. “grow the Telegram community by X%), is there a place where the Stacks community can see and track your progress?**
- Create a Discord Channel for local Blockchain developers.
- Increase subscribers from Nigeria to Stacks Newsletter.
- Create Twitter Channel for the group.
- Create a Telegram group

**7. (Optional) Share examples of any community growth or progress so far. This can be in the form of metrics (e.g. Twitter or Telegram growth), press/good news, or community stories.**

https://techpoint.africa/2021/05/14/nigerian-blockchain-hub-abuja/
https://blockchainnigeria.group/
https://twitter.com/blockchainng?lang=en
https://web.facebook.com/CodeUpAfrica/
https://twitter.com/wittyfoundation
https://www.meetup.com/CodeUp-Africa/
https://www.meetup.com/Asaba-Webflow-Meetup/
https://www.meetup.com/GitLab-Nigeria-Community/
https://web.facebook.com/WittyTechnologiesandEmpowermentFoundation
https://www.meetup.com/Warri-WordPress-Meetup/

**8 Briefly summarize your operating costs for one quarter (3 months). (You may attach an appendix/supplement listing your costs in more detail.)**

$20,000 per month including personnel (social media management, content creation, PR, partnerships, community management, third-party vendor management, support ecosystem entities, relationship management, technical and non-technical support, general consulting, transport and logistics), marketing expenses, swag/gift/merchandise, website design and maintenance, software expenses, events, hackathons, talk show, short video production, other service fees.

Team: $11,000/month
Marketing/Publicity/swag: approx. $2000/month
Tech/Software/Design/Website: approx. $5000
Meetups/hackathons/talk show: approx. $2000

Total: $20,000/month

**Comment by louiseivan** [comment]
We currently have a chapter in the works. I suggest coordinating with Haroun, who's building the community for Africa. Also, the figures here are overblown. We have a bias toward action and would want to see momentum before anything else. Usually, chapter leads have a long list of community contributions which can be found in Hiro, Freehold, Daemon Technologies, New Internet Labs, or Stacks Foundation.

cc: @jennymith

**Comment by ogasky** [comment]
@louiseivan, thank you for the update about the African community work in progress, and am very happy to be part of it. Africa is a continent with 54 countries and Nigeria is just one of these African countries, thus she will be part of the African community. However, in the issue of momentum, I and my team are very ready to give in our best towards the success of the community in Nigeria. It will interest you to note that I started the GitLab Nigeria Community (https://www.meetup.com/GitLab-Nigeria-Community/) in the month of May 2019 with some few developers community and within one year we grew the community from less than 20 to over a thousand members and we did over 40 events within a year before the COVID-19 closedown. Please see https://www.meetup.com/GitLab-Nigeria-Community/ and also it very key to note that our budget was based on covering the 6 geopolitical zones and 36 states in Nigeria, however we can surely reduce the scope of our event/meetup coverage per month to accommodate the approved budget. Finally, I want to appeal, that the Nigeria Community be approved while the African Community work is on going. Thank you.

**Comment by harounkola** [comment]
I'll follow up, perhaps we can combine our activities.

**Comment by harounkola** [comment]
> I'll follow up, perhaps we can combine our activities.

Please join our Telegram community and participate there too https://t.me/StacksAfrica

**Comment by ogasky** [comment]
@harounkola, I have join the telegram group. Thanks

**Comment by harounkola** [comment]
Thanks @ogasky as @louiseivan mentioned, action is that the community looks for. 

Bring your developer buddies to the Telegram group, now that you've joined. Let's work on creating something useful like a stacking pool just for us Africans and I'm sure they'd find that the African community can be right up there with the other's that are already creating real value for the broader Stacks community.

**Comment by ogasky** [comment]
@harounkola, as promised in the telegram group, am very much ready to support the African Continent group but we must also understand that every brands with community focus in mind build their communities from the local to country groups. I can list several for you but I do not want to promote any brand here, thus you can research on that. However, it is also key to note that I have been developing communities from state to national level in Nigeria since 2017 of which I can provide you some links if necessary. Finally, I want to state clearly that I am passionate about community services and am very much ready to build this community. The Stacks Nigeria telegram group have been created long ago & we are building gradually. thank you.

**Comment by harounkola** [comment]
Good luck with your efforts to take the message of Stacks to the poeple of NIgeria. Please include @louiseivan in your activities and he'll add you to the Stacks Trooper's group too.

**Comment by ogasky** [comment]
acknowledged and thank you.
