### ISSUE TITLE
ALEX - a functioning platform on Stacks that efficiently connects crypto financial participants

### ISSUE THREAD

**Issue by rachelyingyi** [stacksgov/Stacks-Grants#132]
## Background

Stacks is an open-source network of decentralized apps and smart contracts built on Bitcoin. Stacks unleashes Bitcoin’s full potential as a programmable base layer.
Stacks makes it then possible to access the liquidity, power, and safety of Bitcoin’s 1tn dollar blockchain.
Stacks 2.0 being released only recently, however, there is currently a lack of DeFi primitives and ecosystem to unlock the full potential of Bitcoin.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/443225/120918288-4b1e8080-c6e6-11eb-8307-5d3db5fc7384.png">
Fig 1: Stacks currently lacks DeFi primitives and ecosystem to unlock the full potential of Bitcoin

## Project Overview

Think of us as [Compound](https://compound.finance) / [AAVE](https://aave.com) with underlying technology like [Balancer](https://balancer.fi), but user experience of [Robinhood](https://www.robinhood.com).

At ALEX, you can 
- Lend your BTC and earn 
- Borrow BTC
- Mitigate risk with BTC short positions
- Maximize upside with BTC leveraged long positions

<img width="369" alt="image" src="https://user-images.githubusercontent.com/443225/120918450-15c66280-c6e7-11eb-9950-5ccab7f2c0d5.png">
Fig 2: ALEX aims to build DeFi primitives that Stacks need to grow its ecosystem

Our initial focus (v1) is
- Build DeFi primitives targeting developers looking to build ecosystem on Stacks, and
- Simplify the user experience going from(to) CeFi to(from) DeFi to attract non-developers, broadening the Stacks user base.

## Scope

A number of Clarity smart contracts will be built on the core concept of Yield Tokens ("ayTokens"). Yield Tokens allow term lending with fixed APY.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/443225/120919614-18c45180-c6ed-11eb-8252-81d5bbf09f9d.png">
Fig 3: Yield Tokens allow term lending with fixed APY

### Lending at fixed yield for a fixed term
- Buying of ayToken (against Token) equates to lending of Token at the rate implied by the price of ayToken until T.
- Holding ayToken until T allows the holder to accrue, with certainty, at a fixed rate (as implied by the price at which holder bought ayToken).
- Selling of ayToken before T could result in a profit or loss, depending on the prevailing price of ayToken.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/443225/120918675-27f4d080-c6e8-11eb-99a7-7a2b9b398123.png">
Fig 4: Buying and selling of Yield Tokens allows the efficient price discovery

### Borrowing at fixed yield for a fixed term
- Minting of ayToken against collateral assets and selling of ayToken against Token equates to the borrowing of Token at the rate implied by the price at which ayToken was sold.
- Loan-to-Value (“LTV”) is the ratio of the value of the tokens borrowed and the value of the collateral assets.
- Liquidation occurs if the LTV of a loan reaches the Maximum Loan-to-Value (“Max LTV”).

<img width="632" alt="image" src="https://user-images.githubusercontent.com/73505363/122315206-30e96b80-cf4c-11eb-9585-a172b2085bf2.png">
Fig 5: Illustration of borrowing lifecycle

### Automated Market Making designed for lending / borrowing protocols
The borrow rates embedded in ayTokens are determined using an automated market making formula, for example using the constant power sum formula between the balance of the Yield Tokens and that of collateral asset, following Yield Space (https://yield.is/YieldSpace.pdf), suitably modified to allow for capital efficiency following Uniswap v3 (https://uniswap.org/whitepaper-v3.pdf).

### Platform Architecture that supports ecosystem development

<img width="843" alt="image" src="https://user-images.githubusercontent.com/443225/120918758-9c2f7400-c6e8-11eb-9bbd-d940c6c397b6.png">
Fig 6: ALEX platform is designed to allow for implementation of arbitrary trading strategies

## Deliverable 
Low-fi mock-up (mocknet and local repo cloning) of the ALEX DeFi platform, which enables users to lend & earn BTC, borrow BTC, mitigate risk with BTC short positions, and maximize upside with BTC-leveraged long positions.

### Budget & Milestones
Total requested grant for this deliverable = $30,000
Estimated time of completion: Early July

### Milestone 1
We like the design of [Balancer V2](https://docs.balancer.fi) and are borrowing heavily from their ideas to design our platform to allow for implementation of arbitrary trading strategies.

Equation abstracts rebalancing and market making logic, while Pool encapsulates the value of a strategy.
Pool abstraction allows aggregation of the assets of all ALEX pools into a single vault, bringing many advantages over traditional DEX architecture.

Key base component specifications (shown in diagram below), which include:
- **Vault** specification: Vault holds and manages the assets of all ALEX pools. The design has many advantages over the traditional DEX architecture; it enables abstraction of pool logic, significantly cheaper multi-leg trades, high frequency trading, flash loans, and more.
- **Pool** specification: Pools handle the logic of dynamic trading strategies, whose token rebalancing are then handled by Vault. Pools consist of the Strategy Token whose value is driven by Collateral Tokens. Rebalancing logic is driven by Equation. Pool issues Pool Token to liquidity provider, representing a proportional ownership of that Pool
- **Equation** specification: Equation triggers Pool rebalancing. This allows creation of any arbitrary rebalancing strategies to be deployed as a pool.

<img src="https://yuml.me/alexgo/alex-v1-class.png">
Fig 7: Class Diagram (work in progress, subject to change)

### Milestone 2
Low-fi mock-up that users can engage with, which includes:

- User dashboard that displays the following:
    * I see My Balance, summary list of all tokens I hold.
    * I see My Borrowing, summary list of all borrowings I have.
    * I can click on each token for more details.
    * Those Yield Tokens "in the money" will be highlighted.
    * Those borrowings close to liquidation will be highlighted.
    * Upon clicking a token (non Yield Token), I see my current balance, associated Yield Tokens I hold, and maximum I can borrow using the balance as the collateral.
    * Upon clicking on an Yield Token, I see my current balance, and maximum I can borrow using the balance as the collateral.
    * Upon clicking on any borrowing, I see my current balance, current LTV, maximum LTV, Liquidation penalty, maximum I can borrow further, maximum I can repay, maximum I can top-up, and the list of Yield Tokens I can roll into.
- Lending capabilities:
    * I see My Deposits, summary list of Yield Tokens I hold, which I can buy, sell, or borrow against.
    * I see Available Deposits, summary list of available Yield Tokens I can buy, together with max amount I can buy.
- Borrowing capabilities:
    * I see My Borrowings, summary list of all borrowings I have, which I can borrow more, repay or top-up.
    * I see Available Borrowings, summary list of all available Yield Tokens I can mint, together with max amount I can mint.
    * I can top-up Collateral any time or when I receive Max LTV notice.
    * If I receive Max LTV notice and do nothing, Collateral will be liquidated to burn Yield Tokens and return residuals.

![](https://yuml.me/alexgo/Alex-v1-use.png)
Fig 8: Use Cases (work in progress, subject to change)

![](https://yuml.me/alexgo/Alex-v1-activity.png)
Fig 9: Activity Diagram (work in progress, subject to change)

**Comment by RaffiSapire** [comment]
Hi @rachelyingyi Thanks for applying. We would like for you to come back with an updated scope 1-2 weeks out from the end of the accelerator. We will fund future work building on top of and furthering what is done during the accelerator. Keep in mind, we wouldn’t provide a grant to make something that is already built but is closed source open. We’d be excited to fund future open source work here.
