### ISSUE TITLE
Toolkit for generating smart contract and web explorer from data model

### ISSUE THREAD

**Issue by arkoc** [stacksgov/Stacks-Grants#133]
**Background**

We are Bransfer from the Stack Accelerator program. We are helping traders to move BTC between exchanges extremely fast and we use Stacks to keep records of all transactions that are done off the bitcoin chain. As we were implementing Stacks integration, we thought that this could be a very common case. When software wants to store data in blockchain (for credibility) and have an explorer on this data.

**Project Overview**
We provide a command-line tool. Input for this command-line tool is the data model. Data properties that you want to store in blockchain. Outputs are smart contract code and front-end explorer over that smart contract.

**Scope**
Final delivery is a command-line tool or/and website where users can enter data model. Like:
```
from: string
to: string
amount: decimal
```
There are 2 Outputs:
1. Smart contract, with hashmap of these entities and a function to add a new entry in it.
2. React frontend which is basically explorer over that hashmap.
3. Example of code that inserts data to smart contract storage. (in the preferred language, we will first implement in C# as we use it as the main language now)

**Budget and Milestones**
Total Grant Request:  17,000$

M0: Testable MVP in test-net with basic functionality. (10h) 5,000$

M1: Fully functional command-line tool as described in Project Overview. (10h) 5,000$

M2: Website which will do the same as a command-line tool. (10h) 7,000$ (including ops costs for running website)

**Team**
We are founders of https://bransfer.io.  About us: https://www.bransfer.io/about-us

**Risks**

**Community and Supporting Materials**

**Extra**
Anyway, we are developing this tool right now, as we need this for our main product. Grant will help us to spend more time on it and polish it to "near" perfection.

**Comment by arkoc** [comment]
Edited original post:
1. Because 10.000$ + 7.000$ is not equal to 20.000$ :)
2. Updated my Grammarly to PRO version, so I fixed some grammar issues.
3. Fixed some some punctuation issues.

**Comment by arkoc** [comment]
Edited original post one more time:

1. Added M0 milestone.

M0 milestone will help to understand if this tool useful community and will allow collecting early feedbacks to understand moving direction.

**Comment by RaffiSapire** [comment]
Hi there, unfortunately this is a pass for us. We're not seeing additional value driven by this scope for the community, and this is also being funded already by the accelerator.
