### ISSUE TITLE
ROYALE - Real-time PVP Skill-based gaming platform

### ISSUE THREAD

**Issue by sberemski** [stacksgov/Stacks-Grants#135]
### Background
_What problems do you aim to solve? How does it serve the mission of a user owned internet?_

We are looking to explore the opportunity offered by blockchain technology to create novel game experiences and to create game infrastructure that enable novel game experiences or business models. 

We want to create technology that enables creators and consumers to retain more of the economic value they create relative to the status quo with regards to platforms and publishers.

### Project Overview
_What solution are you providing? Who will it serve?_

The initial solution is to launch a game on the stacks blockchain that showcases how games can use the blockchain for identity and payment processing. 

The MVP of the game has already been created and is [live](https://nanoroyale.com/). 

We then want to extend the game to enable a creator and player owned ecosystem to flourish. 

Players compete in Stacks Royale for fame, glory and a little profit. They can play the game to earn tokens. Tokens can either be trade for other cryptocurrencies or used to purchase in-game avatars. In-game avatars are tokenised as NFTs and can either purchased or sold in a market place.

Creators are incentivised to make in-game avatars which are then minted in accordance with player wishes through a crowd-funding model. If enough players commit tokens to a particular concept, that token is minted and made available to the players who voted for it.

### Scope
_What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?_

### **Stacks Royale**

**Stacks Royale is a game with the following properties:**

1. 2D game that runs in the browser
2. Player versus Player
3. Quick to learn, hard to master
4. Skill game - Players stake stake with the top performers winning the process
5. Players are represented by avatars in the game space

**Success is measure using the following metrics:** 

1. New users
2. Active users
3. Retention (D1, D7, D30)
4. Engagement (Sessions per DAU)

### **An NFT market place**

Allows players to buy and sell avatars

**Success is measure with the following metrics:** 

Volume transacted over time

### Budget and Milestones
_What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone._

### M1: Art style refresh and marketing page

*$3,000*

1. Commission a designer to create and implement an art style for the game to make it feel premium, improve the UX and to enable other artists to build avatars for it in the future.
2. Technical implementation of the art style and assets
3. Marketing page to promote the game and ICO
4. Create a marketing plan for the ICO
5. Scope out an ICO on the Stacks blockchain from a technical perspective 

### M2: Integrate with Stacks and prepare ICO

*$2,000*

1. Port the payment system of Royale to the Stacks blockchain
2. Implement Heap to track game performance and implement success metrics
3. Mint a new token that will be used to transact within the Royale ecosystem
4. Bring on marketing partners and create media campaigns to promote ICO

### M3: Market and run ICO

*$2,000*

1. Execute marketing plan
2. Run ICO and distribute coins to participants

### M4: Avatars and NFT marketplace

*$10,000*

1. Avatars can be won in the game
2. Avatars are displayed prominently in the game leaderboards, end of game screen and during combat
3. Implement an NFT marketplace allowing players to buy and sell in game avatars. 

### M5: Bring avatar creators into the ecosystem

*$4,000*

1. Creators can submit new avatar designs to the NFT marketplace
2. Line up 10 creators to make avatars
3. Promote marketplace to creator communities

### Team
_Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work._ 

[Hmexx](https://github.com/hmexx/) - Full stack developer and CTO with 2x exits

[Stan Beremski](https://www.linkedin.com/in/stanislavberemski/) - Product leader with games experience at NaturalMotion, Zynga and King. Worked on [CSR Racing](https://g.co/kgs/1CHEux), [Dawn of Titans](https://g.co/kgs/hZ5ad9) and [Farm Heroes Saga](https://g.co/kgs/B5NmqV)

We are missing product design skills and are looking for collaborators.

### Risks
_What dependencies or obstacles do you anticipate? What contingency plans do you have in place?_

Product risk

1. The long term retention of the game cannot be improved sufficiently to build sustain the DAU numbers in the long run. This will be mitigated by using the in game analytics to identify the problem and design product updates to deal with it. 
2. Players are not interested enough in the avatars as a reward leading to low usage of the NFT marketplace. This will be mitigated by doing primary user research to understand why players are not interested and then designing solutions to the problem.
3. The marketing plan for the ICO doesn't generate sufficient interest in the project to provide us with the investment to continue to build out the product and ecosystem. This will be mitigated by reducing the scope of the project so that we can continue to build it with out the additional investment. 
4. The transaction costs and finality time of payments are too high for users which makes the game uneconomical or unappealing. This will be mitigated by batch processing transactions and better message to players around the SLA so they know what to expect.

Technical risk

1. Private key or Data leakage: Minimize amount of tokens on application servers. Run penetation tests. Use multi-sig accounts for large accounts and contract owners. Use smart contracts wherever possible to distribute rewards in a trustless manner.
2. Performance/Scaling: Use cloud infrastructure with auto-scaling nodes. Use CDNs to serve all static content. Spread game servers over several continents to reduce latency/ improve game experience.  Rely on 3rd party infrastructure, such as Discord, for non-game-specific features (such as chat, statistics, tipping, etc)

### Community and Supporting Materials
_Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?_

### The game have proven really popular and has been growing organically with great user feedback

- 200K+ games played in 60 days, with almost no marketing.
- 10,000 users in 2 months. No growth marketing spend.
- Prizes won by 6,288 players
- 1,300 users actively engaged on the game's Discord server
- Great retention:
    - Top 3 players have taken part in 6,596, 5,208 and 4,321 games respectively.
    - Increasing player base 2 months after first reddit post.
    - 
![1](https://user-images.githubusercontent.com/948247/121774077-3cb5e600-cb78-11eb-9b58-76a07d4db231.png)
![2](https://user-images.githubusercontent.com/948247/121774078-3cb5e600-cb78-11eb-9ec7-2efda7e772d3.png)
![3](https://user-images.githubusercontent.com/948247/121774080-3d4e7c80-cb78-11eb-97d9-9ccd8f6638fc.png)

## Community feedback and support is key to the project

There is a vibrant and growing community for the game on its own Discord channel. Product updates and announcements are handled through this channel.

We also plan to do a series of blog or vlog posts on the implementation of the game and the NFT marketplace for the Stacks community to share our experience and progress with the project.

**Comment by RaffiSapire** [comment]
Hi @sberemski 
Unfortunately, this is a pass for us. 

It looks like this is a pre-existing product that you want to expand with grant funding. I don’t think that’s an issue per se but it feels like Stacks is an afterthought here. We would rather see social proofs within our community that there is interest for something like this. In addition, funding a project's ICO is out of scope for us. We're focused assessing to what extent a project:
1. Community Growth / reaches new people
2. Makes Participation easier/accessible
3. Demonstrates Technical/Mission-oriented Possibilities 
Here, unfortunately it did not check the boxes.
