### ISSUE TITLE
I want to Evangelism/Ambassadorship targeting India 

### ISSUE THREAD

**Issue by jiten123321** [stacksgov/Stacks-Grants#14]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

 **What problems do you aim to solve?** 
India is a special county in which the population is 1.3 billion but only a 125million people know English rest 60-65% of people know Hindi because Hindi is the national language of India so the problem comes when we create content/videos/events in English or another language to target Indian people. 

**How does it serve the mission of a user-owned internet?**
Over 560 million internet users, India is the second-largest online market in the world, ranked only behind China. They estimated it that by 2023, there would be over 650 million internet users in the country. 

So we have to spread the awareness of Blockstack by creating regional articles, videos and meet up/webinars, etc, so can the people of India understand the importance of user-owned internet.  

## Project Overview

 **What solution are you providing?** 
I'm was an Ambassador since 2017 for lots of projects and most of the projects I'm working with I help them localize their project In India by creating contents/ events/ Infographics in Regional languages.  

**Who will it serve?**
So I will create Article/ Translated article, Videos, Meet-up, and Webinars in Hindi and Odia language to expand awareness about Stack 2.0, Clarity, BlockStack ecosystem, and uses cases in India to serving or targeting Indians. 

## Scope

**What are the components or technical specs of the project?** 
As this will be a community growth project to it has no technical specs but yes this project, I'm targeting not only users but also developers because I have created some Blockchain clubs in various colleges and universities where I will visit or do meetups/webinars to tell them about Blockstack. 

**What will the final deliverable look like?** 
First, I will create huge content in Hindi and Odia language about Blockstack for #context, then I will do events to spread awareness and when people make a search about Blockstack after my event then they will find regional contents which will help to establish a connection and this is a trial and tested method.  

How will you measure success?
I will use community management tools like Eventribe to measure my success. 

## Budget and Milestones
I want to Apply for 2 grants in this single application which will be in two phase 1st phase(8weeks) for content creation, the second phase(8weeks) for events. 
**What grant amount are you seeking?** 
 5K in total 2.5k for the first phase and another 2.5k for the second phase 
**How long will the project take in hours?** 
>For the fist phase

I will create 2 videos per month and will share it on my YouTube channel with 1.7k subscribers.
1videos takes 5hrs for content + 3hrs for record +4 hrs for edit = 12hrs
2*12hrs= 24hrs hr for two videos 

4 Articles per months on my personal blog or third party publication like coinmonks/Hackernoon (If created in English)
1 Articles take ~24 hrs for research and writing so 4 articles will take 4*24hrs= 96hrs

4 Infographics per month on my social media like twitter, linkedin, facebook, etc.
1 Infographics take 4hrs so 4 infographics will take 4*4=16hrs 

>For the second phase 

I will create 2 events per month 
One event takes 7-15 days because if it is an online event then I have to publish and market the event then if physical event then has to organize place, tools, etc or visit to universities to talk with the authority and so on. 

But one event goes from 1hr to 2hr and minimum attendees 50 maximum 200.

Later after event I will add the event recording into Youtube to help in later in long term.

## Team

**Who is building this?** 
In my team, there are three people but content creation and event speaking/hosting are done by me but they help me with edit, social media management, and event management, etc. 

**What relevant experience do you bring to this project?**
As I have good experience as an ambassador so I have some tactic strategy to build awareness of a project in my region and I'm sure it will work great for Blockstack. 

 **Are there skills sets you are missing that you are seeking from the community?**
I only wish to community to provide some push to my work just by liking, commenting, and sharing which will help me lots 

## Risks

**What dependencies or obstacles do you anticipate?** 
As corona is going on so it may affect physical meetups.

**What contingency plans do you have in place?**
So I will go with online events.

## Community and Supporting Materials

**Do you have previous projects, code commits, or experiences that are relevant to this application?**
Yes, I have a good experience(4+ years) I have worked for Ballet, Elitium, Status network, etc as an ambassador, and currently working with Algorand, Polkadot, as an ambassador. 
What community feedback or input have you received?

**How do you plan to share your plan to the community over time and as the final deliverable?**
I physically visit or share it online.

**Some samples of my work of last month:**
Webinar for Radix- [Click here](https://youtu.be/YIGfwx9GLyA)
Algorand webinar- [Click here](https://youtu.be/JkzpD37pWyI)
Hackernoon - [Click here](https://hackernoon.com/what-is-true-blockchain-interoperability-cqr3xnb)
Coinmonks- [Click here](https://medium.com/coinmonks/title-future-of-bitcoin-in-india-e056f7a6807b)

Regional language articles- 
NEAR India publication- [Click here](https://link.medium.com/3ip6wATRH9 )
Beam India publication- [Click here](https://link.medium.com/oc8ABVYRH9 )

**Comment by RaffiSapire** [comment]
Hi @jiten123321, I'm Raffi, I'm working with the Foundation on the grant program. We're syncing up to learn more about possible ambassador opportunities for you and others. Will be back soon!

**Comment by jiten123321** [comment]
okay

**Comment by ryanarndtcm** [comment]
Hey there, I am researching more on our end as to how this may fit best into the ecosystem (re: evangelist program at Blockstack). I apologize for the delay as the details are worked out.

**Comment by jiten123321** [comment]
> Hey there, I am researching more on our end as to how this may fit best into the ecosystem (re: evangelist program at Blockstack). I apologize for the delay as the details are worked out.

Okay ...please take your own time.

**Comment by ryanarndtcm** [comment]
Hi @jiten123321 

I would suggest that your idea would be a better fit for the Blockstack Evangelist program, which can help cover some of the costs of your meetups. You can read more about it here: https://community.blockstack.org/guide#evangelist

In future, we will reconnect with you should the Stacks Foundation launch an evangelist type program more in line with the work you are doing.

Thank you
