### ISSUE TITLE
AccountOne

### ISSUE THREAD

**Issue by accountone88** [stacksgov/Stacks-Grants#141]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

AccountOne will be the first crypto native financial services platform that will enable clients to submit their information anonymously to third parties to receive offers for financial based products. 

The current leadgen platforms capitalize on monetizing a users information by selling it to multiple parties (Nerd Wallet or Credit Karma), and are able to provide more relevant offers by learning more about a users data, spending habits, and interest. 

AccountOne will put the control back to the user and force third-parties to interact with data that is self-selected and most importantly owned by the users until the point where a decision is made to move forward with an offer. 

**Project Overview**
What solution are you providing? Who will it serve?

Allowing individuals to receive offers from third-parties on financial products without giving away data for free/without consent/ or full understanding. 

It will serve mostly under-banked communities and individuals that want to protect their data from large banks and financial institutions 

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

Leveraging the Gaia/stacks architecture to store a users private information 

Final deliverable is a mobile application where a user can control a data submission to a third party and receive a binding offer to proceed with a financial product 

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Expected Timing: 40 hours 

10 hours - back-end data base build 
10 hours - testing 
10 hours - front-end user interface 
10 hours - integrating third-party into platform 

Total Grant Request: $10k 

M1: Scope of work, deliverables, and grant amount of total.

M2: Etc.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Looking for a stacks development team to help kick-start the project to MVP 

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

Onboarding a third-party to the application will create challenges. For MVP will only need to test the general structure and idea. 

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

Looking for any helpful insight and advice from the community.

**Comment by RaffiSapire** [comment]
Hi @accountone88 thank you for your submission. We discussed and unfortunately this is a pass for us. Reason being, the grant is not well scoped, and we are concerned that there is not a development team already part of this submission.
