### ISSUE TITLE
Cerebro Wallet: 5 new assets with own blockchains, including STX

### ISSUE THREAD

**Issue by eugeneive** [stacksgov/Stacks-Grants#15]
## Background

Due to market fluctuation and exciting technological innovation, recently cryptocurrency was in the center of attention. At Cerebro, we believe that the increase of functional compatibility and collaboration between crypto projects (blockchains) will increase the pace of those innovations. We also believe that providing the accessibility for a basic unit of every project (coin) for the community is of crucial importance. That is why, we are creating a multicurrency wallet with an open source code where users will be able to store and exchange the greatest part, if not all current and future cryptocurrencies, decentralized.

## Project Overview

There’s no chance to have transactions without a wallet. Having a good wallet is a necessary condition to get protected from various threats, break-ins or fraud, that’s why you ought to have an authentic wallet that helps you safely interact with popular blockchains including Blockstack.

Our wallet for the first currency Bitcoin (mainnet + testnet) [was launched last week](https://twitter.com/BlockstackApps/status/1304154813882462208). And now we intend to go to the next step of our development - connecting new blockchains. Through Cerebro we want to provide access to the Blockstack community to various currencies.

## Scope

Current project scheme and scope of work:

![cerebro-grant-scheme](https://user-images.githubusercontent.com/15582487/93710069-4dd34880-fb4c-11ea-9d4a-73531c7af84e.jpg)

During 4 weeks, we are planning to add support for Bitcoin Cash, Bitcoin SV, Litecoin, Zcash and most importantly STX (testnet). As a result of our work, the following functions will be provided:

- creating accounts
- deleting accounts
- customized name of accounts
- importing accounts with a private key
- exporting accounts
- receiving coins
- sending coins
- transactions history
- viewing coin price
- comparing coin price with other coins in the wallet (coins chart)
- open source implementation code will be available on Github: https://github.com/cerebrowallet/cerebro-wallet

!Attention. STX (mainnet) will be supported right after launching the main network, whenever it is launched.

## Budget and Milestones

Plan implementation is evaluated in $5000 with the following 4 weeks long steps to take:

- Connecting bitcoin-like blockchains: Bitcoin Cash, Bitcoin SV, Litecoin, Zcash.
- Connecting STX (testnet).

## Team

[Eugene (Ive) Ivchenko](https://twitter.com/eugeniusive) is a user-oriented product manager. For 10 years, he’s been creating products that later managed himself. His journey to the world of cryptocurrency started with designing cryptocurrency wallets and exchanges and continued at Guarda Wallet, where he held a position as the Chief Product Manager and upgraded both web and mobile versions of the wallet. Then he was involved in Dappy and other projects. _His next goal is to make Cerebro the leading mass application built on Blockstack._

[Pavel Andrianov](https://github.com/andrianovp) is a full-stack developer with 15+ years of web applications development. Started working at Cerebro in 2019. He is a digital nomad that you won’t meet twice in one place. Bearded, tattooed, fond of hiking in the mountains and cryptocurrencies. Among everything at Cerebro, he’s mostly keen on technology and the idea of Blockstack. _He works every day to create the best future for Cerebro and its users._

## Risks

We do not experience any uncertainty or lack of skills and thoroughly assess our capacities to implement our plan.

## Community and Supporting Materials

Beta-version of Cerebro wallet is available via the link https://cerebrowallet.com, while the open source code you will find here https://github.com/cerebrowallet/cerebro-wallet. We’ve received a range of positive feedback considering the high quality of UI and UX of Cerebro from @muneeb-ali (Blockstack CEO), @louiseivan (an external consultant at Blockstack PBC), @MarvinJanssen (works on a cool project Ryder) and others. We have a fairly tiny and thoughtful schedule of incrementing new blockchains. We use a flexible development approach that’s why at any moment we are ready to present our progress and results to Stacks Foundation and community through official Blockstack channels (Discord, Forum etc.)

**Comment by friedger** [comment]
I don't think that the implications for non-blockstack chains should be financed through this grant.

What does it take to add a new chain? What does your app architecture look like? Do you the rosetta api?

**Comment by eugeneive** [comment]
Hey @friedger,

The scheme in the first message contains answers to your questions. We are independent of external developers and we connect each blockchain directly. There is no reason to use the Rossetta API. But we will consider such a possibility in the future when the developers will solve the issues and provide the library in a suitable programming language for us.

Our goal is to create a multicurrency wallet in the Blockstack ecosystem. So that the community can interact with other blockchains, decentralized, rather than through exchanges or other external wallets. Support for new blockchains including STX is the first stage without which it is impossible to build a full wallet with built-in exchange and etc.

**Comment by MarvinJanssen** [comment]
Great project @eugeneive.

I see where @friedger is coming from. Based on previously approved grants, it seems like the Foundation is looking for grant proposals that directly impact the Stacks ecosystem in some way. Then again, it all comes down to the interpretation of what it means to "serve the mission of a user owned internet". I would say it fits that description. Perhaps @blocks8 or @RaffiSapire can clarify. Otherwise, I assume that scoping it to creating a technical foundation (abstraction layer) to support multiple chains/cryptocurrencies with a STX implementation on top would fit the bill. Perhaps an idea, out of personal desire, is to add the ability to deploy and interact with Stacks smart contracts much like you can in MyEtherWallet. (Although this could also be a separate grant proposal.)

**Comment by eugeneive** [comment]
Thanks @MarvinJanssen 

The Stacks Smart Contracts and Built-in Stacking are already in our development roadmap 🚀

**Comment by fluidvoice** [comment]
I think funding work on the other coins being added only makes sense if there will be some DEX (coin exchange) functionality but this will be just a wallet with no DEX correct?

**Comment by eugeneive** [comment]
@fluidvoice Sure. Exchange is the next step. And this is a separate grant proposal.

**Comment by eugeneive** [comment]
> Some altcoin traders have requested STX to be added to the Atomic Wallet which is just one of various multi-coin wallets. But these do not (yet) support Blockstack Auth/ID which could help bring in new blockstack users via creating new blockstack accounts ID's when running the app.

They will never support Blockstack Auth/ID. I designed the first version of Atomic Wallet and I know the company's policy. The Blotskstask community will have its own multi-currency wallet. And I hope it will be Cerebro.

**Comment by friedger** [comment]
> it seems like the Foundation is looking for grant proposals that...

We should strongly voice what we are looking for! 

I now better understand this proposal and think that it is great to extend the functionality of the wallet app. Will the domain name belong to the foundation? We have already some apps like bitcoinportfolio or shine wallet being not maintained anymore. 

To get more coins into the wallet, the architecture would need an abstraction from the blockchair api. What else need to be changed? Is integration of eth coins more difficult? 

Seeing your previous work I think you will build this. Nevertheless, could you provide smaller milestones?

**Comment by MarvinJanssen** [comment]
I think a well-rounded online wallet application built on Stacks technology will serve as a great incentive for both new and existing members of the community.

**Comment by andrianovp** [comment]
Hey @friedger,

> Is integration of eth coins more difficult?

The integration of ETH is not more difficult, but it's not on our road map, for now. Stacks Smart Contracts and Built-in Stacking have a higher priority for us.

> could you provide smaller milestones?

Taking into account that we work on project part-time, we could split work into two milestones:

1. Connection of BTC-like coins: Bitcoin Cash, Bitcoin SV, Litecoin, Zcash.
2. Connection of STX. This will include API and node as well.

**Comment by eugeneive** [comment]
> Will the domain name belong to the foundation? We have already some apps like bitcoinportfolio or shine wallet being not maintained anymore.

Let's not get carried away. This concept is still in the design stage. You can discuss it here https://forum.blockstack.org/t/designing-the-stacks-grants-process/11141

And by the way, we purchased the domain https://dappywallet.com (the project that had funded a grant in 2018), which was available for registration for a long time. It is strange that Stacks Foundation did not do it before us. We created a page with a redirect to the official Stacks wallet and Cerebro. Now the traffic has been restored.

**Comment by eugeneive** [comment]
Hey @blocks8 @ryanarndtcm
Are there any questions?

**Comment by RaffiSapire** [comment]
Hi @eugeneive after discussing it internally we are declining this grant request. What we could be interested in funding from the community is power tools that help active miners or tokenholders buy, send, and stack STX. This would look like an applicant who is already hacking on this tool, constantly in discord asking for feedback from users and iterating. A great example of a super tool that was built for a community is called https://scout.cool/. This team of two was constantly on discord asking for what information users wanted to see and created a dashboard. I could see someone creating a great wallet specifically for the stacks community like this, but this is not the spirit of this grant or the right team for that project given the response to feedback above.
