### ISSUE TITLE
SeekProtocol Grant application

### ISSUE THREAD

**Issue by faithinyous** [stacksgov/Stacks-Grants#164]
Background What problems do you aim to solve? How does it serve the mission of a user-owned internet?

Freelancing has become a core part of the contemporary economy and an essential component that private individuals and companies rely upon to deliver goods and services successfully. Around a third of all US, the workforce is also freelancing in a certain capacity, with some of them choosing to leave traditional employment to pursue freelance full time. Furthermore, freelancers have helped expand services that were previously only available to large corporate clients to small and medium businesses, giving them a boon in their development and making them more competitive. 
The current services marketplaces are siloed, and this causes friction for users to transition from one to another easily. 
Centralized marketplaces are the dominant force, represented by significant marketplaces, like Upwork and Fiverr, and the smaller ones, like TopTal and Guru. They are the de facto way that freelance platforms operate.
There is a central, trusted third party in a centralized marketplace that operates and regulates most, if not all, aspects of the freelancer-client relationship. This control starts from dictating how freelancers reach their clients, structure their projects, and manage the financial aspects to resolve disputes between them. Thus, these platforms have two major components: the marketplace and financial services.
The marketplace represents all aspects related to the job board, client-freelancer communication,  and project structure. The financial services contain the management of payments and fees, with escrow services being a vital component of the functionality of these platforms. Because financial services such as escrow require special licenses and conditions. They are generally outsourced to another party to be handled in exchange for a fee, then passed down to the users. For example, both Fiverr and Upwork rely on Payoneer to manage the financial component of the business. Payoneer, however, also relies on traditional banks, such as Bank of America and Barclays, to provide their services.
The principal value proposition that a centralized marketplace needs to offer is a combination of trust and supply. Both freelancers and clients need to trust that the platform manages their money, ensures accountability, and mediates disputes if they arise. Supply refers to the ability to provide access to as many freelancers as possible while also having a steady stream of clients to ensure freelancers’ earnings are kept at an acceptable level and not cause a race to the bottom when it comes to prices.
This is where the cracks start to show, with none of the platforms doing a great job handling these issues. 
Freelancers are the primary source of income, with the fees being paid almost entirely from the income they earn on the platform, plus charges for additional services. Most platforms charge around 20% from the freelancers plus additional fees for various services, such as applying to jobs. Furthermore, to keep freelancers competitive, an opaque layer of rules and rankings is added that is very rarely explained in any detail. Almost everything is tracked and ranked, accounts can be banned, and rules are added and changed constantly. This makes it very difficult for freelancers to keep track of, mainly when they are spread on more than one platform. The amount of tracking and ranking also tips the scales in favor of clients, with a bad review being able to compromise the freelancer.
Platforms have attempted to solve these issues in various ways. Upwork requires an application process before being admitted and regularly deletes inactive or problematic profiles. Fiverr operates as an open economy, using gig rankings to push better freelancers forward. TopTal relies on a lengthy and challenging interview process before admittance. None of these solve all the issues, however, mostly being inefficient or causing additional problems.
The standard issue for both marketplaces and gig platforms is that they are siloed. As a result, entrepreneurs, employers, and freelancers have to do some manual work to keep up with the market, and the costs are not negligible. 
Decentralized marketplaces are a completely new development, currently just starting out. They focus on using blockchain to eliminate the tomes of opaque rules and regulations that most sites use, eliminating the need for them, creating a fair and balanced marketplace both for clients and freelancers. A decentralized platform pulls its strength from the fact that all members of its ecosystem are important. This means that many of the rules and guidelines regarding the sale of goods can be decided (or at least discussed) by actual users. Buyers and sellers would have the ability to consider the guidelines on the marketplaces because the marketplace would actually value them.
Decentralized marketplaces are yet to fall into a predefined category, the way traditional platforms such as Upwork of Fiverr do at the moment, having the possibility of creating a flexible ecosystem to address any potential project. They also have a large potential in generating strong collaboration between freelancers, which is something traditional platforms failed to do. Because of the way they are set up, collaboration between individual freelancers is something to avoid on the current marketplaces. This however creates a cap on the scale of projects that can be tackled, with anything beyond small to medium scale not being feasible to be solved through a typical freelance platform. Beyond this, transparent rules and regulations can lead to a much higher quality in proposals and services offered.
Finally, there is the option of not relying on a marketplace and creating an individual network and onboarding process by the freelancer. This is currently viable only in certain situations and requires a different skillset from the freelancer, with the ability to create and manage a business being paramount in this scenario. Furthermore, a host of ancialiary skills are necessary, from managing the financial aspects and creating a website to creating the necessary network to find work. There is also the startup time, which can be much longer 

Project Overview What solution are you providing? Who will it serve?
Decentralized marketplaces are a completely new development, currently just starting out. They focus on using blockchain to eliminate the tomes of opaque rules and regulations that most sites use, eliminating the need for them, creating a fair and balanced marketplace both for clients and freelancers. A decentralized platform pulls its strength from the fact that all members of its ecosystem are important. This means that many of the rules and guidelines regarding the sale of goods can be decided (or at least discussed) by actual users. Buyers and sellers would have the ability to consider the guidelines on the marketplaces because the marketplace would actually value them.
Decentralized marketplaces are yet to fall into a predefined category, the way traditional platforms such as Upwork of Fiverr do at the moment, having the possibility of creating a flexible ecosystem to address any potential project. They also have a large potential in generating strong collaboration between freelancers, which is something traditional platforms failed to do. Because of the way they are set up, collaboration between individual freelancers is something to avoid on the current marketplaces. This however creates a cap on the scale of projects that can be tackled, with anything beyond small to medium scale not being feasible to be solved through a typical freelance platform. Beyond this, transparent rules and regulations can lead to a much higher quality in proposals and services offered.
Finally, there is the option of not relying on a marketplace and creating an individual network and onboarding process by the freelancer. This is currently viable only in certain situations and requires a different skillset from the freelancer, with the ability to create and manage a business being paramount in this scenario. Furthermore, a host of ancialiary skills are necessary, from managing the financial aspects and creating a website to creating the necessary network to find work. There is also the startup time, which can be much longer 

Scope What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

To be able to achieve what we want to do we will start from making the api and application side for onboarding the companies and providers to make it easy for them to create a wallet and connect to the blockchain using simple api. This will be the solution to onboard people who do not have the ability to get into the blockchain world.

Final deliverable will be:
Backend
create/manage user for companies
Allow companies to create user for their provider
Secure way to keep the user profile data
Allow company to create job on smart contracts
Allow approved provider to accept jobs on the company

Frontend
Registration
Company view approved provider and provider profile
Create jobs
View job status

Budget and Milestones What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Milestone1 - Wallet creation and onboarding provider (2 month - 2500 USD)
Create flow diagram for onboarding process
Setup database and algorithm for security
API to create wallet and company profile
API to create provider if provider does not exist (if exists then become approve)
API to call smart contract and create jobs
Setup job smart contract

Milestone2 - Provider access job and accept job where company approved (2 month - 2500 USD)
API for provider to accept the job company created
Company support the fee when provider accept job (blockchain gas fee)
Secure way for provider to accept the job only when they are approved by company
Start wireframe for UXUI

Milestone3 - Create Responsive Web UI (3 months - 3000 USD)
Web for Company/Provider registration
List of provider (create through API only)
Company profile
Create job
Job status
Provider list

Risks What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

Risk: KYC provider needs to be done. For many different countries it could be hard to kyc each of them correctly. We are starting from our company as a test case to prove that it will work.

Team Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work.

Apiporn Simapornchai
	https://www.linkedin.com/in/faithinyou/
Pakorn Subpoonkerd
	https://www.linkedin.com/in/pakorn-subpoonkerd-b50348b1/
Sahib
	https://www.linkedin.com/in/sahibanandsongvit/ 
JoeZ
	https://www.linkedin.com/in/joezcc/ 

Missing skill sets
Blockchain and smart contract security
Wallet security

Link to previous work
https://www.seekster.co/ 
https://albedofront.gtech.software/ 
https://stock.sarathat.com/ 

Community and Supporting Materials Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

We do have the application that we want to onboard providers on to blockchain (Seekster). During the development process we will update the community weekly for feature updates and what has been done.

**Comment by RaffiSapire** [comment]
Hi @faithinyous thank you for your submittal. Unfortunately, this is a pass for us. Here is some feedback:
Overall, it didn't seem specific or beneficial to the Stacks community or ecosystem. There are also many of these that exist and we couldn't convince ourselves building it on the blockchain is a core solution to a problem that exists. If in the future you'd like to pull out something specific to stacks community we'd be happy to review.
