### ISSUE TITLE
Cross-chain funding site using USDC as monetary vehicle integrated with Stacks. 

### ISSUE THREAD

**Issue by MicahDevs** [stacksgov/Stacks-Grants#168]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

Our product solves the issue of project funding without gimmicks across numerous chains with USDC used as a fair, stable and reliable commerce vehicle. We hope we create a platform for reliable funding, no matter if the sentiment is bearish or bullish, and we likewise are building with as much transparency and fairness as possible by not baking in a token of our own. 

**Project Overview**
What solution are you providing? Who will it serve?

We are solving the issue of ad-hoc funding drives, often self-populated and pushed, by projects within the blockchain space. Likewise, we are enacting strict guidelines including code audits and/or KYC (kept private if requested) so as to ensure projects approach with the best foot forward while protecting retail investors.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The components will include react-built web3 front end which is finishing development now, a custom CMS and API for interaction with the front end plus smart contracts, hopefully across many networks including Stacks. We have the CMS / API gateway built out, and are finalizing the web3 interface while finishing our first set of contracts for our first chain. 

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

We would like to raise $25k here to fund development of contracts for the Stacks blockchain and to partly help release iOS and Android version of the platform so users have as many opportunities as possible to fund and invest in projects across the blockchain ecosystem without the current ad-hoc system.

Total Grant Request: 

M1: Delivery of smart contracts customized to Stacks and tied into API/CMS, 6-8 weeks delivery. $2400

M2: Inclusion of Stacks into iOS/Android applications, 24 weeks delivery. $22600 (15% of predicted total)

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

We have an in-house full stack developer who has worked on numerous blockchain projects and has graduated from a good university in Germany with a CS degree, a project lead who has team experience in healthcare, graduate as a STEM student, and worked as a front end web dev lead, a project manager with 40 yrs of Fortune 50 experience as an engineer/programmer with experience running his own business, plus an intern from a top U.S. Ivy with primary focus on data, marketing and CS.

The areas we are a bit deficient in right now are in legal/compliance (incorporation) and finance plus crypto-centric marketing. We have had meetings to rectify some of this.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

The risks right now center around project funding, hence this focus. Our funding requirements are lightly loaded currently but I foresee the possibility and potential to grow these needs as we expand with marketing, app development, market fit and broader adoption.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

We have no community feedback currently as we are not quite to MVP; I can privately share developer repos, temp site URL, project/business name, pitch deck and other materials as requested. Once we are at MVP, ideally we will focus on guerrilla marketing among the main popular venues. Our hope is to scout and find viable talent and use the site plus our market contacts to help them reach their goals, if viable.

**Comment by RaffiSapire** [comment]
Hi @MicahDevs thank you for your application. We discussed today at grant committee and unfortunately, this is a pass for us. The reason being is, after reviewing this application, it is unclear what you all are actually doing and what problem it solves for users. Thank you for the time you took here and we wish you the best.

**Comment by MicahDevs** [comment]
It would have opened Stacks up as an option on the funding site for project builders but we are not going to out of pocket the development costs for chains that require special coding adds such as this.

**Comment by MicahDevs** [comment]
It solved the problem of funding fragmentation as mentioned but I will not bother you more in comments. It will be clear when live and we tried.

**Comment by MicahDevs** [comment]
Thank you for the consideration. You are free to approach us in the future of you feel differently. Have a great week.
