### ISSUE TITLE
Personal Knowledge Garden

### ISSUE THREAD

**Issue by bamanczak** [stacksgov/Stacks-Grants#175]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

There are plenty of tools on the web to allow you to create your personal knowledge garden. Among the popular ones you might find roam research, Workflowy, Evernote or recently launched Kosmik… but all of them require you to hand over your data to a private company. If you don't trust those vendors you could use tools like Zettlr, Org-mode, TiddlyWiki… but all of them require you to either set up your own dedicated server or to host your files somewhere. Which ends up with the same problem as the private-owned tools, as you could use GitHub, Dropbox, Box, OneDrive, Google Drive or many more tools to host your data but… you still end up with a private company owning your data and having to trust that they encrypt those properly.

**Project Overview**
What solution are you providing? Who will it serve?

The solution I design is a Stacks-based (Gaia-based) private and decentralized tool for creating your own Knowledge Garden.
The garden is based on files saved using Markdown syntax, which allows easy portability between similar products. The goal is for the users to be able to save and store private notes, with links between them and search. What will be stored there is up to the user: personal diary, personal knowledge database, maybe decentralized team wiki?
Contrary to similar projects from the past (see Risk1 from _risks_ section) this project has a clear focus on usability and friendly design to make sure that the project would be well received by its users. The goal is to bring not only "tech folks" but to open the Stacks ecosystem to less technical users as well.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The scope:
1. A static web app describing the project (static homepage), as designed in Milestone 1
2. React-based app integrated with stacks that allows to save markdown notes, with features as defined below
3. Usability reports conducted with initial users

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: 10 000
Timeline: more hours than 40. Spanned accross multiple weeks.

**Milestone 1**: Designs, initial usability tests and user story mapping 
Deliverables:
Grant request for M1: 1 000
Estimated hours: 40
- Initial design prototypes in figma
- Report from usability tests conducted on initial designs
- Adjusted prototypes in figma
- User Stories documented for the remaining milestones

**Milestone 2**: Initial features (v 0.1)
Grant request for M1: 5 000
Estimated hours: 200
- Homepage (static site)
- Login using stacks
- Storing of notes in GAIA with markdown support
- Usability tests for v1

**Milestone 3** (v 0.2)
Grant request for M1: 4 000
Estimated hours: 150
- Linking between notes
- Tagging of notes
- Basic search features
- Research, feedback gathering and documentation for future milestones

**Future Milestones** 
(not yet estimated, to be planned separately after initial success)
- Detailed search within all notes
- Isolated notepads (folders) for notes
- adding other data types to notes (e.g. images)
- sharing notes and full folders between multiple users
- saving publicly available notes
- feeds/blogs based on the project

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

This is planned to be a 1-person project. I am a software developer and test engineer with commercial experience since 2013. I worked mostly on commercial corporate projects with closed source code. My experience is visible e.g. on [Linkedin](https://www.linkedin.com/in/bruno-manczak/). My profile says I worked mostly as test/qa but my key focus is test automation and I never limited myself with the automation codebase only, as I was eager to deliver new features or fix defects as well.
I have experience working mostly in Angular from modern web-based technologies and I used React mostly for smaller sideprojects.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

**Risk 1**: similar failures from the past.
A list of failed project, available on heywebby.app that attempted to leverage Gaia for storing notes, recipes, tasks is not a short one: https://magicspoon.xyz/, https://safenotes.co/, http://spectrenotes.com/, https://pnotes.online/, https://notes.shellapps.com/ : all of those projects now return 404 error or are used by domain sellers. This clearly shows that such a tool needs to be an Open Source project, not a personal project, with enough funding to sustain the domain for multiple years. 
To mitigate this risk, all codebase will be OpenSource and part of the grant funding will be used to assure domain and hosting for at least the next 5 years. Alternatively, free solutions like Github Pages would be explored.

**Risk 2**: Delay
I work fulltime at a company that is my key focus. This it might be the case that project deliverables would be delayed as the project will be developed after hours.
There is no possible mitigation for this risk at the moment. I need to be upfront about it and accept the risk.

**Risk 3**: Unforseen difficulties and underestimated complexity
There are reports created by Gartner or PMI which showcases that multiple software projects are underestimated or end up in failures. My own experience also showcases that under-estimating features and projects is not an uncommon thing.
To mitigate this risk, I have consulted the scope with other collegues and I plan to leverage the power of the web and my strong social circle in case of such an event, to get advice and guidance from other developers.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

My experience is clearly visible in my LinkedIn. There is no community gathered around this project yet, however the notion of "mind garden" is becoming increasingly popular. See e.g. the case of Roam Research which became one of the most powerful tools in this area.

**Comment by RaffiSapire** [comment]
Hi @bamanczak we discussed the grant at length today and unfortunately it's a pass as it is today. Reason being, we don’t think theres a user base here. We would be happy to reconsider a version of this application that demonstrates demand from the community (maybe by usage, and consistent usage and engagement over time). Thank you for taking time to apply.

**Comment by bamanczak** [comment]
Hi @RaffiSapire!
Thank you for your review. This is sad news as I really hoped to develop this project with your support as I believe it would have a very wide variety of use cases.

However in this case I understand that the risk that I also highlighted in the proposal is simply too high.

> Risk 1: similar failures from the past.

I hope we still will have a chance to develop something together with stacks 🙇

**Comment by RaffiSapire** [comment]
Hi @bamanczak - absolutely. Would be happy to brainstorm other ideas with you during either of our open office hours this week or next. Please feel free to join!
