### ISSUE TITLE
Stick - Accredited seed funding SaaS.

### ISSUE THREAD

**Issue by MicahDevs** [stacksgov/Stacks-Grants#183]
We are Stick;

We are a cross-chained seed funding market running on USDC rails and would like funding to add Stacks smart contract integrations to our platform so founders have another option to grow Stacks total project reach.

This grant will fund development of smart contracts which integrate Stacks into our platform.

We believe a general business contract will cost around $7,000 to complete. This would include a Stacks contract comparable to ERC1155 which will interact with fungible, semi-fungible, and non-fungible tokens enabling Stacks Development teams listing opportunity & sales of tokens, directly to accredited investors, using the SaaS we have developed.

Our team and risk are included in our deck, as well as some XP on previous projects. Our plan to gain users and 'community spread' is with direct marketing to accredited investors alongside our general marketing to founders looking for lift that prefer markets such as this versus VC pitching.

Our one-pager is at http://bsg-onepager.webflow.io

Our deck is at [stick.app.pdf](https://github.com/stacksgov/Stacks-Grants/files/6913701/stick.app.pdf)

Our mock is at http://blocksetgo.webflow.io

**Comment by RaffiSapire** [comment]
Hi @MicahDevs - can you please take a look at some of the other grant issues and break down your deliverables into 2-4 milestones, with clear features/deliverables at each step? 

I read through your deck, but it would be helpful if you succinctly explain the problem you're solving, why existing solutions don't make sense, and what people will be able to do with Stick, using the grant framework we have provided.

**Comment by MicahDevs** [comment]
**Background**
_What problems do you aim to solve? How does it serve the mission of a user owned internet?_

Grant options are well covered within the space but we are now witnessing increased regulatory oversight over the funding of tokenized product. Due to scope and scale, many will simply not be ideal for grant funded development alone and may require added support. This added support area is where we are positioned to assist. We connect accredited investors to tokenized projects and bypass current ad-hoc walls which include ‘VC warm introductions, insider lingo, and/or perfectly sharpened sales tooling’; this facilitate more exposure to Stacks and onboards many projects that otherwise would not have the opportunity to be built.


**Project Overview**
_What solution are you providing? Who will it serve?_

We are building a SaaS market connecting all types of accredited investors with seed funding level projects who cannot find lift through grants or niche venture capital alone. We believe the need will only grow for this and if we can provide relief for this very specific pain point the industry is now experiencing, we believe we can help further grow the space as a whole in safe, compliant and non-confrontational ways; this absolutely includes Stacks.

**Scope**
_What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?_

Our components consist of a custom content management system developed in Django, an application programming interface, a front end developed in React and main SQL database. We are running around 80% javascript, 10% solidity, 10% python currently.

To achieve interoperability with Stacks without manual control necessary for transactions, we will be required to build out contracts in Clarity which facilitates carry and sale of any tokens as needed by Stacks specific projects. We will also be required to add in functionality for a Stacks specific wallet to our front end.

Specific deliverables will include the build out and implementation of our Clarity contract which interacts with our content management system, API and front end, plus front end integration between the primary stacks wallet and our website.


**Budget and Milestones**
_What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone._

**Total Grant Request:**

**M1:** _Boarding and development of Clarity contract to match functional spec:_ 40 hours.
**M2:** _Integration between Clarity contract and content management system:_ 20 hours.
**M3:** _Test net of contracts, including 1+ week of beta tester time, dependent:_ 20 hours.
**M4:** _Integration of wallet to UI and application layer:_ 10 hours.
**M5:** _Ancillary bug testing and clean up to account for overrun:_ 10 hours.

Approx. 100 hours at nominal rate between main developer + clarity developer at $70/hr, averaged. We believe, once started, this project will take approx. 2.5 weeks as a reasoned ballpark. 


_If any other questions exist, please ask and thank you for any considerations._

_Have a great week!_

**Comment by RaffiSapire** [comment]
Hi @MicahDevs we discussed your grant at length, and unfortunately it is a pass for us. 

A standard like the ERC1155 does not exist on the Stacks blockchain yet. The other work laid out in the  grant description seems mostly to be concerned about proprietary work, which wouldn’t benefit the ecosystem as a whole, and all our grants require that grantees make their work open source. Thank you for taking time to apply.

**Comment by MicahDevs** [comment]
I'll answer this in three parts; one, obviously we would implement a fungible standard if no multi-use standard would apply, that is common sense; two, the contract also would obviously be open sourced as it is running on a blockchain - if you expect us to open source our CMS, etc. to suit you, excuse me?, and three, when you see regulation settling in, do think about the ecosystem benefit. The hubris of maxis trying to do maxi things.
