### ISSUE TITLE
Rupee Stable Coin - Stacks Chain Representation

### ISSUE THREAD

**Issue by asifshiraz** [stacksgov/Stacks-Grants#185]
**Background**
============
What problems do you aim to solve? How does it serve the mission of a user owned internet?

Crypto on-ramp bridges are available in jurisdictions that are confident of their regulatory practices, but some third-world countries, specifically Pakistan, are caught in a decision paralysis on how to deal with crypto, with impulsive bans and mixed signals from the regulators. This prevents any exchanges from establishing and has left the local community with a few circuitous alternatives: Have offshore relatives buy crypto for them, use unofficial brokers charging exorbitant fees, or use Paxful and Binance P2P functions, which are also expensive, and cumbersome.

This situation not only hinders the general adoption of cryptocurrencies in the region, but will also stand in the way of the work being done by the Pakistan Stacks Chapter.

**Project Overview**
====================

What solution are you providing? Who will it serve?

Other than officially regulated exchanges, one other alternative to improving access for the public is a local stable coin, which is denominated in the local currency, the Pakistani Rupee, instead of the US dollar, and can gradually induce people to take it as a substitute for the State currency, and not convert it to fiat. This will allow the local stable coin to continue circulating, gradually increase in size, and minimize the hurdles associated with on-ramping. 

Some of the benefits of this project would be:

a) Reduce fees associated with trading crypto from Pakistan, since the investor will not have to do round-trip fiat to crypto conversions. Fiat will be represented by a gradually expanding pool of tokens which will absorb a lot of round trip fees, as well as introduce efficiency, when entering and existing crypto positions.

b) Offer a mechanism for day-to-day transactions denominated in the Rupee, allowing local trades to be settled predictably without having to rely on the USD-based stable coins available in the market. Our team is also working on Urdu translation of unstoppable wallet to make it more accessible for the common man, as a replacement for locally popular payment apps like EasyPaisa and JazzCash.

c) Expose people to the Stacks blockchain by having them use a stable coin operated using Stacks smart contracts.

d) Give people a "savings account" feature in their "checking account", by periodically distributing the price appreciation of the assets backing the stable coin, without needing to directly invest in them. This will make the Rupee coin more attractive than the regular State currency.

e. Strengthen the stacks ecosystem and interoperability with complimentary projects e.g. we may incorporate Arkadiko token as a backing store for the Rupee token.

**Scope**
=========
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The Rupee Stable Coin (RSC) will be maintained by an US-based LLC, to prevent the complications associated with the uncertain regulatory regime in Pakistan. This will ensure freedom to operate and manage the RSC token online, without legal interference from the Government of Pakistan.

A set of smart-contracts will be created to allow visibility into the backing stores holding the physical assets against which the Rupee token will be issued, with a minimal of 100% value backed at any point in time. The backing stores will consist of hard physical assets, which is culturally important to assign value to the Rupee token in the eyes of the Pakistan public. Only crypto-representations of such assets will be employed e.g. XAUT, GLC, DGX, PMGT, as well as physical gold and silver. BTC and stable crypto assets, including STX itself can act as backing stores of value in future. Oracle services maybe needed to validate presence of the off-chain backing assets.

Additional smart contracts maybe needed for features like automated redemption from on-chain portion of the backing store.

**Budget and Milestones**
==========================
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $5,000

The grant will money will be used for stacks-based on-chain portion of the backing store of the stable coin, and for providing liquidity for people buying into and out of the stable coin.
The smart contracts and other administrative expenses will be covered by us, and grant money will not be used for that.

**Team**
==========

Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

The project is lead by Asif Shiraz, a senior software engineer with experience in fortune 100 companies. He is the founder of Dinar Wakala LLC, a Texas based seller of gold and silver coins minted as replicas of the medieval Muslim coinage: the dinar and the dirham. Mr. Shiraz is also the author of an Urdu book introducing Pakistani audience to Austrian school's monetary theory and its congruence with certain religious injunctions mandating sound money. Our core team includes members locally from Pakistan, to manage the physical backing stores and promote the tokens in the country. We also have a loosely associated global community of sound money enthusiasts from the US, Malaysia and Indonesia, who are very interested in partnering with a gold-backed asset of this kind.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

The primary risk comes from regulatory crackdown on a project that can potentially challenge the government currency. The mitigation plan is to maintain as little physical presence in Pakistan as possible, until a more certain and favorable compliance framework can emerge. Adoption from remotely operating a stable coin can be challenging, however, the country is hungry for sound money investments, as evident from exorbitantly high margin asset sales happening on Binance P2P, Paxful and Localbitcoins.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

We envision the Rupee Stable Coin to be a multi-chain project, and are also working on Ethereum and Solana based contracts. Our website is under construction at http://rupeestablecoin.co and git repo at https://github.com/rupeestablecoin

**Comment by tycho1212** [comment]
Interesting project! I have some questions which the grant committee might also have

1. I'd be curious to learn if there is validation for demand for a Pakistani Rupee Stablecoin (data, surveys of traders, etc)? I'm under the impression that most people in crypto in countries like Pakistan prefer to use USD-pegged stablecoins because of the volatility of local currencies

2. You mention this is a multichain project, what's the progress so far for building RSC on other chains?

PS: I'm just an enthusiast reading these proposals

**Comment by asifshiraz** [comment]
Thanks @tycho1212 for your questions.

1. Validation for demand is just observational, based on my own experience. Crypto industry is quite new, and a lot of educational effort is needed to make people understand how it works, and how they need such building-block components in the ecosystem. There is also general dissatisfaction with the rate of inflation, and people are expected to buy into anything that can counter that.

2. Well.. it is fairly new. I have Open Zeppelin based simple Ethereum contracts. Testing on Rinkeby.

**Comment by jennymith** [comment]
Hi @asifshiraz, thanks for submitting this proposal! We think this is an idea that could gain traction within the community one day, but as it currently stands, we are not comfortable approving this application given the high level of regulatory uncertainty surrounding it. In order to move forward with reviewing this application, we would need much more information on the legal, technical, and product aspects of this project. See the following questions:
- Beyond simply registering a US-based entity, have you done any other due diligence to identify the potential legal/regulatory risks of this project?
- What specific functions will be covered by the set of smart contracts you mention? 
- Are there plans to build an accompanying UI for users?

**Comment by asifshiraz** [comment]
Thanks Jenny. That makes perfect sense. There is definitely uncertainty around such a setup. I will keep you apprised of our progress. We can close the request.
