### ISSUE TITLE
integration into CFC Wallet with 8M+ users

### ISSUE THREAD

**Issue by oleksiivinogradov** [stacksgov/Stacks-Grants#19]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> What problems do you aim to solve? How does it serve the mission of a user owned internet?
Executive summary: https://docs.google.com/document/d/1_GP-22JmnXLEE7vVH18lYi_e8My99j9W8rTO8oeaXMw 

## Project Overview

> What solution are you providing? Who will it serve?
Executive summary: https://docs.google.com/document/d/1_GP-22JmnXLEE7vVH18lYi_e8My99j9W8rTO8oeaXMw 

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

Will do the integration with native tokens support and DeFi support

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

$5000, 100 hours

UI design - 20 hours
Prototype backend - 30 hours
Prototype iOS/Android - 30 hours
Tests and errors checking - 20 hours

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?

Executive summary: https://docs.google.com/document/d/1_GP-22JmnXLEE7vVH18lYi_e8My99j9W8rTO8oeaXMw 

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

Presentation: https://docs.google.com/presentation/d/1E4JDn1lTUpfq1pTTn2RFuYaIwmJ0fQ2IVKlNUA8iKzU 

## Community and Supporting Materials

> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

https://www.linkedin.com/in/oleksiivinogradov/

**Comment by friedger** [comment]
@oleksiivinogradov The grant is for projects of 5k$ not 50k$. Could you highlight the benefits for the community? Do you plan to share some of the revenue back to the foundation?

**Comment by oleksiivinogradov** [comment]
> @oleksiivinogradov The grant is for projects of 5k$ not 50k$. Could you highlight the benefits for the community? Do you plan to give some of the revenue back to the foundation?

I don't find limits in general. $5k is bellowing my costs for the integration of your blockchain. But I can do it, in case of some PR support. 
Regarding benefits for the community - blockchain cost nothing without real cases. CFC Wallet is a real case with millions of users. Revenue sharing is possible in case of using existed referral system inside bot and apps.

**Comment by friedger** [comment]
![Screenshot from 2020-09-29 10-44-42](https://user-images.githubusercontent.com/1449049/94534578-d8006880-0240-11eb-8ca3-3fccb3eeb9fc.png)

**Comment by oleksiivinogradov** [comment]
updated

**Comment by ryanarndtcm** [comment]
Thank you for your application. This proposal is not being approved as it does not meet the requirements of supporting the mission of a user-owned internet, nor any specific description of the benefits to the Stacks Ecosystem community
