### ISSUE TITLE
Bitsoko

### ISSUE THREAD

**Issue by allanjuma** [stacksgov/Stacks-Grants#196]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

Decentralized services for micro, small and medium enterprises. The merchant will own all the softwares  services that their business depends on to run successfully. 

**Project Overview**
What solution are you providing? Who will it serve?
Micro, small and medium sized merchants  will be able to create an online store with web-hosting, payments and delivery services, by running a node powered by the lightning network.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
A docker container that connects to an lnd-node and provisions an online store with payments and delivery services. 

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

We are seeking 35,000 USD to provision the merchant services app across 15 existing merchants in nairobi, Accra and lagos. 

Sample merchants
https://aurelias.kitchen
https://liqourlab.biz 

Total Grant Request: 

1: FUNDING: raise capital for 15 merchants (9 micro,  4 small, 2 medium), using smart contracts on stacks, by sending STX in exchange for merchant tokens.
2: TRACKING: tie merchants services to smart contract to enable all income and expenses to appear on respective contract
3: REWARDING: enable token holders to earn profits from respective merchants

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 
Development by bitsoko services. 
https://drive.google.com/file/d/1Qf9Wj53U74oqfvWDa9JO-jejzIXabAle/view?usp=drivesdk

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
This this is the second time we are fundraising  for merchants, we have had good success and plan to do better this time. 

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?
Previous event.
https://youtu.be/3nFBQr-HiyU

Git
https://git.bitsoko.org/bitsoko

Updates on dedicated #stacks channel here
https://discord.gg/U7FF3JY8

**Comment by jennymith** [comment]
Thanks for taking the time to put together this application @allanjuma!

**Decision:** We have decided to pass on this proposal as it is unclear how your grant would utilize Stacks technology or benefit the Stacks community. 

**Feedback:** Should you continue to pursue this project, we encourage you to do more technical research on how your services would be built on Stacks. If you are determined to build a long-term business and you're looking for funding, we would also recommend looking into the [Stacks Accelerator](https://stacks.ac/), an intensive 3-month program that would provide the kind of curriculum and mentorship you would need to get this venture off the ground.
