### ISSUE TITLE
Stacksboard - NFT powered digital real estate

### ISSUE THREAD

**Issue by danosaur98** [stacksgov/Stacks-Grants#199]
**Background**
> What problems do you aim to solve? How does it serve the mission of a user owned internet?

Digital real estate is an excellent way for advertisers to boost their brand and artists to display their work, among other use cases. A popular example of digital real estate can be found at [The Million Dollar Homepage](http://www.milliondollarhomepage.com/). However, modern digital real estate has much to be improved through the use of NFTs. The owner of a popular website can rent out some space on its website to paying advertisers who want to showcase their brand, or to artists who want to showcase their art. As a digital real estate owner, I would prefer a hands free way to keep my space full of paying customers. As an advertiser or artist, I pay the owner to display an image on the entire space for a set amount of time. I typically am unable to pay for just a section of the space, and I do not receive anything after my set amount of time is over. 

**Project Overview**
> What solution are you providing? Who will it serve?

Stacksboard is an NFT powered digital billboard where each slot will be minted as an NFT, and the owner of each NFT is given the right to publish an image on the billboard. The NFT owner may resell their slot NFT, and a royalty fee is given back to the billboard owner. Stacksboard consists of the Clarity smart contract layer, as well as a React front end component to display the billboard.

Slot NFT owners are anyone interested in advertising or showcasing their work on that billboard. This solution benefits them by letting them resell their slot whenever they wish, which allows them to regain some of (if not more than) the money they spent for that slot. In addition, they are able to display an image (and metadata) on part of the billboard, instead of needing to pay for the entire billboard.

Stacksboard owners can be any company or entity with digital space for billboards, such as a section on their webpage. This solution benefits them through the royalty they receive on each slot NFT resale in perpetuity, and they do not have to worry about manually reselling the slots.

Stacksboard will open up a powerful secondary market for digital real estate where the digital real estate owner or the NFT owners will determine the value of each NFT. For example, if the  digital billboard owner is a famous museum, artists would be interested in displaying their art there, or if the digital billboard owner is a popular website for a particular niche, advertisers of that niche would be interested in showcasing their brand there. Furthermore, if the owner of one slot was a famous artist, it would drive up the value of the surrounding slots since it shows that famous artist believes in the billboard. Every NFT resale provides royalty fees for the owner, and the resale can result in a positive return for the original buyer. Stacksboard provides a valuable way for the community members to interact with one another and to gain recognition through their artwork or brand!

In the future, Stacksboards could be brought to the physical world by displaying them on billboards in large cities such as New York City.

**Scope**
> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

1. Clarity Smart Contract - creates slot NFT that implements the sip-009 NFT standard, allows Stacksboard owner to specify royalty rate and NFT owners to specify image URL and other information that can be displayed on the billboard

2. Front End Component - reusable react component that interacts with the clarity smart contract to read all information from the slot NFTs to build the billboard, will allow any stacksboard owner to add to their website
	- Example layout (can be changed):  
![Stacksboard](https://user-images.githubusercontent.com/15619710/133561224-9bf43d4d-6263-4987-a608-e265591d0df0.png)

Each slot owner would be able to specify an image for their slot. Users can interact with the stacksboards -  when they hover on a slot, it will display a tooltip with metadata about the owner, such as their website, social media handles, or a description about the image they selected.

3. Front end demo - website allowing users to interact with the first Stacksboard. Visitors can hover over each slot of the stacksboard to see more information about the artwork and information about the owner. This may also provide a way for users to buy and sell slots directly on the web app, but if an NFT marketplace is opened and well supported by the community, this website can connect to that NFT marketplace instead. 

The first stacksboard is expected to benefit the stacks community as it is the first NFT powered billboard on the stacks blockchain where community members can advertise or display their artwork, but also allow users to resell their slot NFTs whenever they want. We will measure success based on how popular the first stacksboard will be, and based on how easy it is for other entities to start displaying their own stacksboard in their webapp. 

**Budget and Milestones**
> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone. 

Total Grant Request: 

M1: Clarity Smart Contract Development 
- 40 - 60 hours (research, development, testing) - $2000
- Deliverable - smart contract deployed on testnet that allows:
      - Stacksboard owners to build their own stacksboards and specify royalty, 
      - Slot NFT owners to specify image and metadata

M2: React Front End Component  
- 40 - 60 hours (design, implementation, connecting with clarity smart contract) - $2000
- Deliverable - Open source react front end component that displays the stacksboard along with metadata displayed in a tooltip on hover. Smart contract will also be on mainnet.

M3: Reference web app for the first Stacksboard 
- 40 - 80 hours ~ $3000, depending on whether a popular stacks NFT marketplace has been opened by then.
Deliverable - reference website to showcase this technology and to be the first website that the community can interact with - mint / buy / sell NFTs and display their art.

Total - ~$7000

**Team**
> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

I'm a full stack developer with 4+ years of industry experience in typescript/react, python, docker. In addition, I have experience with clarity and have contributed 5 smart contracts in prior clarity hackathons. I will be building both the front end website/components and the clarity smart contracts. 

**Risks**
> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

One risk is a slot NFT owner is allowed to specify the image URL, so they could specify a NSFW image that would show on the stacksboard without the owner's consent. A work around to this is for billboard owners to take daily or weekly snapshots of the stacksboard (could be minted as an NFT!), and update the image displayed after the owner approves what is being displayed on the stacksboard before it goes live on their website or physical screen. 

**Community and Supporting Materials**
> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

I created 5 Clarity contracts for prior Clarity hackathons, and I have experience working with Clarinet. I've chatted about the idea with Jenny Mith and Jim Crane and they both provided exceptional feedback and seemed enthusiastic about stacksboard. I've taken inspiration from some of the NFT teams in the stacks accelerator and would be interested in connecting with them as well. I hope to share this project with the community with the first Stacksboard, which will provide the community a valuable opportunity to interact with one another, display their artwork or gain visibility for their brand, and to mint and resell slot NFTs.

**Comment by jennymith** [comment]
Hi @danosaur98, thanks for submitting such an interesting proposal. It's clear that you've put a lot of thought into how you could innovate on a classic web 2.0 model using web 3.0 tools.

**Decision:** **Pass.** While this proposal is certainly interesting from a business model perspective, after much discussion, we felt that it isn't in the spirit of advancing a user-owned internet. Despite the fact that it has the potential to open up a secondary market for "renters" to sell their slots, thus providing a more lucrative/profitable pathway for users, this model is still vulnerable to digital real estate monopolies/centralization/market manipulation. Because there are no term limits or regulations imposed on billboard owners, there's nothing stopping them from unfairly hiking up billboard rent prices or booting renters when they simply don't like their content. Based on those risks alone, it seems like this project is simply duplicating web 2.0 dynamics around advertising, rather than innovating on them. 

**Feedback:** Although we are passing on this application, we recognize that there is a very interesting idea here and encourage you to either move forward with building/testing this proposal on your own, or resubmitting this application after some thought and revision. Here are some questions/suggestions to consider for future work:

- Map out the economics of this model in detail. Figure out how you can open up that secondary market for renters without giving so much control to owners.
- How can you make this billboard market easier for users to enter/exit? I.e. How can you avoid a situation where the price to obtain an NFT billboard is so high that new users are never able to participate?
- Distribution channels are often more important than tech itself. How can you leverage the model of Stacksboard combined with the technology of NFTs to help users reach more distribution channels with their content?
- Would this product be able to bypass adblockers?
- What kinds of features could you implement to better regulate the content of these billboards?

**Comment by danosaur98** [comment]
Hey @jennymith ,

Thank you so much to the committee for the response to my proposal - it offered tons of helpful feedback and brought up problems I will consider going forward. There were a few points that I was hoping to understand better and a few points I was hoping to clarify: 

To start off with, I wanted to clarify the difference between a billboard owner and a slot NFT owner. 

Billboard owners set up the smart contract and web component on their website. They receive mint and royalty fees. Once someone mints an NFT from the billboard owner, the billboard owner can not change the information that a slot NFT owner puts on-chain. The web component reads information such as image URI directly from on-chain.

Slot NFT owners mint or resell slot NFTs. If you are the owner of a slot NFT, you are given permission to update information such as an image URI and your website URI on-chain. You decide what price you would sell at. The billboard owner cannot change your NFT on-chain information, nor force you to sell at a certain price, nor force you to transfer your NFT to another owner.

>  this model is still vulnerable to digital real estate monopolies/centralization/market manipulation

From my perspective, this is a problem inherent with all NFT marketplaces, not just with stacksboard. I agree a digital real estate monopoly/centralization could happen if one or some organizations bought a majority of the slots, but this problem and market manipulation can happen with any NFT. I think it is outside of this project's scope to solve a universal NFT problem.

> Because there are no term limits or checks imposed on billboard owners, there's nothing stopping them from unfairly hiking up billboard rent prices 

I disagree here - the billboard owner sets the mint price. Once a slot owner mints the NFT, the slot owner sets the resale price. You could argue that the slot owner unfairly hikes up the billboard "rent" (resale) price, but you can also argue the slot owner believes the price is the true price for a slot on this billboard. As an analogy, I can think my artwork should all be worth 100k, and others might disagree with me and say my artwork is worth 1k. It's my decision to sell for 100k, and their decision to buy for 1k. Of course, I might not find people who will buy my artwork for 100k, and those buyers might not find people who will sell my artwork for 1k, but no one, including the board owner, can force me to sell for a lower price. If I think this billboard is extremely valuable and gives me lots of exposure, why would I want to resell my slot for a price I don't agree with? 

> or booting renters when they simply don't like their content.

I would love to discuss this point more as this is a grey area. 

I would argue this is more censorship resistant than the current web 2.0 advertising model. Technically, if I'm the billboard owner, I can't actually "boot renters". I do not own the slot NFT, so I do not have permission to change the image URI stored on-chain, nor can I forcibly send the slot NFT to someone else. 

If I don't like what a slot owner has used for their image, I could censor it by removing it from displaying on my billboard. However, I would want to avoid this because I am no longer displaying the true form of the board, and people would no longer want to view a censored board, so it would probably cause the resale value of the slot NFTs to plummet. 

The only advantage a billboard owner has is receiving the original mint fee and royalty fees, and owning the location (website) for the first display of the billboard. Otherwise, anyone can add the react component to their website, connect it to the right smart contract, and view the correct and uncensored state of a billboard since all of that information is stored publicly and on-chain.

> Based on those risks alone, it seems like this project is simply duplicating web 2.0 dynamics around advertising, rather than innovating on them.

I would like to argue that this project innovates by solving some of the problems with web 2.0 advertising dynamics, but does not solve all of the problems, most of which are inherent of all NFTs, which are outside of the scope of this project. 

> Map out the economics of this model in detail. Figure out how you can open up that secondary market for renters without giving so much control to owners.

I think we have some miscommunication here - if by "owners" you mean billboard owners, I would argue they don't have much power. They can't change the slot NFT information stored on-chain. They are disincentivized from censoring images on their billboard because it would hurt the PR of their billboard. 

If by "owners" you mean slot NFT owners, they're already in the secondary market, and sure they have a lot of "control", but that's one of the main features of the stacksboard. Slot owners have more control over their slots than in traditional web 2.0 advertising - the information they store on chain can't be censored, and they can resell their slot. 

> How can you make this billboard market easier for users to enter/exit? I.e. How can you avoid a situation where the price to obtain an NFT billboard is so high that new users are never able to participate?

I think we may also have some miscommunication here too. If by "to obtain an NFT billboard" you mean to be a billboard owner, anyone can do it for free basically. They would set up the smart contract with the mint fees, and then anyone can mint a slot NFT on their billboard, and the billboard owner can display the billboard on their website.

If you mean "the price to obtain an NFT billboard" as in the price to obtain a slot NFT to display your artwork on part of the billboard, I would argue this is one of the features of the stacksboard, as I've explained above. Slot owners should be able to sell their slot for whatever price they believe is right. You could argue that this is a problem with web 2.0 advertising, but if the NFT billboard were to be displayed in NYC Times Square, or if it were to be displayed year round at popular sports events like the Superbowl, would it make sense for a slot on such a billboard to be cheap enough for new users? The price is directly tied to the value of displaying your artwork on the billboard. 

> Distribution channels are often more important than tech itself. How can you leverage the model of Stacksboard combined with the technology of NFTs to help users reach more distribution channels with their content?

Great question - I haven't put too much thought into this yet, but I will consider this moving forward. 

> Would this product be able to bypass adblockers?

I believe so since it's a react component reading information from a smart contract, but I am not personally familiar with adblocking technology, so I will also consider this moving forward.

> What kinds of features could you implement to better regulate the content of these billboards?

Another great question to consider moving forward. One solution for this problem and could potentially address the above problems - I was thinking of was turning the board into a DAO, where slot NFT owners are granted voting rights. If enough members agree, it could overwrite individual slot NFT information, or send transfer slot NFTs. I haven't worked out the entire implementation, but just spitballing ideas around.

Thanks again for the feedback, and I look forward to hearing the committee's thoughts on the points I made above!

**Comment by RaffiSapire** [comment]
Thank you @danosaur98 for taking the time to respond to our feedback, the committee reviewed it thoroughly, and unfortunately we were not able to convince ourselves otherwise based on our initial reasons for passing sent by Jenny.
