### ISSUE TITLE
COVID-19 Strategy

### ISSUE THREAD

**Issue by Dallas23** [stacksgov/Stacks-Grants#200]
**Background**
What problems do you aim to solve?:Hoping to solve the problem of a infectious desease that is spreading rapidly.
How does it serve the mission of a user owned internet?:By serving the purpose of online COVID-19 information.

**Project Overview**
What solution are you providing?:Providing needed COVID-19 information and medicine.
Who will it serve?:All individuals.

**Scope**
What are the components or technical specs of the project?:Creative medicine machinery and medicine testing/clinical studies.
What will the final deliverable look like?:The outcome of the product and information.
How will you measure success?:Bringing smiles to everyone's face.

**Budget and Milestones**
What grant amount are you seeking?:$900,000,000.00
How long will the project take in hours?:18
If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: 

M1: Scope of work, deliverables, and grant amount of total.:
1.Clinical Study:$800,000,000.00
2.Product Evaluation:$100,000,000.00
And that's plus putting all the deliverables to work.

M2: Etc.

**Team**
Who is building this?:Myself
What relevant experience do you bring to this project?:None.
Are there skills sets you are missing that you are seeking from the community?:No.
Please share links to previous work. 

**Risks**
What dependencies or obstacles do you anticipate?:Taking the challenges of working with the government in getting this successfully done.
What contingency plans do you have in place?: None.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application?:No.
What community feedback or input have you received?:None.
How do you plan to share your plan to the community over time and as the final deliverable?:By getting it known under the federal government.

**Comment by jennymith** [comment]
Hi @Dallas23, thanks for your submission. 

**Decision:** Pass. This project doesn't seem to be at all related to Stacks. The grant amount you're seeking is also extremely over budget. 

**Feedback:** If you would like more guidance on how to put together an application that is more suitable to this program, please feel free to join our [office hours on Tuesdays and Thursdays.](https://community.stacks.org/events#term=office%20hours&start_date=2021-09-23&view=stream&range=events&events=20) Thanks!
