### ISSUE TITLE
Stacks NFT Calendar 

### ISSUE THREAD

**Issue by STXNFTCalendar** [stacksgov/Stacks-Grants#205]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

- Our goal is to increase community awareness (within Stacks and the general crypto community) of Stacks NFT drops and projects by providing the community with a responsive, crowd-sourced NFT calendar.
- It will serve the mission of a user owned internet by increasing adoption of Stacks, specifically through NFTs. It will educate people on the power of Stacks x Bitcoin and how Stacks adds a lot of functionality to the Bitcoin network.

**Project Overview**
What solution are you providing? Who will it serve?

- Our solution is an NFT calendar (https://STXNFTcalendar.com). It will serve both the project NFT drop founders (to expand their reach and sales) and the consumers (for the discovery) of the NFT art.
- We are asking for this grant to improve our website, increase our marketing efforts, and to allow us to work more "full-time" on this project.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

- We will be operating a Webflow frontend/Airtable/Node-JS backend site. It allows the community to submit new NFT releases (date/time, price in STX, quantity, description, etc). This allows the community to be more aware of releases and increase participation.
- We will measure success by the number of unique visitors and page views the site gets, along with the number of projects submitted. Finally, the level of overall adoption of Stacks NFTs in the broader crypto market.
- We will also provide completely transparent weekly updates of the website stats, newsletter subscribers, and all other relevant progress. There will be a page on the website dedicated to updates which will be posted to Twitter and shared in our weekly newsletter.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request:

- We are requesting a total grant of **$20,000 USD.**  We will continue to spend a lot of time marketing the site via Twitter - @STXNFTCalendar, through a weekly STX NFT newsletter, and through other channels, as well. We will also continue to improve the quality of our site during the next couple of months.
- **Budget breakdown:**
    - **$15,000** = $50 an hour x ~15 hours per week x 2 (both of us) x 10 weeks.
    - The remaining **$5,000** will be used for marketing efforts and operational costs.
    - We still expect to self fund parts of the project, at least for the near future.
- This grant will allow us to take the whole project to the next level, and to make it completely self-sustaining, through website/newsletter sponsorships.
- We will begin to do periodic giveaways to gain exposure, grow more rapidly, and give back to the community.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work.

- We are a two person team of brothers - Landon and Carson.
- Carson - Carson has a large amount of experience in internet marketing and social media growth. He built a TikTok growth agency website from 0 to 14 million organic Google impressions(**1 million visitors**) in one year, making it the #1 TikTok growth agency in the world, before it was acquired.  He is a JavaScript developer and focuses mainly on automation and backend.
- Landon - Landon is experienced in building community. He has built up a local digital media brand to **~40k social followers and ~5k email subscribers (50% open rate)** for a small city (< 400k population). [https://WichitaLifeICT.com](https://WichitaLifeICT.com) [https://www.instagram.com/wichitalifeict/](https://www.instagram.com/wichitalifeict/)

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

- We do not see many obstacles in the way of this project.
- One potential obstacle would be a downturn in the overall NFT market. If this were to happen, we would continue to cultivate support for NFTs built on Stacks and build up the community during the "Bear market".

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

- So far, we have been running the site [STXNFTCalendar.com](http://STXNFTCalendar.com) for approximately 4 days. We already have visitors from over 34 countries and an email list of 150+ people. The visitors, views, and submissions are growing faster each day. The community seems to love it and is very supportive.
- We will continue to improve the site and the experience for our users. We will provide the community with updates on the website traffic, email subscribers, etc.

**Comment by STXNFTCalendar** [comment]
Thanks for the response @jennymith ! **"Education, Evangelism, and Collaboration. Are you experienced in communication, marketing, community or creative? _Create resources that support or grow the community._"**

We would be applying specifically for this category, which we think it fits quite well in.

Concerning relationships with NFT creators in the STX ecosystem, we are in active conversations with **20+ on a daily basis**. We think the stats for the site/Twitter acct/newsletter show dramatic community support for the project. What else do we need to show to qualify for the grant?

**Comment by STXNFTCalendar** [comment]
Hey @jennymith ! 

Sorry for the late response. We have been super busy with the site/Twitter, all the drops, + regular jobs. We will have an updated/improved proposal ready for next week's review session.

Thank you so much for all of the constructive feedback. We really appreciate it and look forward to hearing back after we re-submit.

**Comment by STXNFTCalendar** [comment]
Also a little update on everything, since we've been "#BuildInPublic" on Twitter and in our newsletter.

(10/26/2021 - 11/1/2021)

Twitter Followers = 1009 (+292!)
Email Subscribers = 305 (+95!)
Website Unique Visitors = 547 (-73) from 50 (+4!) countries
Website Page views = 4900 (+300!)

We are thrilled with the growth and excited to see where we can take this with your support! 🚀

**Comment by jennymith** [comment]
Hey @STXNFTCalendar, do you still plan to resubmit this grant?

**Comment by will-at-stacks** [comment]
@STXNFTCalendar just an FYI - since your application has been stale for several months we are closing it.  if you are still interested in a grant, you will need to submit a new application
