### ISSUE TITLE
Pay transaction fees and gas fees using bitcoin's lightning network

### ISSUE THREAD

**Issue by supertestnet** [stacksgov/Stacks-Grants#217]
**Background**
To use the stacks blockchain users must obtain stx tokens to pay fees. Stacks miners are paid for their work by means of these stx fees, which are integrated in each stx transaction. Integral fees are simple to implement and make things easy for miners but they introduce friction for users of a blockchain. One item of friction is that, before a user can add transactions to a given blockchain, they have to obtain enough of its tokens to pay for gas fees. The more blockchains there are with integral fees, the more tokens users must store in their wallets in order to use those blockchains. Also, integral fees involve broadcasting transactions to a mempool, which is bad for privacy, and they introduce complications when fees suddenly increase after a transaction has been broadcast but before it has been mined. To alleviate some of these problems, some miners, such as pool.in, allow users to pay low or no integral transaction fees and instead they may pay transaction fees out of band using a currency of their choice.[1] Some bitcoin developers even support dropping the mempool entirely and doing all transaction fees out of band.[2]

**Project Overview**
What solution are you providing? Who will it serve?

One possible alternative to the mempool is for miners to run a service with an api that takes in raw transactions from users as input, computes a fee, and returns a request for fee payment using some sort of invoicing system such as the one in use by bitcoin's lightning network. If a wallet's users wish to use this system instead of integral fees, their wallets could construct a raw transaction and include it in a query to various miners to get their fee rates, then select the cheapest miner or the fastest (i.e. largest) miner, depending on user preference. Such a system would allow users of a blockchain such as stacks to add transactions to the stacks blockchain without purchasing stacks tokens, reducing friction and enhancing privacy. In combination with a pegged bitcoin token such as xBTC,[3] this could allow stacks to be used in a similar manner to other sidechains such as liquid and rootstock, where a bitcoin pegged token is used in most contracts and payments, with the advantage that -- in stacks -- transaction fees and gas fees could be paid directly in bitcoin over the lightning network.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The deliverable would be a daemon which stacks miners can run in combination with a lightning node such as lnd. The daemon would create a tor service with an api that listens for queries from user wallets. Future stacks wallets could use an array of such tor services to query stacks miners for fee rates and include any of their unconfirmed raw transactions in the query. The software would compute the current fee rate in stx for each of the user's raw transactions, as well as any gas fees, sum up the total cost to add those transactions to the blockchain, convert the result to satoshis, and create a lightning invoice for that amount. The daemon would then return this lightning invoice to the user's wallet. If the user attempts to pay the invoice, the miner would temporarily hold the invoice, and, while holding the invoice, insert all of the now paid for transactions into his or her block template. This would ensure that the next block mined by that miner will include those transactions. Once that block is created, broadcasted, and anchored into bitcoin's blockchain, the miner would settle the lightning payment. If at any stage before the transaction is anchored into bitcoin's blockchain the transaction fails, such as because the inputs to the user's transaction got spent in some other transaction, the lightning payment would not be settled but rather canceled by the miner so that the user gets their money back, and the now invalid raw transaction would be ejected from the block template.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: I seek a $20,000 grant to complete this project to be paid in bitcoin.

M1: Create a tor service with an api that listens for raw stx transactions and returns a lightning "hodl invoice" from lnd - 64 hours

M2: Modify the daemon so that it validates raw stx transactions before accepting them, computes total transaction fees and gas fees needed to add those transactions to the blockchain, converts the resulting fee value to satoshis, and uses the resulting value as the input for the lightning invoice - 64 hours

M3: Create a function within the daemon which runs when a query is made to the daemon's api and which, when triggered, adds a user's raw transactions to a database indexed by the payment hash associated with the hodl invoice created in step 1 - 64 hours

M4: Create a function within the daemon which runs when lnd detects that someone attempted to pay a hodl invoice which is now waiting for settlement by the miner. This function, when triggered, queries the database mentioned in step 3 for the payment hash of the invoice that the user attempted to pay, thus getting the user's raw transactions - 64 hours

M5: Create a function within the daemon which runs on a loop when the previous function runs. This function should check whether the user's transactions remain valid, i.e. their inputs have not been spent in some other transaction. If that check returns true, the function should ensure that the transactions are in the miner's current block template, otherwise it should eject the transactions from the block template and cancel the user's invoice. The loop should stop running only after the user's transactions are mined into the stx blockchain and anchored into bitcoin's blockchain - 64 hours

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

I, Super Testnet, am building this. I have experience as a bitcoin and lightning engineer since 2018. Most of my work can be viewed at my website, highlevelbitcoin.com, where I showcase apps that I have written for triggering various actions on a server in response to a lightning payment. Some of my relevant work include BTC Paywall, which allows content creators to lock their content behind a paywall such that it is only revealed to the user if they make a lightning payment, and Article Votes, which lets users pay sats on the lightning network to increment a ranking number for a set of articles. (It is used by the podcast bitcoinaudible.com to let users upvote what topic they want to hear next on the podcast.) Less relevantly, I am also responsible for the php implementation of lnurl auth, which is a keypair based authentication system popular among lightning network users because it allows them to authenticate with services and log into websites using the bitcoin wallet to sign a message proving what user they are.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

One of the things I have not done previously is work with block templates to conditionally inject raw transactions into a block template or eject them from it in response to external functions. If this does not work how I expect it does, my contingency plan is to look up how it works in developer documentation and ask other developers for assistance. Another obstacle is that some wallet makers may not like the idea that they have to add tor support to their wallets in order to work with this system. A contingency plan is to modify the software so that miners can run the daemon on clearnet if that becomes an issue.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

Regarding previous projects, see the comments under **Team**. Community feedback and input that I have received so far has been great. Upon announcing this idea, I received positive comments from Brittany Laughlin,[4] Mitchell.btc,[5] Muneeb,[6] Lyle Pratt,[7] Bitcoin Frankie,[8] and several other stacks supporters.[9] The community seems to regard this as a good way to increase the appeal and accessibility of the stacks blockchain and I anticipate more support as I announce completion of the various milestones.

[1] https://pushtx.com/
[2] https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-October/019572.html
[3] https://blog.stacks.co/xbtc
[4] https://twitter.com/br_ttany/status/1460734975251202060
[5] https://twitter.com/mcuevasm/status/1460736078202167299
[6] https://twitter.com/muneeb/status/1460734265797263360
[7] https://twitter.com/lylepratt/status/1460712148989100036
[8] https://twitter.com/bitcoinfrankiee/status/1460742106226569221
[9] https://twitter.com/GeistLight/status/1460706399269396480

**Comment by lylepratt** [comment]
Very cool stuff @supertestnet! When I was trying out Stacks I personally found it painful to have to go to an exchange to get STX before I could do anything. This would make onboarding new users to Stacks use-cases *much* easier since USD->Lightning wallets like Strike could be used to pay for Stacks transactions.

One thing to consider would be bumping the grant up to $30k to include support for lightning fee payments in the Hiro Stacks Wallet.

**Comment by matthiasdebernardini** [comment]
I would be more than happy to contribute to this, either with beta testing it, shilling it, or writing docs for it.

**Comment by will-at-stacks** [comment]
Hi @supertestnet, thanks for your proposal. We think this is an interesting idea that has a lot of potential to improve the experience of transactions on Stacks. We would be open to funding a solution in this area but have several suggestions for you to consider before we do. We recommend taking a deeper look at sponsored transactions, a unique feature of Stacks, as well as different models for “fiat onramps,” before committing to the approach that you’ve outlined in this original proposal. 

We realize that this will likely require further discussion so please feel free to schedule some time for us to work through this feedback next week.  If you'd like, you can reach me at will@stacks.org and we can set up a call to discuss.

**Comment by tycho1212** [comment]
I think this would be incredibly valuable for Bitcoin-Stacks cross-chain applications. I definitely support this

**Comment by FriendsFerdinand** [comment]
I like this, I think this would help to onboard new users.

**Comment by will-at-stacks** [comment]
@supertestnet just touching base to see how things are coming along with the revised proposal.  We look forward to reviewing it when you are ready.  Thanks, Will

**Comment by supertestnet** [comment]
@will-at-stacks If I remember correctly the primary revision you requested was to add a milestone to make this system trustless. After consideration I do not think it is possible to make this system trustless, therefore I choose not to add such a milestone. I therefore forfeit the grant request.

**Comment by matthiasdebernardini** [comment]
@supertestnet what about using a peerswap-like construction to help minimize trust in the trade and a DLC compatible oracle for the price (if they give you a bad price then you have proof that they lied and can warn other users about it)

https://blockstream.com/assets/downloads/2021-11-16-PeerSwap_Announcement.pdf

sounds complicated but it could ameliorate the settlement issues and the price issues

**Comment by supertestnet** [comment]
> sounds complicated but it could ameliorate the settlement issues and the price issues

If that is possible it is more complicated than I know how to do or have the inclination to do. I think it would be great to pay a miner to add your transaction to a block. That seems simple, easy to implement, and useful. Creating a submarine swap from btc to stx and then simultaneously using that stx in a transaction in order to market the product as "trustless" (because now a miner can't easily run off with your 15 sats) seems like dumb engineering to me.
