### ISSUE TITLE
Live Shows on MiamiCoin, NYC Coin, and STX NFT Marketplaces

### ISSUE THREAD

**Issue by kurtgrela** [stacksgov/Stacks-Grants#218]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

I'd like to create video content for projects that are building on Stacks.  There is not a lot of YouTube content on MiamiCoin, NYC Coin, and STX NFT marketplaces.  I'd like to share how I use them by providing weekly updates on market action and dynamics.  I support the CityCoins mission where mayors should act like CEOs to recruit the best ideas and talent.  Taxing citizens is an idea from the old world.  As for NFTs, they are quite fascinating by allowing artists to generate a recurring revenue stream rather than a one-time sale.

**Project Overview**
What solution are you providing? Who will it serve?

Weekly live show on MiamiCoin (Mondays at 8pm EST)
Weekly live show on NYC Coin (Tuesdays at 8pm EST)
Weekly live show on NFT marketplaces (Wednesdays at 8pm EST)

Event details will be posted on Twitter and YouTube.  Active market participants and interested people would join the live shows or catch the reruns.  Answers questions on the live show.  The show link would be included in my nightly [Top 10 Tweets at 10pm](https://tweets.101blockchainst.com) to generate more views after the live show is over. 

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

3 weekly live videos on a specific subject
7 hours prep time per week (Twitter, discord, articles, marketplace dynamics)

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

10 hours a week, including show time.  Initial run period is 10 weeks.  (No shows Mon, Dec 13 to Thur, Dec 30 due to travel.)

I have funded access to Canva for show thumbnails, Ecamm for live streaming, Restream to Facebook, Twitter, YouTube, greenscreen, lights, stand-up desk, access to gigabit internet, and M1 Macbook Pro.

Total Grant Request: $10,000

M1: Scope of work, deliverables, and grant amount of total.

M2: Etc.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Kurt - I participate in MiamiCoin, NYC Coin, and the NFT marketplaces.  I keep up to date with Twitter and the Discord communities.  I have a video streaming room and setup where these videos will be produced.

Twitter:  [https://twitter.com/kurtgrela](https://twitter.com/kurtgrela)
Twitter biz:  [https://twitter.com/101BlockchainSt](https://twitter.com/101BlockchainSt)
YouTube: [https://youtu.be/EbMaEanx84c](https://youtu.be/EbMaEanx84c)
Blog post:  Top 10 Tips for NYC Coin [https://tweets.101blockchainst.com/p/top-10-tips-for-nyc-coin](https://tweets.101blockchainst.com/p/top-10-tips-for-nyc-coin)

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

I am dependent on internet.  If there is a winter storm where there is an outage, I can reschedule for the next day or another day in the same week.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

After I wrote the Top 10 Tips for NYC Coin, the CityCoin Discord admins pinned my blog post.  It's been pinned for 10 days!  I show more than 450 people have visited that blog post.  My tweet announcing the article has ~4,500 impressions and ~400 engagements!  The corresponding YouTube video has 160 views, which is a good start.  All of this demonstrates people are interested in the content.

**Comment by will-at-stacks** [comment]
Hi Kurt, thanks for your proposal! We are definitely open to funding this grant and are excited about supporting more content around Stacks projects and creators. Before we commit to the full 10-week run though, we’d like to work with you on ensuring that your content is reaching as many folks as possible. Perhaps we could start with just 2–3 episodes, spend the first milestone gathering suggestions/feedback from the community, and set a goal to reach X number of community members by the end of this short run. Assuming you reach that goal, we can renew your grant for a more regular schedule of content.

Let me know what you think—happy to discuss more on a call next week. Please reach out to will@stacks.org to set up a time.

**Comment by kurtgrela** [comment]
Excellent!  Sure.  I welcome the coordination, suggestions/feedback, and outreach metrics.  I'll send you an email.

**Comment by kurtgrela** [comment]
Based on our discussion on 12/1, I will close this grant request and focus on a few other topics for content creation in the near term.  I'll submit another grant request this weekend.  Then we can revisit this grant request.
