### ISSUE TITLE
Productionize Meeting Bot for use with Advocates DAO SourceCred instance

### ISSUE THREAD

**Issue by blueridger** [stacksgov/Stacks-Grants#226]
Meeting bot Productionization

**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

As the Advocates DAO and the Governance Lab grow and begin engaging more members of the ecosystem, capturing the value of real-time collaboration in meetings in our incentive mechanisms will become more and more important.
There is a prototype Discord bot that tracks meeting participation that is being used with high satisfaction in other communities that use SourceCred; however, it is not productionized, with a crash rate of about 20%, and the admin features leave much to be desired.

**Project Overview**
What solution are you providing? Who will it serve?

We want to productionize the existing Meeting Attendance Bot prototype, increasing its reliability and improving its UX and feature set. This will benefit members of the Advocates Program and the people they engage by creating richer automated data for use in the SourceCred incentive mechanism.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

This project includes:
Refactoring the bot to use event-based architecture with light-weight semi-persistent state management
Refactoring the code to be more maintainable
Improving the documentation for purpose, usage, and deployment
Adding Google calendar integration
Add a toggleable feature to send reminders/suggestions to use the bot when meetings seem to be happening

Success will look like consistent use of the bot where applicable and a virtually 0% crash rate

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request:
9000 STX
90 Dev/UX hours

M1: Refactoring the bot to use event-based architecture with light-weight semi-persistent state management
20 dev hours
2,000 STX

M2: Refactoring the code to be more maintainable
10 dev hours
1,000 STX

M3: Improving the documentation for purpose, usage, and deployment
10 dev hours
1,000 STX

M4: Adding Google calendar integration
Components: Cron job that checks for upcoming events using the Google API, scheduled jobs to track meeting attendance when meetings start, configuration options
30 dev hours
3,000 STX

M5: Add a toggleable feature to send reminders/suggestions to use the bot when meetings seem to be happening
20 dev hours
2,000 STX

**Team**
The SourceCred Product Team, with Thena (blueridger) as lead. We are the subject matter experts on SourceCred-related product development and are responsible for virtually all 1st-party development right now.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
The dependency already exists in this repo and we do not expect any obstacles https://github.com/blueridger/MeetingAttendanceDiscordBot

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

As soon as this is complete it can be implemented at Stacks. Currently, Advocates DAO does not have their own calendar but they will and the Stacks server in general does. This tool will be essential to publicise and value public, realtime engagement and we want to make it better so it can serve the Stacks Ecosystem as it continues to decentralize. This tool can also be used for manual rewarding of outstanding participation and lead to NFT badges and other neat, creative ways to reward past contributions of real time participation to the Stacks events.

**Comment by jennymith** [comment]
Hey @blueridger, please [see this comment for reference](https://github.com/stacksgov/Stacks-Grants/issues/227#issuecomment-987692950).
