### ISSUE TITLE
Ocelo.io

### ISSUE THREAD

**Issue by diopitis** [stacksgov/Stacks-Grants#228]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

One of the biggest issues in web3 is finding individuals to help with developing new technologies. Ocelo is trying to bridge the gap between those with ideas and those able to build.  Ocelo makes central parties redundant by utilizing clarity smart contracts for escrow payments between dreamers and builders. 

**Project Overview**
What solution are you providing? Who will it serve?

We are providing a decentralized platform for posting jobs or finding individuals such as developers, designers, artists, and more. The industry standard for these centralized platforms is taking a 2.5% payment processing fee and an additional 10-20% fee from those completing the job.  When disputes arise on these platforms they are also handled in a centralized manner. Ocelo proposes a better way in which smart contracts act as mediaries and a community solution where a community jury will resolve disputes if they arise.  

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The final deliverable will be a platform in which users can post jobs, view workers profiles, portfolios, message,  invite them to jobs, and leave reviews. We will have a smart contract which handles the escrow between users as well as settle decisions from the jury on disputes. For our MVP and to garner community engagement we will be building a discord bot for users to act as a jury in a discord channel when disputes arise and receive payment in STX

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: 20k Stacks

M1: Clarity Development 3 weeks 
Clarity Smart Contract for holding payments and dispute handling
Unit Testing of the contract and deploying a testnet for early testing

M2: UI/UX Design and Prototype 3 weeks
We will be working with a design agency and having this milestone occur at the same time Milestone 1 is being worked on. 

M3: Backend 3 weeks
Development of our application backend and discord bot to support the full features of our MVP. 

M4: UI 3 weeks
Developing a fully function web app to handle contract calls, job postings, user profiles, messaging, etc.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

The Ocelo team is comprised of Dioptis and Invidia. We are both developers who have been very active in the Stacks ecosystem. Some of our previous work include the Miami Coin UI  [https://minemiamicoin.com/] as well as MIamiPool - a completely decentralized smart contract for mining MiamiCoin [https://mine.miami/].

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

One of the biggest risks we face is lack of community adoption. We have made it a priority to start partnering with other projects, as of now we have both AlexGo and Moonray as partners to use our platform for hiring talent. We are continuing to engage with other projects in the Stacks ecosystem. 

Our technical risk involves the jury system of our final product. We are still working on if it can be completely onchain or if it would cause too many transactions. 

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

We both have extensive experience using Web2 centralized platforms for hiring freelancers. This has helped us identify many key aspects of the industry that can be improved. 

Our Github profiles can be found here.
https://github.com/diopitis
https://github.com/syinvidia

With those that we have shared Ocelo with in the community we have got a similar response being that this is something needed to continue the amazing growth and development occurring on Stacks.  Our jury system will be a way for those in the community to earn STX for helping manage disputes and be introduced to our platform.

**Comment by SyInvidia** [comment]
We've now also partnered with Arkadiko, who have offered early community testing and adding USDA to our platform in the future!

**Comment by will-at-stacks** [comment]
Hi @diopitis, just leaving a note here that we'll revisit this proposal once we've considered whether a grant or residency makes more sense for this project (call scheduled for next Wednesday).  Very excited for this proposal and looking forward to our chat!

**Comment by philipdesmedt** [comment]
Confirming that Arkadiko core contributors would love to try this and see USDA integrated!
