### ISSUE TITLE
Video Content Creation for STX Projects

### ISSUE THREAD

**Issue by kurtgrela** [stacksgov/Stacks-Grants#230]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

Looking to create video content on STX and its projects.  Not a lot of STX video content on Twitter or YouTube.  Looking to change this and onboard everyday folks to the Stacks ecosystem.

**Project Overview**
What solution are you providing? Who will it serve?

Video production and narration for current and upcoming events and topics.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

MP4 video files.  Some videos may be edited.  Others may be completed raw.  Stacks to add its branding, intro and outro.  Some content will be for evergreen purposes.  Other content will focus on the near term or current events.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request:  $3,000

M1: Scope of work, deliverables, and grant amount of total.

M1:  Video content on NFT marketplaces - current and upcoming projects - In progress
M2:  Okcoin may list CityCoin NYC.  If so, I'll create a video covering this topic
M3:  MiamiCoin rewards and market activity (Dec 8-9)
M4:  HeyLayer launch (Dec 10)
M5:  Video on CrashPunks launch (Dec 12)
M6:  NYC Cycle 1 rewards and market activity (Dec 12/13)
M7:  Stacktistic launch (TBD) https://twitter.com/STACKTISTIC_btc 
M8:  Stacks on Chain Dashboards - as new features are added, create videos https://www.stacksonchain.com
M9:  TBD...

Success:   Increase YouTube views, more frequent video publishing on Stacks YouTube channel, add to the variety of people on channel, increase Twitter views, and/or landing page hits from a video.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Kurt -  I have a video streaming room and setup where these videos will be produced.  I keep up to date with Twitter and the Discord communities.

Twitter: https://twitter.com/kurtgrela
Twitter biz: https://twitter.com/101BlockchainSt
YouTube: https://youtu.be/EbMaEanx84c
Blog post: Top 10 Tips for NYC Coin https://tweets.101blockchainst.com/p/top-10-tips-for-nyc-coin

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

I am dependent on internet. If there is a winter storm where there is an outage, I can create content later in the day or usually the next day.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

After I wrote the Top 10 Tips for NYC Coin, the CityCoin Discord admins pinned my blog post.  I show more than 450 people have visited that blog post. My tweet announcing the article has ~4,500 impressions and ~400 engagements! The corresponding YouTube video has 160 views, which is a good start. All of this demonstrates people are interested in STX content.

**Comment by jennymith** [comment]
Just noting here that you've spoken with the grants team and are currently working on your first "drafts" of these videos.

**Comment by friedger** [comment]
Great proposal!

In my opinion, the current topics are too much focused on CityCoins, maybe that is just me.

**Comment by kurtgrela** [comment]
Closing
