### ISSUE TITLE
dnarstacks-Africa

### ISSUE THREAD

**Issue by enochpromo** [stacksgov/Stacks-Grants#238]
**Background**
People in many developing countries lack access to interest-bearing accounts denominated in US Dollars or other relatively-secure, global reserve currencies. 

In many countries, people wish to hold USD in order to mitigate the risks brought on by exchange rate volatility and inflation of their native fiat currency. They deposit large amounts of USD in the most secure place they have access to: banks. But these banks are not legally permitted to provide their customers interest payments on USD-denominated deposits. 

In Ghana, where Dnar is already operating a cryptocurrency exchange with 40,000 users, depositors can earn interest on their deposits made in the local currency but these deposits run into inflation and exchange rate risks. With USD inflation at the highest rate in nearly 40 years, USD deposits that don’t earn any interest are currently decreasing in real value by over 6% year-over-year. 

Depositors in developing countries are desperately seeking alternatives to their 0% APY USD-denominated bank accounts.

**Project Overview**
Dnar wishes offer a vehicle for depositors in Ghana to earn interest on dollar-denominated deposits through crypto & stablecoins.

We will build a prototype application on Stacks that enables depositors to earn interest payments in Bitcoin or USDC for deposits made in USD-denominated stablecoins or Bitcoin on Stacks

We plan to integrate Arkadiko/Zest Protocol in order to leverage their technology which enables deposits to earn interest in their own stablecoin. Our fork will give depositors the ability to swap their local currency for USDC or Bitcoin and earn interest in either of those cryptocurrencies.

**Mission alignment**
This project aligns with the Stacks Foundation priority to build infrastructure for a user-owned Internet. This project enables Bitcoin to tackle an issue where traditional finance is not able to offer a solution. **We enable DeFi with mobile money onramp/offramp built on Bitcoin for Africa.**

We will enable Ghanaians to leverage the user-owned Internet (Bitcoin and stablecoins) to earn interest on their dollar-denominated bank deposits. In this case, the user-owned Internet can provide a solution that addresses inflation and exchange rate risks for depositors at banks in Ghana.

We believe that this prototype for Ghana, supported by the Stacks Foundation, can grow into an application that serves people in any emerging market. When you create a solution that works in Africa, you create a solution that can work anywhere.

**Scope**
Final deliverable 
A white-label DeFi application built on top of Stacks/Arkadiko that enables users to deposit crypto or fiat and earn interest in USDC & Bitcoin.

**Customer Journey**

![DNAR 2](https://user-images.githubusercontent.com/34989007/153321306-97cc8f70-a578-4ada-b9f7-5ac1902c1bae.png)

This diagram shows the steps the customer will need to take in order to earn STX, BTC or USDC interest their deposits .

Existing users will be able to log into the application and utilize product
Product will have separate screen

**Budget and milestones**
Total Grant Request: $25,000 (15,000 STX at time of writing) / 12 weeks

**M1:** Publish the build scope to Github for community feedback 
Hiring and onboarding up to three Clarity developers
Write detailed technical specifications and build application roadmap
Publish landing page communicating Web3 & Bitcoin/DeFi upgrades coming soon
3 weeks

**M2:** Build back-end and integrate testnet version within existing application
Back-end server implementation built on top of Stacks/Arkadiko
Low fi, UX Web application
Low fi, UX Mobile application
5 weeks

**M3:** Functional working prototype
Front-end implementation functional and connected to back-end
Deployment of testnet version with working React Native Front End
Documentation
Hi-fi UX & UI 
4 weeks

**M4:** Prototype is implemented within Dnar app through beta
Functional application with DeFi on Stacks enabled for web & mobile.
Official new screens with UI enabled for Web & mobile

**Team:** 

Dnar and Enoch Antwi will lead the project, providing software development, strategic direction, and engagement with African banks, regulators, and other key stakeholders to ensure product-market fit. Enoch will also be consulting with Phillip De Smelt, Founder of Arkadiko. We will need up to three additional Clarity engineers. Enoch has been in touch with Clarity engineers from successful Stacks-funded projects about helping with this. Dnar’s team of six software engineers has built a crypto exchange from scratch, engaging 40,000 unique users and integrating with fiat on- and off-ramps in Ghana. As the founder of Dnar, Enoch has engaged deeply with regulators on Bitcoin and other digital currencies and has been featured on CNBC Africa.

**Comment by will-at-stacks** [comment]
Thanks for submitting a grant application! Due to the holiday break, grant reviews are currently on hiatus and will resume on January 5th. In the meantime, we encourage you to continue to share and get feedback on your application from the community.

**Comment by enochpromo** [comment]
Thanks for the feedback Will! 

Will share with a few folks I know and see if I can reach out to some people in the discord.

**Comment by enochpromo** [comment]
Hey Will! 

I will look into this immediately.

Thank you very much.

**Comment by enochpromo** [comment]
> Hi Enoch, thanks for your application. We would like for you to make some revisions and resubmit this application before we will be able to arrive at a decision. Can you please:
> 
> * Provide a bit more detail under the Scope, Final Deliverable, and Measure of Success sections?  In particular, the Final Deliverable section.  We need some context on what point in the process you are at now and what you intend to build.  Is this a brand new application?  Or new features to an existing application?  What is the user path you are looking to satisfy?  Are these new users or existing users?
> * Secondly, can you simplify the Budget and Milestones section?  Each milestone requires its own review and 15 milestones would be cumbersome for you and us.
>   A good application to use as an example is this one:
> 
> #251
> 
> We look forward to reviewing your revised application.
> 
> Thanks, Will

**What is the user path you are looking to satisfy?**

Please indicate what you mean by this? Are you talking specifically in reference to a customer journey or use case? What do you mean by "user path"

**Comment by will-at-stacks** [comment]
Hi @enochpromo - We are having a difficult time understanding the 'extents' of your grant scope.  By 'user path', we mean the customer journey.  This will help us better understand what features already exist and what you plan to build.  If you could make a quick diagram using whimsical.com that would be great.  This is also a link to a grant proposal that provides a nice summary of the user path we funded for them.

https://github.com/stacksgov/Stacks-Grants/issues/220

Best,
Will

**Comment by enochpromo** [comment]
Hey Will,

Checking it to let you know we are making some final modifications and working out some things internally. I have some Stacks engineers helping with this. The next submission will be much clear, thanks for the feedback and the guidance.

**Comment by enochpromo** [comment]
Hey @will-at-stacks 

done!

**Comment by will-at-stacks** [comment]
@enochpromo received.  We will add this to our list of grants to review.

**Comment by enochpromo** [comment]
@will-at-stacks thanks!!

Speak soon.

**Comment by louiseivan** [comment]
Quick high-level questions

- As an ecosystem, we're all about increasing STX access, how do you increase it? 
- Why fork Arkadiko when you can integrate it? Maybe there's a scenario where you guys can collaborate instead of forking it
- CreditCoin has a similar approach wherein they act as a vehicle for depositors in Africa to get exposure on DeFi Yields

**Comment by enochpromo** [comment]
Hello Louise, great questions. I will address each of them.

- As an ecosystem, we're all about increasing STX access, how do you increase it?

1. We are increasing access by offering a yield product that gives incentive for stacking
2.  Once we integrate this product we will be offering STX on our exchange, we have over 40k users.

- Why fork Arkadiko when you can integrate it? Maybe there's a scenario where you guys can collaborate instead of forking it

1. We will not be forking Arkadiko, I am in touch with the founder and we are discussing integration and he's also making intros. 

- CreditCoin has a similar approach wherein they act as a vehicle for depositors in Africa to get exposure on DeFi Yields

1. It is important to note Creditcoin is not live. Although their approach is slightly similar we are very different.
2. They act as an aggregator and match.
2. Credit coin is on its own blockchain.
3. Creditcoin aims to decentralize credit history. 
4. It's also worth noting that Creditcoin is also coming out with their own token at 200m supply. Coming out initially with your own token is not the best approach in an emerging market.

**Comment by will-at-stacks** [comment]
@enochpromo thank you very much for your engagement in the review process and being so open to feedback.  Since the initial phone call with your team several months ago, I, personally, have noticed your continuous engagement in the Stacks community.  Excited to approve this grant!
I am going to break this up into (4) $6,250 payments issued at the start of each milestone so you have the working capital to complete the work.  We look forward to seeing this project progress!

**Comment by enochpromo** [comment]
Thank you very much @will-at-stacks @louiseivan 

I will keeping you both up to speed on the exciting developments happening on our side. 

Looking forward to working with Stacks!

**Comment by enochpromo** [comment]
@will-at-stacks 

Checking in to let you know that we will be submitting for M1 soon. Progress is moving on well.

**Comment by will-at-stacks** [comment]
@enochpromo great.  Thank you for the update.  Excited to see what you've accomplished!

**Comment by enochpromo** [comment]
Hey @will-at-stacks 

I have sent documents over to you via email communicating what we have achieved. Including the internal roadmap, developers, etc. modifications has been made to the website and below includes our build scope and public organization

Build Scope
[build scope](https://github.com/dnarStacks)

Public organization
[dnarStacks](https://github.com/dnarStacks)

Build will be open source and made for other fintechs, crypto exchanges to integrate via api

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
