### ISSUE TITLE
RayoCity Grant Application

### ISSUE THREAD

**Issue by metadimensions** [stacksgov/Stacks-Grants#255]
**Background**

The problem is mostly Content Publishers don't have good revenue in a decentralized environment, to solve this we're building a RayoCity in Metaverse - the next big thing in Blockchain. We are just building this as a Blockchain Game to create a Visual Appeal, in the RayoCity community, there will be Players, Publishers, and Developers, these people will get benefitted through game incentives and earning through self-published content.

**Project Overview**
RayoCity is a modern-day Simulation Game on Polygon Chain where users can earn, build, own, trade, and explore a Virtual City. It is a complete Universe, this Virtual city has everything, it has a Shopping mall, Airport, Library, Bank, Sports Complex, and a lot more. Users can visit a Shopping mall to purchase & trade NFT's, play arcade games to get incentives (Play-to-Earn). They can go anywhere in the city and do whatever they want to do. Users can also visit a Central library where they can buy or sell E-books and they can also publish their own content. If a user sells a book another user can buy that book within this library through RCTY tokens.

**Scope**
Our Game will be built on Polygon (Matic) Chain, we have done major research on choosing the blockchain considering that Polygon will fit our needs.

Tech Stack:-
Frontend - React
Smart Contract - Solidity
API's - Serverless (AWS Lambda or Google Cloud Functions)
Play-to-Earn Games - HTML Phaser, WebGL, and Three JS
UI/UX - Figma
Graphics - Adobe Illustrator
Collaboration - Github and Notion
Docs- GitBook

**Budget and Milestones**

Minimum Viable Product (MVP) Version 1 - will be completed and launched on Feb 12- Feb 18, 2022, with RCTY Token

Currently, we are working on the Game UI Design, once the design system is completed we need to work with our In-Game Smart Contracts. We're looking to complete version 1 with Shopping Mall, Airport, and Library. This version will allow users to enter into the RayoCity Metaverse like Playing Game (P2E), NFT Trading, and Selling/Lending E-Books.

Required Funds:-
1.  Smart Contract Engineer - $7000
2. Auditing Smart Contracts - $2000
4. UI/UX and Graphic Design - $4000

Total Grant Request:  $20,000

**Team**
All three of us are Software Engineers and know each other for a long time. We have good experience building products from scratch and our core competencies are React, Vue, Node JS, Python, Unity 3D, WebGL, Three JS, API Development, and Cloud Services - AWS, GCP.  We have an intermediate level of Dapps Development Experience. So we're looking to hire an experienced Blockchain Engineer who will write our Smart Contracts which should be more secure due to the Play-to-Earn Ecosystem. Apart from this, we have the ability to complete the Frontend, In-built Games, and APIs. Please do check our Github account:- [https://github.com/10dimensions](url)
[https://github.com/metadimensions](url)

**Risks**
The main Obstacle is that our idea is really big which can't happen overnight it takes a lot of hard work, time, and patience to build a Universe like RayoCity if you have checked our Whitepaper - [https://docs.rayocity.com](url)  you know about what we're building. As our project is going to be in the Metaverse still people do not what it is all about, but people have a good awareness about Simulation Games like SIMS, Tycoon. Our aim is to solve the above-mentioned problem through a simulation game. Another obstacle is smart contract experience, though we have an intermediate level of knowledge we need an experienced blockchain engineer to be part of this.

**Community and Supporting Materials**
Currently, we're in an early development stage looking forward to completing our MVP version also we have community channels across Twitter, Telegram, and Discord but we are yet to start the engagement, once our Game is launched hope we will have a good community engagement.

**Quick Links:-**

Website: https://rayocity.com/
Twitter: https://twitter.com/rayocitygame
Discord: https://discord.gg/dvy47Rwr
Medium: https://rayocity.medium.com
Telegram: https://t.me/rayocity

**Comment by will-at-stacks** [comment]
Hi @metadimensions - 

Thank you for the application.  This sounds like a really interesting project.  

While we are open to funding projects on other chains we do want to make sure all Stacks Foundation funds are deployed in a way that in some way benefits the Stacks ecosystem.  We are also hesitant to allocate 35% of grant funds to marketing efforts for a project in its infancy.  Obviously, marketing is important, but we would prefer to keep the focus of any funds awarded to you directed at the development of your MVP.  If you could address these issues and help us better understand why you felt the Stacks Foundation could be a strategic partner to you at this time, we would love to review that revised proposal.

Best, 
Will

**Comment by metadimensions** [comment]
Hi @will-at-stacks 

Thanks for getting back to us.

We have been keeping an eye on Stacks Foundation Funds for some time, right now as we are in a very early stage of development and looking to raise funds to work on our core Smart Contracts, even though we have good development experience I guess we need an experienced Smart Contract Engineer because our Project contains Incentives Ecosystem which should be more secure and reliable.

So we don't need a Marketing budget as of now, our reason for the grant is to build our MVP. Apart from the Blockchain, and UI/UX Design, our team has the ability to complete other development work like Frontend, Games, and APIs. So the grant we receive from Stacks Foundation will be solely used only for Product Development purposes.

Revised Proposal will be:-
1. Smart Contract Engineer - $7000
2. Auditing Smart Contracts - $2000
3. UI/UX and Graphic Design - $4000

Total Grant Amount:-$13,000

Thanks,
Venki

**Comment by will-at-stacks** [comment]
gm @metadimensions -

Thanks for revising the application.  Just curious if you are considering Clarity as a smart contracting language - and building on Stacks?  Or are you committed to Solidity / Polygon?  Also, are you familiar with Moonray (Stacks-based NFT game) and/or the Stacks Accelerator?  

Just trying to get a bit more context as to your familiarity with Stacks.  

I will huddle with others early next week and get back to you.  If you could respond prior to that - that would be helpful.

Thanks,
Will

**Comment by metadimensions** [comment]
Hello @will-at-stacks ,

We had an internal discussion about this, right now we are in an early-stage development so we don't have any technical restrictions, we are just getting started. Also, we know about the Stacks Ecosystem and the major apps which are built on it, still Bitcoin is the largest liquidity provider globally, it will be very unique if we build our Game on this ecosystem.

We are ready to build our RayoCity Game on top of Stacks Blockchain if we get good Seed funding support from the Stacks Ecosystem

Looking forward to this.

Thanks,
Venki

**Comment by metadimensions** [comment]
Hello @will-at-stacks ,

We had an internal discussion about this, right now we are in an early-stage development so we don't have any technical restrictions, we are just getting started. Also, we know about the Stacks Ecosystem and the major apps which are built on it, still Bitcoin is the largest liquidity provider globally, it will be very unique if we build our Game on this ecosystem.

We are ready to build our RayoCity Game on top of Stacks Blockchain if we get good Seed funding support from the Stacks Ecosystem along with this Grant.

Looking forward to this.

Thanks,
Venki

**Comment by metadimensions** [comment]
Hey @will-at-stacks 

Did you have a chance to talk with the other stakeholders? 

Let me know if you need further details from us.

Thanks,
Venki

**Comment by will-at-stacks** [comment]
Hi @metadimensions   

Thank you for the follow up.  After discussing this a bit further and taking a look at the GitHub repos and whitepaper you provided we have decided to reject this proposal.  We feel this is a really interesting project and quite ambituous.  When you contrast the scope of the project you have in mind with the code and technical details we have available to review, we are concerned that your team would be able to deliver on the proposed MVP.  Please let us know if you feel we may have missed something or if something was lost in translation.  If you do feel like you can improve the code / whitepaper / proposal to address these concerns, we would love to reconsider.

Best,
Will

**Comment by metadimensions** [comment]
Hello @will-at-stacks ,

Thanks for the reply.

To give a context about this, our Whitepaper might give a detailed overview of what we are building but we may add new things in the future too, to talk about the Github repos we are just getting started also the reason for this grant is completely for development purposes. Right now we are in need of an experienced Blockchain Engineer to write the smart contracts and UI/UX designer to create our game ecosystem. 

You can also check our personal Github repos if you are more concerned about our development experience 
Vishal V -  https://github.com/10dimensions
Venkatasuburamanian A - https://github.com/metadimensions

Also do let us know what details are missing on our proposal/whitepaper, so we will update it accordingly. We can also schedule a Zoom call if it's possible.

Thanks,
Venkat

**Comment by metadimensions** [comment]
Hello @will-at-stacks ,

Just to inform you we have got a Grant offer from a Blockchain community to build our project on their chain, so please let us know your update on our grant.

Thanks,
Venkat

**Comment by will-at-stacks** [comment]
Hi @metadimensions -
Are you and your team able to meet for a Zoom meeting next Wed at 3:30pm EST?  Can you please email me at will@stacks.org so I can forward you the invite?

Thanks
Will

**Comment by will-at-stacks** [comment]
Hi @metadimensions - Please excuse us if your review takes a bit longer than normal as e are in the process of rolling out a new platform.  Additionally, I am out of the office until 2/7.  We will get back to you as soon as we can.  Best, Will

**Comment by metadimensions** [comment]
Hello @will-at-stacks,

Hope you are doing good.

We have been waiting for you to discuss the grant work.
