### ISSUE TITLE
BeltLacer Risk Pools

### ISSUE THREAD

**Issue by dougvahey** [stacksgov/Stacks-Grants#259]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

Today’s insurance companies have every incentive to dispute/delay claims to hoard profits.  Early business models were “mutuals” where individuals owned the company, pooled their money to insure, and enjoyed profits (absent catastrophic losses).  BeltLacer will rediscover the roots of risk-taking by testing the concept of user-owned risk-pools for small property (cell phone breakage), hypothesizing that people will share risk and rewards through common token ownership and utilitarian risk management for small-loss property items.  But we envision this model for homeowners insurance someday. 

**Project Overview**
What solution are you providing? Who will it serve?

Build 5 risk-pools with 20 owners each.  Build a reinsurance “lake” atop pools (if pool becomes illiquid due to claims).   Test economics of token pay-in, liquidity pooling–in all pools, staking, and token-dividends.  Build wallet capabilities for owners.  Experiment with pools with owners who are affiliated with each other + those unaffiliated. BeltLacer already has an iOS + Android app with 
 9 diagnostic tests for phone health (screen, sound, etc).
Appointment making capabilities for phone fix in New York City (with 2 repair shops) 
(note: grant request does not entail moving phone tests or phone health history on-chain) 

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

Wallet + token
Build liquidity pools + liquidity lake
Fill pools (w/ 20 owners each + $) + lake ($) = test risk-sharing behavior
Test economics of $ intake + liquidity + dividend

Goal is to test if we can build something of value for owners.  Will the economics of pooling/claims paying/staking provide enough value to supplement the other phone values: diagnostic testing, coverage for already-brokens, easy/expert repair, health record (on-chain someday) = “carfax” for phones = verifiable valuation/ownership for reselling? 

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $10,000 ($100/hr.)

M1: Scope of work, deliverables, and grant amount of total.
Build wallet + token capabilities:  20 hrs.
Build 5 pools + lake:  20 hrs.
Marketing to fill 5 pools with 100 testers  30 hrs.
Evaluation of business model and value proposition:  30 hrs over 3 months.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skill sets you are missing that you are seeking from the community? Please share links to previous work. 

Founders:  Amit Nema (Bloomberg and Founder @  https://www.uptick.co/dashboard) and Doug Vahey (Chubb Insurance and Founder @ RiskPool.co–p2p insurance for small property items and (unable to find product-market fit) and Founder at PRA Global–insurance captive for doctors recommending medical cannabis. Raised $1.5m seed ).  Doug is FT and Amit is PT.  Doug has domain expertise and Amit is very tech-savvy, but neither has experience with Clarity or enough familiarity with the STX blockchain.  We outsourced our existing app to a developer in India.  

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

**Business model may be not be supported on Stacks
**Inability to engage Clarity resources

<img width="483" alt="Screen Shot 2022-01-09 at 1 17 29 PM" src="https://user-images.githubusercontent.com/12103083/149405277-0125cff8-a514-426f-a6df-033e4743dabf.png">

**Comment by friedger** [comment]
To me it is not clear what the scope is

> Wallet + token
Do you build a wallet?

> Build liquidity pools + liquidity lake
What does building a pool and a lake involve? Marketing? Development?

> Fill pools (w/ 20 owners each + $) + lake ($) = test risk-sharing behavior
Is this just a bank transfer?

> Test economics of $ intake + liquidity + dividend
How does a test look like?

More generally, why is an on-chain token necessary? If I sell my phone or repair my phone, are tokens burnt? Is a local currency more appropriate?

**Comment by tycho1212** [comment]
Interesting project! I'd also be curious about a clear answer to the question: why not use a central database for this?

**Comment by dougvahey** [comment]
Thank you for your questions friedger and tycho1212.  We believe hard property (vs. digital) items---the records of which--will find their way onto the blockchain because a proper valuation will require immutable validation of ownership, damage, maintenance, and improvements.  Example:  a rare watch can be insured for the amount YOU want to insure it for (vs. the amount the insurance company dictates), which may a $ value more than normal because because the person wearing it is famous.  To your other questions, we build wallet connectedness (not the actual wallet) and group people so that w can test the efficacy of risk sharing / liquidity pooling with people you know / don't know.  (P2P insurance has failed for various reasons, on various continents, and we suspect that insuring with people you don't know will be more successful---especially if we can align incentives around token-ownership and better utilitarian risk management behaviors).  We are open to other ideas. Nexus Mutual in London (smart contract insurance) is using their token mainly for governance.  We need to find actual testers to pay and participate in this smaller pool structure for 3 months.  We will also try to learn if the economics of small + larger liquidity pools allow people to protect their phones for at or near "no cost."  Or learn that the existing system, with its hidden deductibles, other nasty surprises, and costing people $300-$600, is the only way.

**Comment by dougvahey** [comment]
Inadvertently clicked "send" with a couple grammatical errors.  Apologies.

**Comment by tycho1212** [comment]
Hm, is small property the best way to test whether p2p insurance can work on chain though? In my mind, the model might find more success when insuring goods whose ownership is digitally verifiable

**Comment by dougvahey** [comment]
We think small property is a good place to start----claim frequency vs. severity + low stakes + low fraud (breakage = repair; not a new phone).   And insurance will always surprise you with behavioral learnings.  The phone make/model is digitally verifiable (e.g  iPhone 13) and in our case, the owner is making the purchase from his/her/their wallet.   The phone diagnostic tests run by our app (links below) will someday all be verified on-chain (though this grant does not contemplate putting those tests on-chain).   Thank you tycho1212 for the push question.  Doug     https://apps.apple.com/us/app/beltlacer/id1458889599                                              https://play.google.com/store/apps/details?id=io.ipsofacto&hl=en_US&gl=US

**Comment by will-at-stacks** [comment]
Hello @dougvahey  - Apologies for the delay, we have been reviewing this internally and are very interested by the concepts presented, but share some of the concerns other commenters have posted.  Would it be possible for you to simplify the proposal in such a way that is easier for people outside of this industry to understand?  Specifically, what is a “liquidity lake” and how does it work?  How is it that an individual would be able to determine the value of a good (rare watch example) rather than an appraiser / adjustor?  Some of the digital world to physical world connections required to make this successful give us pause.  We would much rather see this as a p2p insurance experiment for digital assets.  We hope you consider this feedback and submit a new proposal.  Thanks, Will
