### ISSUE TITLE
Experience / Access Token Model

### ISSUE THREAD

**Issue by Agent2222** [stacksgov/Stacks-Grants#26]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> What problems do you aim to solve? How does it serve the mission of a user owned internet?

NFT's are great, but once the scarcity and community appeal diminishes one may realize that the true utility of an NFT without an action based incentive- like the competitive advantage of a rare Magic Card, strong Pokemon, or ad reachability in Decentraland- becomes experience, and experience limited to a static 2d image can get old quick.

Alternatively, designing variations of NFT's could solve this problem. One variation would be an Experience Token. A token that- much like NFT's- are non-fungible, but non-fungible in the sense the experience would contain slightly different media assets, and allow for the user to input data, and present themselves as an individual navigating through an experience. But most importantly, experiences end. An Experience Token could return to the issuer of the token, or be sold by the initial user to a new user once the experience is complete. Access to the experience would be limited to a fixed amount, and new experiences can continue to be developed without polluting the Blockstack eco-system with NFT's that depreciate in value. 

## Project Overview

> What solution are you providing? Who will it serve?

The project will explore use case options of managing access to experiences and duration based ownership. Additionally developing a general use case component and UI that can be adopted by applications interested in access control and NFT's.

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

This project will research blockchain and non-blockchain experiences to develop a model to monetize, or develop marketplaces for experiences. As well as developing smart contracts based on duration or completion of experiences.
- Collect information on successful incentive based physical NFT's
- Develop digital models of incentive based NFT's
- Develop presentation deck comparing physical incentives to digital incentives for NFT's - 6 pages.
- Develop general ui component for experience ownership. 
- Develop clarity, duration/progress based smart contract 

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Seeking $5000
1 week research 
1 week presentation development
1 Week UI component development
2 Weeks clarity contract development

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?

TBD

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

Radiks MongoDb upcoming changes

## Community and Supporting Materials

> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

I've been developing this project for the past year and a half and can provide screenshot of current designs for a customized implementation of this project. Public githib will be created for this project.

**Comment by ryanarndtcm** [comment]
Thanks for your application! I am reaching out for feedback around Radiks changes, but if you can update your application breaking down the $5000 into potential milestones and also adding the team section - that would be a great next step. Thanks!

**Comment by hstove** [comment]
Could you further explain which "upcoming changes" to Radiks you are dependent on, and why?

**Comment by Agent2222** [comment]
> Thanks for your application! I am reaching out for feedback around Radiks changes, but if you can update your application breaking down the $5000 into potential milestones and also adding the team section - that would be a great next step. Thanks!

**Comment by Agent2222** [comment]
> Could you further explain which "upcoming changes" to Radiks you are dependent on, and why?

Hi Hank, I received an email from Heroku of upcoming MongoDB add-on changes that will effect my project. 

"The mLab team has chosen to discontinue this add-on. The mLab MongoDB add-on will be removed from all Heroku apps on November 10, 2020. We advise you to remove the mLab MongoDB add-on yourself before September 1, 2020 via the Dashboard or the CLI. As of September 1, the add-on will no longer be visible on the marketplace, and installations and plan changes will not be possible. 

Next Steps
You may wish to consider an alternative data store add-on from the Heroku Elements marketplace, such as the ObjectRocket for MongoDB add-on (available as of the date of this email). For customers who are considering remaining with mLab/Atlas, information can be found here."

**Comment by Agent2222** [comment]
> Thanks for your application! I am reaching out for feedback around Radiks changes, but if you can update your application breaking down the $5000 into potential milestones and also adding the team section - that would be a great next step. Thanks!

Upcoming Heroku add-on changes. https://docs.mlab.com/shutdown-of-heroku-add-on/

**Comment by hstove** [comment]
I see - fortunately for Radiks, it doesn't matter where you host MongoDB. Any of the other MongoDB addons work, or you can even use a different provider outside of the Heroku Addon ecosystem. Radiks just needs a valid MongoDB URI in the environment variable `MONGODB_URI`.
