### ISSUE TITLE
Robot NFT

### ISSUE THREAD

**Issue by KUNZIT** [stacksgov/Stacks-Grants#261]
**Background**

Trading on the crypto market is highly risky, to be profitable with it, some people are  use trading robots- this is a software which switchetable settings . It may be complicated to use , take time to optimize, so any community won't deal with it . Trader do not own Trading strategy just put on settings. Trading History hasn't identified. No public accessible records.

**Project Overview**

It's will be an NFT associated with Robot software. For example if you want to buy 1.0 BTC wenn mowing averages crossed, just do pay related NFT and await for results. 

Created dAapp on Stacks blockchain

**Scope**

BNS ,Gaia stacks

Will look like dApp with Stacks blockchain integration and ability to buy NFTs
Amount of NFT to be sold will indicate success 
![Demo nft_220116_114407](https://user-images.githubusercontent.com/94623385/149659043-c0aac776-8f11-41be-a8ac-95c7631839c2.jpg)

**Budget and Milestones**

1. Web site design 20 H
2. NFT design 20 H
3. Navigation Catalogue 20 H
4. Testing demonstration 17 H
5.  Grant Request: 7700$

M1: Scope of work, deliverables, and grant amount of total.
77 Hours x100$ = 7.700 USD

M2: Etc.

**Team**

Vadims Kokins experienced forex and crypto market trader. I do learn coding but need more practice. 

**Risks**
Internet stuck ,crypto winter season. Will try to turn funds into education and advertising, hold created NFTs for future business opportunities. Crypto market regulations in Europa. Mowing to El Salvador to build Bitcoin City.

**Community and Supporting Materials**

It will be my first DAPP with coding work, but I have already experience working with training bots. I will be able to open an physical office in the City business center and make some direct presentations to investors, collectors and merchants.

**Comment by KUNZIT** [comment]
Thank you

**Comment by will-at-stacks** [comment]
Hello @KUNZIT  - Thank you for the application.  We have decided to reject this application on the grounds that we found the text very difficult to read.  However, from what we could gather this is a proposal for a crypto trading bot.  This sounds like a cool idea, but not one we would support as it does not clearly benefit the Stacks community.  Best, Will
