### ISSUE TITLE
Add block compute utilization to explorer 

### ISSUE THREAD

**Issue by bkirby989** [stacksgov/Stacks-Grants#262]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

- The explorer provides visibility into the number of transactions bundled into a block, but this number can be misleading because blocks are constrained primarily by compute resources. Seeing compute utilization is a better metric to determine capacity bottlenecks and network health. 

**Project Overview**
What solution are you providing? Who will it serve?

- Show block compute utilization next to transaction count in explorer "Recent Blocks" dashboard. This will serve anyone who uses the explorer to get insight into current network capacity/health, particularly during times of heavy network usage (new nft drops, defi application launches etc.)

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

- Mock UI: 
![mockui2](https://user-images.githubusercontent.com/1795493/149815424-3098f256-f714-4490-8d34-3c767385d558.JPG)

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

- ~10 Hours 
- Total Grant Request: $1000

- Happy to adjust if this seems unrealistic. This being my first project in stacks ecosystem, an estimate is somewhat difficult to come up with, but my aim is for this to be something small and realistic that could be built upon.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

- I'm a JS/PHP engineer with 8 years experience building for the web. I'm new to stacks dev and this seems like a good first project. 

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

- Not many but perhaps getting onboarded with stacks api/developer tools, running a node, etc. I intend to ask for help in the relevant discords if I'm unable to solve the issue through documentation alone. 

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

- I discussed this with @jcnelson in the core-devs meeting today.

**Comment by tycho1212** [comment]
Second this!

Would there also be a way of showing which specific transactions take up a lot of compute? The better the explorer communicates why things are slow, the more understanding people in the community will be imo

**Comment by JakeBlockchain** [comment]
+1

I like Tycho's suggestion as well.
More info lets everyone make better decisions and understand what is going on with the network.

**Comment by will-at-stacks** [comment]
@bkirby989 
Hi Bradley, Thanks very much for the proposal.  This feature will be welcomed in the community.  We would like to approve this proposal, but could you please first let us know if you need to adjust your budget so that you can incorporate the feedback from @tycho?  “Show which specific transactions take up a lot of compute?”

Thanks,
Will

**Comment by bkirby989** [comment]
Hey @will-at-stacks, that's great news, happy to hear it! I agree that's a good suggestion from @tycho1212 . 

I'd adjust the budget to include an additional 5 hours, and $500 (so 15 hours, $1500 total) to include per-transaction compute details sorted on the block details view (https://explorer.stacks.co/block/0x05ba48c734144d9a21df440ac09f6562fbd7ccbce3beca9e4eca595e184e379a?chain=mainnet)

If time allows I could also include a pie chart with compute utilization broken down by contract for each block.

**Comment by will-at-stacks** [comment]
Hi @bkirby989 -
Thank you for revising the application to include that extra scope.  This is approved!  Please reach out when the work is complete so we can check it out!  
Thanks,
Will

**Comment by bkirby989** [comment]
Will do, thanks a ton @will-at-stacks!

**Comment by will-at-stacks** [comment]
Hi @bkirby989 just checking in.  Can you please provide us with an update on this grant?  Thanks, Will

**Comment by bkirby989** [comment]
Hey @will-at-stacks! Super sorry for the delay. Got swamped with my full time gig right as this was accepted. Will have a proper update for you with some code to review by Monday.

**Comment by bkirby989** [comment]
Hey Will,

My apologies, but I will not be able to complete my grant as written. What
address should I return the funds to?
