### ISSUE TITLE
Stacks Nigeria Chapter Re-application

### ISSUE THREAD

**Issue by ogasky** [stacksgov/Stacks-Grants#273]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?
The Stacks Nigeria Community on Telegram (https://t.me/StacksNigeria) has grown in number and thus there is the need for meetups in order for members to learn about Stacks and also develop projects on the Stacks blockchain as well as grow the community too.

**Project Overview**
What solution are you providing? Who will it serve?
Stacks Nigeria Chapter is a community of Stacks developers and enthusiasts living in Nigeria. The community will have at least one meetup per month in any state of Nigeria, coupled with training workshops, seminars, conferences and hackathon that will be done quarterly and annually in order for members to have more knowledge about Stacks and connect with other Stacks professionals. During these meetups and training workshops, Stacks developer/advocates will do slides presentations to participants that will be gathered in a room or hall. It is key to note that most of these meetups will be physical because there is no lockdown in Nigeria, but safety protocol will be duly observed at all time. Also swags will be giving to participants during these Stacks events towards promoting Stacks to others.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
Members will be taught several Stacks related topics which include: Clarity, Smart Contracts, NFTs, Stacking & Stacking pools, Available APIs for Stacks projects, etc. To achieve these, slides and video presentations will be used and meetup venue will be conducive and open to all. Stacks experts/developers will be invited to our meetups to educate members on Stacks. Our goal is to equip members to develop projects on Stacks.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.
This is going to be monthly meetup activities:

Venue for Stacks Meetup:       600 USD
Participants Refreshment:       800 USD
Resource (Internet & Videos): 400 USD
Logistics & Publicity:               900 USD
Production of Stacks Swags:  1300 USD
Facilitating Team:                   1000 USD 

Total Grant Request: 5000 USD

M1: Detailed report will be send via the appropriate channel after the monthly meetup.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 
I am Onose Oghenevwogaga by name, & the lead of this community . I am a tech & blockchain community developer and have organized several tech and blockchain events in Nigeria. See the links below for more details
https://t.me/StacksNigeria
https://drive.google.com/drive/folders/12VPnxgkSLlf-iqVlWeAEZWPNrt2ebm3Q?usp=sharing
https://drive.google.com/drive/folders/1wSpeipcMFSWHu8PwK-Q5xwBpvnXMcxOA?usp=sharing
https://www.meetup.com/CodeUp-Africa/events/282613054/
https://www.meetup.com/CodeUp-Africa/events/280108192/
https://www.meetup.com/CodeUp-Africa/events/275977884/
https://www.meetup.com/chainlink-nigeria-connected-smart-contracts/
https://www.meetup.com/GitLab-Nigeria-Community/

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
The risk is that there are no much Clarity and Stacks developer around this part of the world but presently I am a participant of the 2nd Clarity Universe Cohort, thus will connect to others.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?
Our community will be informed of future meetups via the telegram group and photos will be sent to the appropriate channel after the meetup.

**Comment by louiseivan** [comment]
Louise here from the Stacks Foundation. Saw the growth over your Telegram group! I always tell builders _building community is no rocket science 🚀 , but this doesn't mean it is easy as there's no particular framework for it_. To re-iterate each of the chapters is working with at least one of the community OKRs below:

1. Increase the # of token holders to 1,000,000. There are currently 410K STX Holders.
2. Expand Stacks to more than 100 countries. 
3. Increase the # of Stacking Pools and the # of total STX Locked.
4. Increase the # of Mining Pools and the # of total BTC Transferred.
5. Increase the # of Smart Contracts build. Currently at 152.

Aside from this we need supporting materials showing that you have been part of the Stacks community for at least 6 months. Lastly, Chapters must also come up with their own financially sustainability plans.

**Comment by ogasky** [comment]
@louiseivan, Thanks for acknowledging the growth of our Telegram group, it was not really easy but thank God for the growth in number. However, as regard working with one of the community OKRs listed above, I want to state clearly that we can fit into any of the #1 to #5 you listed, except the #4 which may require more sophisticated and very expensive gadgets/equipment to set up. But I want to assure you that you will see some smart contracts build from the community as in #5, the number of token holders will increase because activities and projects from the community will make more members execute projects that will initiate STX transactions thus leading to the actualization of #1. Entering Nigeria will aid #2 to fruition as we are ready to make it a huge success. We will encourage the community members to stake in available staking pools towards realizing #3.

For the record I join the Stack community (Telegram group) before I creating my country telegram channel & which is over six months, I remember clearly that that was the period I initially applied for the Approval of the Nigeria Chapter see the link here https://github.com/stacksgov/Stacks-Grants/issues/127 to get the date. 

As regard sustainability, I want to state here that I look forward to a chapter that will get projects done that will add value to the Stacks ecosystem. These could be smart contracts build projects or Pool of Stackers. However, I am of the believe that if our chapter is productive and active, it will sustain itself and thus the entire Stacks Foundation will not want to see it die. I don't know if it is proper for stacks members to be levied but am pretty sure that the profit of productive activities can sustain the chapter. Thank you

**Comment by ogasky** [comment]
This is to inform you that we just had a 16 years old secondary school boy from the Nigerian Telegram community group, who minted a design on an NFT & he priced it for $50.00 USD / 40.75 STX. He was also capable of creating his own wallet by himself after giving him some guide. We are indeed making huge progress as a community, and particularly for the young talented ones among us. Thank you.

**Comment by will-at-stacks** [comment]
Hi @ogasky - 

I am very sorry for the long review process.  I've come to learn that we are not accepting applications to start new Stacks Chapters at this time.  Please keep a look out for announcements over the summer regarding the Chapters program.  I will also respond to your other application now.

Best,
Will
