### ISSUE TITLE
STX-Starter: Boilerpates to help the STX dev community build fully functioning STX dApps.

### ISSUE THREAD

**Issue by JungleYak** [stacksgov/Stacks-Grants#283]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

The main problem we intend to solve is the lack of quality boilerplates, developer tutorials, and community resources for writing, testing, and deploying of dApps on Stacks. This specific project is for any developer in the Stacks ecosystem that not only wants to write and test smart contracts but also wants to learn how the smart contracts work together with frontend dApps.

Our overall goal is to help developers get productive by minimizing mundane boilerplate tasks and shipping real dApps quickly.

**Project Overview**
What solution are you providing? Who will it serve?

Our project is called `stx-starter` and is based on the success that` scaffold-eth` [[scaffold-eth Github](https://github.com/scaffold-eth/scaffold-eth)] has had in leveling up developers in the Ethereum ecosystem. We came to the agreement that we should take a similar approach in where each branch of the `stx-starter` project will have specific functionality and detailed information on what is happening behind the scenes. These branches are like mini-apps that can be forked/cloned/deployed with common web3 dApp functionality out of the box

This will serve the Stacks community by helping developers from other ecosystems get up-and-shipping quickly with Stacks

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

We are beginning with a simple dApp scaffold that will include:

Out-of-the-box functionality composed of...

- NextJS w/Tailwind app with a standard layout utilizing the Stacks brand coloring
- Wallet Connect component & displaying the STX balance of the connected wallet
- Faucet component with a contract to get STX from localhost devnet (in case of no/slow connection speed)

With 2 branches as fully functioning dApps

- A basic counter dApp that will increment a count variable on the blockchain, and read the current count
- Minting a basic NFT

Each branch will also have...

- Overview of what the specific branch/app does
- Fully functioning app that can be deployed to mainnet with minimal changes
- Tests for all contracts of the branch/mini-app
- README that contains setup instructions, and details of what each contract/function does

These sample projects will allow developers to not only have example smart contracts written in Clarity that they can reference and learn from but provide a starting point and example for how to structure a full-stack project with Clarinet and Stacks.js complete with a frontend and testing mechanisms.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Planned Hours: 70-80 
Total Grant Request: $7,000-$8,000

Milestone 1: NextJS/Tailwind and layout and basic instructions for cloning/installing/testing
Milestone 2: Connect/Disconnect wallet functionality, Localhost devnet faucet with instructions
Milestone 3: Writing your first smart contract: Counter dApp and contract
Milestone 4: NFT Minting dApp

This hours estimate includes not only direct development work but also testing and iterating based on community feedback to ensure we create the most useful open-source product possible.

This is an initial estimate for this grant only. We plan on continuing to add more functionality to this starter project to make it as useful for as many developers as possible and incrementally apply for additional grants as we do so.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

BowTiedYak [JungleYak on Github](https://github.com/jungleyak) - Primary developer. Software Engineer II. 1+ year in smart contract engineering on ETH. Three months smart contract engineering on STX.
Glasscloud [Glasscloud on Github](https://github.com/glasscloud) - Primary developer. Sr web 2 dev. Enterprise IT consultant. CTO @ TheopetraLabs
KenRogers [KenRogers on Github](https://github.com/kenrogers) - Mentoring and Project Direction. Developer Advocate @ Stacks Foundation (not included in grant payout)

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

Our largest hurdle will be with the Clarity smart contract development as we are both fairly new developing on the Stacks ecosystem. Kenny has graciously agreed to make himself available when we run into questions/issues we need help with. We will also leverage our connections with Jamil.btc, creator of STXNFT.com, as well as our connections in SyVita Guild as very capable Clarity developers that can help us work through some heavy lifting if needed.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

Based on comments and input from the community, boilerplates and scaffolding are desperately needed to help speed up developer productivity especially for functionality that is a part of just about every application (layout, wallet connect, first contract). We have access to plenty of supporting material and have already shown our aptitude by creating a very basic wallet connect app and are almost done building a faucet for devs to test their contracts on their localhost.

The feedback we have received is mostly that people are interested in having a project like this to understand how to work with stacks. We will share our plan and deliverable with the community via twitter announcements our personal, and TheopetraLabs account.

[@BowTiedYak on Twitter](https://twitter.com/BowtiedYak)
[@0xGlasscloud on Twitter](https://twitter.com/0xGlasscloud)
[@KenTheRogers on Twitter](https://twitter.com/KenTheRogers)
[@TheopetraLabs on Twitter](https://twitter.com/TheopetraLabs)

Previous projects and code commits can be found on our Github profiles.

BowTiedYak [[JungleYak on Github](https://github.com/jungleyak)]
Glasscloud [[Glasscloud on Github](https://github.com/glasscloud)]

The idea for this project originally arose during conversations with our developer team at Theopetra Labs. Theopetra is very bullish on Stacks and is committed to not only building our project on Stacks but becoming a pillar and source of education and tooling for developers in the Stacks community. Our vision for `stx-starter` is for it to become the go-to template kit for building projects and Stacks, and for it to continually evolve and improve based on popular, modern toolkits as well as allow Stacks developers to earn future grants and contribute to the ecosystem by creating their own branches and example apps.

**Comment by JakeBlockchain** [comment]
This is a great idea.
I've seen the idea of a smart contract database thrown at that would contain exactly this.
An array of starter templates that are audited for clean code and safety that people can build from.
Good luck on your grant.

**Comment by jhammond2012** [comment]
I'd love to discuss some ideas on this too!

**Comment by glasscloud** [comment]
@jhammond2012 absolutely! The initial boilerplate will include 2 basic dApps, but we want to be able to add other branches that include functionality you see in real world apps. Can drop me a line on twitter (@0xGlasslcoud) and we can link up!

**Comment by friedger** [comment]
Great proposal!

Related works is the app generator from 2019: https://github.com/stacks-network/blockstack-app-generator

**Comment by louiseivan** [comment]
LFG, theopatra bois. Boilerplates are essential to build a thriving dev community as the number 1 platform on Bitcoin and remain on that position. We need fundamentals that will make experimentation faster such as these boilerplates - reused over and over without change.

**Comment by will-at-stacks** [comment]
@glasscloud @JungleYak -

Thanks so much for this proposal.  We are approving it for $8k!  
Only catch - we are about to roll out the new Grants Dashboard.  This portal will have lots of functionality, one key component is an area call the Knowledge Base.  The intention is that all grantees will have to contribute to the KB as part of their grant.  The KB will include tutorials, solutions, and (you guessed it,) smart contract templates.
We want you to give this some thought and write another proposal (after you meet with us to discuss) for being an integral part of getting this off the ground!

One idea is to award grants to people for writing a template for each of these concepts - https://blog.chain.link/44-ways-to-enhance-your-smart-contract-with-chainlink/

This is a link to a similar platform so you can visualize it better. https://algorand.foundation/developers/developer-tutorials

As @louiseivan said - yes, lets LFG!

**Comment by glasscloud** [comment]
@will-at-stacks thank you 🙏

Would love to add value to the Stacks ecosystem wherever we can.

**Comment by JungleYak** [comment]
@will-at-stacks Thank you! We're very excited to bring this project to the Stacks space and help benefit developers.

Let us know when and how you want to meet:
`We want you to give this some thought and write another proposal (after you meet with us to discuss) for being an integral part of getting this off the ground!`

Thanks again!

**Comment by Melchizedek4ever** [comment]
This is an amazing initiative! Can't wait to see the boilerplates!

**Comment by will-at-stacks** [comment]
hey @JungleYak can you provide an update on this grant?  were you able to sign the contract and onboard ok?
cc: @jhammond2012

**Comment by JungleYak** [comment]
Hey @will-at-stacks! With how things changed because of us using our LLC's to sign the agreement, we actually never received a contract to sign. After we sent the LLC's documentation to Shakti he sent us our Stacks but we haven't signed a contract, or onboarded if there's more to it then just beginning to work. It should be known that Glasscloud and I have been working on this grant. Also re: the knowledge base, we sent you a discord message as we're unsure of next steps.

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
