### ISSUE TITLE
Blood Donating System on Stacks

### ISSUE THREAD

**Issue by ogasky** [stacksgov/Stacks-Grants#284]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

There is so much shortage of blood supply around the world which lead to high death rate, and adequate supply of blood can save more lives and sustain humanity. This project is to address this challenge by providing a decentralized blood donation platform that connect blood donor and recipients together within close proximity. Reimbursement for blood donation processes are paid in STXs and the platform runs on the Stacks Blockchain. This is an avenue for more people to have the Hiro wallet and also perform activities on Stacks. The idea is to add more value to the entire Stacks ecosystem.

**Project Overview**
What solution are you providing? Who will it serve?

This is a scalable core Stacks Blood Donation System for connecting blood donors and blood recipients together, as well as STXs been the major currency used for payment transactions. Blood donors and blood recipients sign into the platform, which will require them to create their STXs wallet by default. Thus having a community of blood donors that are connected to recipients when there is a request for blood donation. Also, this system will have hospitals and blood banks signed up as users and/or partners to the platform. 

Donors will be rewarded in STXs while the cost of processing one unit of Blood will be recovered in STXs via crypto donations from corporate organizations and individuals as well as reimbursement from blood recipient. Blood delivery is done when all parameters in the contract is achieved. These donated blood units will be relatively affordable, in the neighborhood of between 5 STX and 10 STX, so as to include gas fee and logistics. We intend to partner with Hospitals and Medical Laboratories as well as Blood Banks in Nigeria and beyond on this project.

All users of the platform will be taken through a guide (video/slides/chart) to ease their onboarding process into the platform.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The final deliverable is to connect blood donors and recipients in real time when there is a demand for blood units, and thereafter reimbursement for the process is paid via STXs to all parties involved. There is going to be a NGN to STX converter to aid accurate payment in STX.

Required Components:
- UI design
- Dashboards
- Wallets
- Geo Mapping
- Smart Contracts
- NGN to STX converter

Technical Spec:
- Clarinet
- Hiro
- Adobe illustrator
- Figma
- APIs
- Google Mapping
- Stacks
- Github

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

**Total Grant Request: 32,000 USD**

M1: = 12,000 USD for 4 weeks
- 3,000 USD = Workstation setup, domain, hosting, & workflow model design 
- 3000 USD = UI designs
- 2000 USD = Content Developer
- 4000 USD = Frontend 

M2: = 15,000 USD for 4 weeks.
- 5000 USD = Smart Contracts
- 8000 USD = Backend & APIs integration
- 2000 USD = Project Testing

M3: = 5000 USD for 2 weeks
- 2000 USD = Corporate Registration & Licenses
- 3000 USD = Publicity & Product Launch

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

- Kutaje J. Oghenevwaire, is a seasoned UI/UX designer with several projects done. For more details go to the link https://www.linkedin.com/in/kutaje-j-oghenevwaire/
- Gaddiel Ighota, is an experienced Web Developer with a demonstrated history of working in the information technology and services industry. Skilled in Python, Responsive Web Design, REST API, React, Node and Express framework. He is a good team player, bringing value and innovative ideas to the team he works with, and being open minded to accept and try out new ideas. See more details via the link https://www.linkedin.com/in/iamgaddiel/
- Kenneth Ijama, is a software developer with focus on JavaScript and just recently he was engaged by the Delta state government in Nigeria to facilitate a training program on coding for the youths in the state. See more of him via the link https://www.linkedin.com/in/webbravo/
- Onose Oghenevwogaga, is an entrepreneur and Founder of WittyHub, he is a blockchain community advocate and has done blockchain events in Nigeria, and some other African countries. More details via the link https://www.linkedin.com/in/onose-ogaga/

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

The major challenge to face is getting blood donors at very close proximity to the blood recipients, however this will be overcome through our incentivized packages for blood donors to encourage large number of signups on the platform. Also, we intend to carry out strong awareness campaigns.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

From our research and survey, many people want this project to come to reality because it is innovative, timely and life saving. Also we have gotten a Medical Laboratory and a Hub that are ready to work with us once this project is launched. Also, it is key to note that I am participating in the 2nd Clarity Universe Cohort and this will be very helpful on this project.

**Comment by tycho1212** [comment]
Innovative stuff! Are you in touch with any blood banks about this? I've worked with blood banks with the previous company I did to help them do digital marketing and they were always very slow and conservative. I think you'll need to get some buy in from them before embarking on this type of project

**Comment by ogasky** [comment]
@tycho1212 thank you for shearing the experience you got with some blood banks and your advice to us is highly appreciated. However, the answer to your question is **YES** , we have met with some hospitals and blood banks and some are ready to collaborate with us on this project. Also, there is a Medical Laboratory with Blood Bank facility in my city that have agreed to launch our project with them. We hope to have more in future, due to the strong marketing activities we will carry out once the project is done. Thank you.

**Comment by tycho1212** [comment]
Cool! It would be great to add a letter of intent or something like this to the supporting material section. If there's some way to get them to contribute some funds for extra buy in that would make this proposal stronger imo

**Comment by ogasky** [comment]
@tycho1212 we can get a letter of intent from the Medical Laboratory with Blood Bank in my city that have agreed to use our platform when we launched, which we will definitely be attached as you advised. And for the records, it is very key to note that we must understand that we are only approaching these hospitals and blood banks to use our platform for connecting blood donors to them and also for the reimbursements to paid in STXs, thereby performing their activities on our platform. Thus, asking them to contribute some funds to the development of the project has not been part of our discussion and it will be tough to ask them to do so, because an attempt to do that will totally discourage them from using our blood donation platform when it is fully launched. Once again, your comments and contributions are highly appreciated. Thank you.

**Comment by ogasky** [comment]
@louiseivan, thank you stating this, but I would like to make it known that I have been involved in some projects that involves saving lives & this is not my first. In the year 2007/2008 I was privileged to established a school sickbay, see the link https://web.facebook.com/media/set/?set=a.1510143114128&type=3 for more details. Also I am currently a Stacks enthusiasts and community developer. Thus, my motive for this project is to save lives and at the same time add value to the entire Stacks ecosystem. Thank you.

**Comment by ogasky** [comment]
@tycho1212 attached is the supporting letter you suggested we get from the medical organization for our project. Thank you.

![Proof of Partnership](https://user-images.githubusercontent.com/30671464/155621247-9c0e7a13-300c-4d51-bea8-c821caefbccc.JPG)

**Comment by will-at-stacks** [comment]
Hi @ogasky 

Thank you for submitting your proposal and patience as our team reviews it.

This project certainly addresses an innovative solution to a pressing challenge, as well as potentially further adaptation of Stacks. However, there are some concerns around the obstacles that can arise with partnerships and crypto donations. More importantly, using Stacks would add another layer that could present itself to be a complication or challenge rather than making it more accessible for people to obtain. Ultimately, this project is not within the scope of the grants criteria.

For these reasons, we have decided to pass on this grant. I realize that this rejection and the Chapter grant rejection - on top of the long review process could leave a bad taste in your mouth and possibly be discouraging.  I hope that is not the case.  We would like to meet with you and get a better idea of how we can work with you to find a grant proposal that will support your goals and work within the core mission of the Foundation.  Can you please grab a time slot on my calendar to meet?  I am out of the office next week.

https://calendly.com/will-at-stacks/30min

Thanks, 
Will

**Comment by ogasky** [comment]
@will-at-stacks , Duly acknowledged and I have scheduled the meeting with you for Monday 14/03/2022. Thank you.
