### ISSUE TITLE
Security audit for micro-stacks

### ISSUE THREAD

**Issue by aulneau** [stacksgov/Stacks-Grants#290]
> `micro-stacks`: Tiny libraries for building the next generation of Stacks apps.

I’m requesting this grant to pay for the cost of a security audit of [`micro-stacks`](https://github.com/fungible-systems/micro-stacks), to be completed in April by the agency [coinfabrik](https://www.coinfabrik.com/)

### Helpful links:
- [Github repo](https://github.com/fungible-systems/micro-stacks)
- [Documentation (WIP)](https://docs.micro-stacks.dev)
- [micro-stacks react libraries](https://github.com/fungible-systems/micro-stacks-react)
- [micro-stacks example projects](https://github.com/fungible-systems/micro-stacks-examples)

## Background

`micro-stacks` is a collection of typescript packages that enable apps to interact with the Stacks blockchain. These packages are different from `stacks.js` in that they have been completely re-organized, cleaned up, and refactored. Stacks.js has been the primary entry point for most developers building applications on Stacks, but very little progress has been made on new feature development or the technical debt surrounding the code.

I started `micro-stacks` as a nights and weekends project over a year ago, mainly because the kinds of app I wanted to build with `stacks.js` were not possible due to numerous reasons. The biggest reasons being around the dependencies that `stacks.js` uses for various cryptographic functions. Additionally, due to the way `stacks.js` is structured, it makes it very hard to use in modern bundlers like `vite` or `esbuild`.

`stacks.js` (previously known as `blockstack.js`) has years of use and maintenance behind it (which I have contributed towards), and it serves as a great foundation for building apps that use Gaia or interact with the Stacks Blockchain in some way. However, it has some (very well known and battle-tested) libraries that are huge in bundle-size which power its various cryptographic/blockchain functions. The most notable packages are: `elliptic`, `bitcoinjs-lib`, `bip39`, and `bn.js`.

`micro-stacks` improves upon this by removing all dependencies on other libraries aside from two (which have both been audited): 

- [noble-secp256k1](https://github.com/paulmillr/noble-secp256k1)
- [noble-hashes](https://github.com/fungible-systems/micro-stacks-react)

And vendors anything else that might be needed (vendoring means to bring in code rather than consume it as an external dependency).

Outside the libraries and dependencies that `stacks.js` has, there are long-standing, opinionated choices that have been made around how things should be used, mostly related to authentication and storage. I've spent years building ~~Block~~Stacks apps and `micro-stacks` is the culmination of my hopes and dreams when it comes to the future for building apps on the Stacks Blockchain.

## Project Overview

Much of the feature work has already been complete, and `micro-stacks` has complete coverage of the same API as `stacks.js`. It works as a 1-1 replacement at 1/10th the bundle size. New improvements and features are added within other packages such as [micro-stacks-react](https://github.com/fungible-systems/micro-stacks-react). I hope to build out integrations with frameworks like svelte and vue. The core packages ideally should not change very often. 

Currently the project is in `alpha` status, only because I wanted to get an audit before changing it. Much of the code comes from a fork of `stacks.js` [(MIT license)](https://github.com/hirosystems/stacks.js/blob/master/LICENSE), so in reality there is likely no greater security concerns around using micro-stacks compared to `stacks.js`. However, I do not know when or if `stacks.js` has ever been audited directly.

## Scope

I’ve already connected with the auditing firm and they are ready and willing to begin work in April, provided this grant is approved.

## Budget and Milestones

The cost of the audit was quoted to me at $21,000 for three weeks of time. Payment can be made in USDT or USDC, and is 50% at the beginning and 50% upon delivery of the report.

## Team

I am the primary maintainer of `micro-stacks`. I have worked in the Stacks ecosystem for years, previously working at Hiro, now co-founder of a Stacks based product studio, [Fungible Systems](https://fungible.systems). I also hope that `micro-stacks` becomes the community go-to for building stacks apps, and I'm very open and excited about anyone contributing to it. 

**Community and Supporting Materials**

I use `micro-stacks` in everything I build or work on, and I know there are other folks in the community who have also adopted the packages in place of `stacks.js`.

**Comment by FriendsFerdinand** [comment]
I've used `micro-stacks` in a small project before and it has saved multiple hours of work. This is a great contribution to the ecosystem.

**Comment by kenrogers** [comment]
Recently started experimenting with micro-stacks after speaking with Thomas about it. I am very excited about this project and to continue to both use and create educational content around it. It's a great contribution to the ecosystem and has the potential to be the go-to TypeScript Stacks SDK. Getting it audited is a crucial piece of bringing it out of alpha stage so the wider community can begin using it in their applications. Very much support this proposal.

**Comment by SyInvidia** [comment]
I LOVE LOVE LOVE MICRO-STACKS! Have used it in multiple projects and has been a huge time saver.

**Comment by ryanwaits** [comment]
I've personally onboarded several new devs to the stacks ecosystem, and `micro-stacks` is the library they end up choosing (and sticking with) every time! It's efficient and easy to reason about, which is why we're also using it to build out our StackerDAOs platform.

**Comment by friedger** [comment]
Auditing would help to merge this branch with more confidence https://github.com/friedger/stacks-swaps/tree/chore/micro-stacks

**Comment by will-at-stacks** [comment]
@aulneau clearly there is A LOT of support for this library. ;).  This grant is approved.  I will DM and you and Shakti so that he is aware this is needed in USDC / USDT.

**Comment by andresgalante** [comment]
Congrats @aulneau, this was fast and I am too late to add my vote here.

**Comment by aviculturist** [comment]
Congrats! micro-stacks is the best!

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
