### ISSUE TITLE
CityCoin Aid Initiative 

### ISSUE THREAD

**Issue by robtg4** [stacksgov/Stacks-Grants#292]
**Background**
[Currently, only 47 per cent of the global population](https://www.ilo.org/global/about-the-ilo/newsroom/news/WCMS_817653/lang--en/index.htm) are effectively covered by at least one social protection benefit, while 4.1 billion people (53 per cent) obtain no income security at all from their national social protection system. The problem with global social protection systems, such as humanitarian aid, COVID stimulus, SNAP (i.e., "Food Stamps), and disaster assistance is that the speed and cost of disbursing aid is expensive, slow, and not transparent. With the increasing recurrence of natural disasters and migration due to climate change, global demand for social protection has increased by 270 million people last year alone, and such a demand is projected to continually increase. To solve this, Emerging Impact has developed a blockchain-based product suite, named [Umoja Payment Suite](https://umoja.money/) to help automate social protection programs, enabling them to be completely digital, 100% transparent, and operate outside the context of the program itself so that beneficiaries can access other financial services longer-term. Our team was the first in the world to deploy a crypto-based humanitarian aid program with Oxfam International in 2019, and, since then, we have partnered with [Care](https://www.care.org/news-and-stories/press-releases/care-chooses-celo-as-first-blockchain-partner-in-latin-america/#:~:text=Emerging%20Impact%20(EI)%20empowers%20aid,%2C%20blockchain%20based%2C%20fintech%20tools.), [Hope for Haiti](https://www.globenewswire.com/news-release/2022/01/25/2372485/0/en/Coinbase-Announces-New-Philanthropic-Initiative-and-Partnership-With-Hope-for-Haiti-and-Emerging-Impact.html), Polish Action Humanitarian, World Vision, and Save the Children to implement both digital humanitarian aid and micro-finance programs across 5 countries. As the type of digital aid begins to expand (i.e., Stablecoins, Central Bank Digital Currencies (CBDCs), etc.) we seek to enable our product suite to support cross-chain assets so that our aid, government, and fin-tech partners can leverage a number of digital currencies in their programming based on their communal preference. 

Namely, [CityCoins](https://www.citycoins.co/about), a project that enables municipalities to create their own cryptocurrencies, is quickly being adopted by city-governments to fundraise their impact and innovation initiatives. CityCoins are tokens based on the Stacks blockchain, and like Stablecoins and CBDCs, they can be used to distribute digital cash assistance to eligible city residents. However, CityCoins bring a unique advantage to ensure hyper-local aid distribution AND targeted economic empowerment. Paired with the Umoja Payments Suite, city governments could distribute programatic social protection that can be flexibly used with merchants partnered within the program. Said merchants could be small or minority-owned business to ensure that city-based aid is spent to grow under-represented business communities, or span across multiple goods/services to ensure that aid recipients can spend their funds to receive a diverse set of goods/services spanning all their needs. 

**Thus, the purpose of this proposal is to integrate Stacks-based assets, namely CityCoins, into the Umoja Payments Suite to enable cities around the world to distribute digital, hyper-local and programmable digital cash assistance to the world's most underserved community members. Specifically, we are asking for grant funding to support the following initiatives: 

1. Integrate Stacks-based assets into the Umoja Payments Suite via the Umoja Money API 
2. Co-fund the MiamiCoin Aid pilot in (potential) collaboration with the City of Miami and the Miami Dolphin's Foundation using MiamiCoin as digital cash assistance to those in need (1,000 beneficiaries) via the Umoja Payments Suite

**About Emerging Impact**
[Emerging Impact](http://emergingimpact.com/) is a Coinbase and Mercy Corps Ventures-backed and minority-owned DeFi neobank built for the Global South. We partner with aid, government, and fin-tech agencies to provide inclusive, digital financial services to underserved communities around the world. We accomplish this using our [Umoja Payment Suite](https://umoja.money/), which was originally built on the Celo blockchain. Additionally, our Umoja Money API provides on/off-ramps between digital currencies, mobile money e-float, and emerging market fiat currencies to simplify the development of social finance applications in emerging markets. Our hope in FY22 is to evolve the API to support multi-chain assets, including those on the Stacks blockchain. 

**Project Overview**
The problem with American social protection systems, such as COVID stimulus, SNAP, and FEMA disaster assistance is that the speed and cost of disbursing aid is expensive, slow, and not transparent. To solve this, we’re proposing Miami become the first city in the world to distribute 100% transparent food insecurity aid to its underserved residents using MiamiCoin. The initial $280k pilot would be led by a partnership between the City of Miami, Emerging Impact (EI), and the Miami Dolphins Foundation and seek to feed 1,000 food insecure Miami residents with the vision of scaling to tens of thousands of residents within a year’s time. To distribute MiamiCoin to eligible, food insecure Miami residents, the pilot will use EI’s Umoja Payments Suite, which is a blockchain-based, aid distribution and monitoring platform that can distribute crypto-aid to anyone with a phone - even the unbanked.   

**Scope**
The nearest-term, biggest impact opportunity for piloting the distribution of MiamiCoin as a form of aid is to enable food-insecure Miami residents the ability to purchase organic food from local merchants through the [Miami Dolphins’ Foundation Food Relief Program](https://www.miamidolphins.com/community/foundation/food-relief-program). The initiative started on June 1, 2020 and provides a minimum of 1,000 meals prepared by Centerplate or local minority owned restaurants each day for up to a 12-month period to families in need in Miami Gardens and the surrounding communities. So far, the Food Relief Program has provided 462,228 meals across 101 restaurant partners, generating over $1.5M in revenue for minority owned businesses in the process. Currently the program feeds 1,384 residents a day, but in partnership with the MiamiCoin initiative, which leverages blockchain technology to scale cash assistance, we have the potential to scale that number to tens of thousands of residents a day with hundreds of restaurant partners.

The Miami Dolphins Foundation (MDF) and the City of Miami, stand to gain the following programmatic benefits  from the MiamiCoin initiative: 

- **100% Transparent Program Monitoring.** The City of Miami can show taxpayers where every cent goes within its digital cash assistance programing whereas MDF can show donors in real-time their impact on the community.
- **Increased Optionality for Aid Recipients.** Rather than being restricted to only merchants that accept EBT, aid recipients can use their digital cash assistance distributed in the form of MiamiCoin to purchase healthy and a diverse array of foods made by local, minority-owned merchants. By doing so, the City of Miami ensures both the economic empowerment of local, minority merchants, who increase their revenues from participating in such programs, and provide food insecure Miami residents with healthier, broader food options. 
- **Replicable & Easily Scalable.** Aid can be distributed remotely nearly instantaneously while maintaining transparency, particularly given the fact that merchants can be selectively added to the program across the city as more eligible residents are registered to receive aid. Any nonprofit program that provides flexible food cash assistance can introduce the usage of the Umoja Product Suite to quickly modernize their programing whilst using their CityCoin as the form of aid.  
- **Battle Tested.** Emerging Impact has deployed the world’s first crypto-based digital cash assistance programs with the world’s largest NGOs - including in places like Venezuela, Ecuador, Kenya, and Haiti with partners such as Oxfam International, Care, Polish Action Humanitarian, and Hope for Haiti, to name a few. These locales often have much lower digital and financial literacy, so EI’s products have been purpose-developed to be intuitive and simple to use. 
- **Extendable to Other Forms of Cash Assistance.** With the successful deployment of MiamiCoin Aid as a digital food assistance model, the City of Miami can easily extend which local businesses are able to accept MiamiCoin for other resources and services, such as healthcare and professional training. The transaction data from the growing program will let Miami officials better understand which services and products are most in need based on programmatic patterns. Such visibility will allow them to, eventually, be able to predict hyper-local needs and proactively respond to those needs independent of federal programming.
- **Financial Inclusion with Aid Programming.** By leveraging decentralized finance protocols, Umoja Wallets and Cards could allow aid recipients to even save their MiamiCoin and generate an APY 40,000 times higher than traditional banking (i.e., 4% - 8% APY vs. 0.01%), so that they may extend their benefits while they are not spending them. This would be the first time in history where aid recipients could save and generate an APY off their cash assistance to extend its use. 

To facilitate the pilot, it is crucial that we accomplish the following: 

1. Fundraise and/or allocate an amount of money to distribute in the pilot to aid recipients 
2. Bridge allocated MiamiCoin to be distributed to program beneficiaries from the Stacks blockchain to the Celo blockchain
3. Add MiamiCoin to the City of Miami’s Umoja Management Dashboard, which is a mass-payouts and program monitoring dashboard for crypto-aid programs  
4. Partner with local food merchants to sell their goods to MiamiCoin aid recipients 
5. Distribute MiamiCoin via the Umoja Payments Suite to Miami residents using the Umoja WhatsApp Wallet 
6. Allow MiamiCoin aid recipients to spend that MiamiCoin with selected, local merchants using the Umoja Commerce Wallet (a mobile merchant PoS application)

**Budget and Milestones**
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-326f27ce-7fff-9cfa-ce4a-a7db3f5ec908"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Jost,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">To enable the aforementioned steps, we will likely incur the following costs:&nbsp;</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Jost,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Table 2.0:</span><span style="font-size:10pt;font-family:Jost,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> Forecasted Pilot Expenses&nbsp;</span></p><div dir="ltr" style="margin-left:0pt;" align="left">

Expense | Description | Cost (USD) | Recipient
-- | -- | -- | --
MiamiCoin Aid Capital (i.e., Funds for Beneficiaries) | The amount of money that will go directly to aid program recipients to use toward purchasing organic food from local, minority merchants | $100,000.00 | Food Insecure Miami Residents
MiamiCoin Integration into Umoja Payments Suite | Adding MiamiCoin to the Umoja Payments Suite so that it can be distributed and monitored in MiamiCoin-based aid programs throughout the City of Miami | $50,000.00 | Emerging Impact
Pilot Operational Costs | Support miscellaneous costs to set up a pilot. This will likely go toward the Miami Dolphins Foundation (or be subsidized by them) for staffing costs incurred for managing the pilot on the ground | $30,000.00 | Miami Dolphins Foundation
Umoja Payments Suite Pilot | Cost of using the Umoja Payments Suite in the pilot and having direct support from Emerging Impact’s Advisory Services team that has decades of aid programming experience and innovated the world’s first crypto-aid program in 2019 | $100,000.00 | Emerging Impact
Total Cost | $280,000.00

</div></b>

Total Grant Request: $150,000

- M1 - $50,000: Integrate Stacks-based assets into the Umoja Payments Suite via the Umoja Money API 
- M2 - $100,000: Finalize Partnership with the City of Miami to Deploy MiamiCoins as social protection 

**Team**
Emerging Impact consists of 12 team members spanned across 6 countries who are fluent in over 10 languages. We have a collective work experience spanning Goldman Sachs, Cisco Systems, ConsenSys, Amazon, the World Food Programme, and Oxfam International. Our team has 20 years of combined blockchain expertise, 10 years of social sector expertise, and 15 years of product design and development expertise. You can lear more about our founders below: 

- [Robby Greenfield](https://www.linkedin.com/in/robtg4/)
- [Sandra Hart](https://www.linkedin.com/in/sandra-uwantege-hart-862b5986/)
- [Jonathan Lewis](https://www.linkedin.com/in/umiworkshop/) 

**Risks**
The main risk associated with this project is ensuring that the aid provided in CityCoin to beneficiaries is over-collateralized, due to the volatile price of CityCoins. We will be compensating for this risk by developing a smart contract in which CityCoins being used as aid will be deposited at a 1.5:1 collateralization ratio. 

**Community and Supporting Materials**
Our team has deployed digital cash assistance programs in Haiti, Venezuela, Kenya, Ecuador, and Vanuatu. We have learned a great deal as to how to provide tools to underserved communities in a responsible manner. You can read more about our apporach here: https://celo.org/papers/future-proof-exec

**Comment by JakeBlockchain** [comment]
Very interesting proposal and idea Rob!
Looks promising and can bring alot of value to people through CityCoins.

A few questions I'd love some clarity on.
1) It looks like the main goal is to allow a liquid digital asset like CityCoins to be used to help those in need.
The focus looks like MiamiCoin initially, which makes sense. 
Is their any expectation of supporting other CityCoins (NYC, or ATX)?
And what would the process be of staying updated as more CityCoins come online?

2) The M2 marked in the proposal looks like the 4th item in the expense report.
Is there a cost for cities to use the Umoja Payments Suite in an ongoing basis?

Thanks.
Good luck with the grant!

**Comment by will-at-stacks** [comment]
@robtg4 -

Nice chatting just now.  Just to summarize next steps:
- You will be sending a shared document so we can all collaborate on possible revisions to your application
- You will be speaking with the City of Miami about their ability to shoulder the M2 beneficiary costs
- You are speaking with the Celo Foundation about possibilities of a co-grant
- I will set up a call for next Friday and include some of our devs and you will include some of your technical staff so we can try to find the most efficient way to do a Stacks native integration.

Please let me know if I missed anything.

Best,
Will

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
