### ISSUE TITLE
Grant request to write about Stacks ecosystem

### ISSUE THREAD

**Issue by Melchizedek4ever** [stacksgov/Stacks-Grants#293]
**Background**
What problems do you aim to solve? How does it serve the mission of a user-owned internet?

The lack of awareness by the mainstream surrounding how web3 works and how it facilitates the invention of totally new concepts such as DAOs and decentralised finance, for example. The idea that a farmer in a remote village using only a cellphone can invest in a new financial system that allows him or her to receive the transaction fees that would have normally gone to a bank still blows my mind!

**Project Overview**
What solution are you providing? Who will it serve?
A series of weekly articles informing and educating both technical and non-technical audiences about Stacks's ecosystem and vision. Target audience will include technical consumers like developers, Tech- and cryptoenthusiasts, as well as the non-technical and un-initiated mainstream audience.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The project will include research and output of a 1500-word to 2000-word article per week and distribution across social media channels and other sites (medium.com, hacker news, Publish0x, etc.). 

This writing project will take the blogging format. What has worked best for me is creating trend-based articles around a given topic and publishing them on my blog and other tech-related websites and social-media channels. But I believe flexibility is very important in creating content; adapting to time-sensitive trends and the needs of the audience is key. Should the need arise, I'm more than able to adopt a different format or write in a specific form or style.

Every month of successfully created and distributed content should be considered a success.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request Estimate: 
Initial Mobilization:
                                             Laptop: 1300
                                             Phone:  500
                           Total Mobilization: 1800
Monthly Expenditure:
                                       Hub Space: 300
                                 Transportation: 400
                                            Internet: 250
                       Research and writing: 2000 (based on 4 articles per month)
                                  Total Monthly: 2950

Total Grant Request: 4750

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 
       I am currently the only member of the team. I have been blogging on a personal level since 2017 and freelance writing since 2020 and have been managing just fine. But I am more than happy to collaborate with other writers and community members in sharing ideas and just working together in general. My website is www.4alltech.com
      I am not a formally trained writer and I would greatly appreciate the support and input of the more professional writers in the community.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
A possible but highly unlikely threat to the project could be physical insecurity, which affects some parts of my country but I live in a relatively stable city and as long as I have the space, time, and an internet connection, nothing should really interfere with my writing. But then the flexibility that blockchain gives us to circumvent such issues is just one of the many reasons I love the technology!

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan with the community over time and as the final deliverable?

I have written about the Stacks network and Clarity language along with other tech subjects at my blog 4alltech.com
I plan to distribute this content across my blog and relavant tech sites as well as social media channels.

**Comment by will-at-stacks** [comment]
Hi @Melchizedek4ever 

Thank you for your proposal and for your patience as we review it.

We are very much in favor of supporting projects that will raise awareness and education on Stacks. However, the proposal does not seem to be within the parameters of the grants program for various reasons:

1)There are no clear milestones or outlines of the topics that are in queue.

2)The focus is to fund on infrastructure and how it can be scalable without one single person maintaining it.

3)There are expenses that are out of the scope of work like laptop, transportation, phone internet, etc.

4)It is important to have a defined scope of work with timeline and milestones. Monthly request of expenditure is not feasible with the Grants Program.

For these reasons, we have decided to reject your grant. We encourage you to continue developing ideas and would be happy to review them again. 

Thank you, 
Will

**Comment by Melchizedek4ever** [comment]
Thanks for getting back to me with this feedback.

I have more understanding of the parameters now. But what do you mean
by "fund on infrastructure"?

Thanks<div id="DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br />
<table style="border-top: 1px solid #D3D4DE;">
	<tr>
        <td style="width: 55px; padding-top: 13px;"><a
href="http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank"><img
src="https://ipmcdn.avast.com/images/icons/icon-envelope-tick-green-avg-v1.png"
alt="" width="46" height="29" style="width: 46px; height: 29px;"
/></a></td>
		<td style="width: 470px; padding-top: 12px; color: #41424e;
font-size: 13px; font-family: Arial, Helvetica, sans-serif;
line-height: 18px;">Virus-free. <a
href="http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank" style="color: #4453ea;">www.avg.com</a>
		</td>
	</tr>
</table><a href="#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1"
height="1"></a></div>
