### ISSUE TITLE
Web3 Network Infrastructure Bridge

### ISSUE THREAD

**Issue by E8Stacks** [stacksgov/Stacks-Grants#296]
Web3 Network Infrastructure Bridge

Stacks applications and start-ups desperately need access to utility in the real world. 

**Background**

While DeFi and NFTs expand across and grow the web3 community, a continued conversation among developers and consumers alike is how to make Bitcoin productive with web3 utilities and applications that impact everyday consumers.

When looking at projects like Helium, it’s clear there’s demand for programmable, decentralized network infrastructure that can work natively with the Bitcoin ecosystem. 

Growing the Bitcoin economy and realizing the dream of crypto civilization means bridging the Stacks decentralized apps and smart contracts ecosystem with the network infrastructure that is the oxygen for millions of consumers’ digital lives.

We propose building a web3 network infrastructure bridge. The bridge between the layer 1 blockchain and physical network infrastructure will bring essential new utility to the Stacks network. 

**Project Overview**

Like Helium, our project will enable developer access to a distributed network of hotspots, creating a portal for everyday web3 applications. But, unlike Helium, we will enable rich, high bandwidth, low latency applications and can still support IoT and smart city applications.

When users with BTC, STX, etc., interact with an E8-enabled hotspot, a captive portal pop-up allows them to connect their wallet. 

Once connected, this can provide a single, secure sign-on across the E8 hotspot network. Second, the portal can enable automated, localized rewards programs.

- Ex. 1 - network priority based on loyalty
- Ex. 2 - speed boosts based on holdings

Third, the network infrastructure bridge and a captive portal will provide a distribution mechanism for Dapps in the ecosystem.

- Ex. 1 - Learn-to-Earn programs in partnership with community organizations 
- Ex. 2 - DeFi opportunities for everyday citizens.

Like AOL had to teach people about the internet using the browser, we believe this safe portal can open the web3 universe to millions of everyday consumers.

**Scope**

What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The project's primary goal is to add additional utility to end-users via the Stacks Network. The utility of the web3 bridge is based on direct physical network integration via standards-based network authentication (RADIUS) and wireless technology. 

The result of integrating the Hiro wallet, and standards-based networking is the ability to interact with the internet (and private networks) directly. The utility to the Stacks network is making stacks more relevant to the everyday use of the internet. And allows additional functionality to be based around Stacks.

1.	Technical requirements for participating hotspot owners
a.	Level system
b.	Upgrade incentives
c.	Streamlined setup wizard
2.	Web3 Network Infrastructure Bridge backend
a.	RADIUS Integrated Authentication System
b.	Legacy Network to Web3 Network Bridge
c.	Management Portal
3.	Captive Portal frontend 
a.	UI Designed Around Average User
b.	Normalizing STX/CityCoin adoption
i.	Coinbase-esque UI approach
4.	Rewards/Bounties Program: 
a.	Network functionality-driven rewards
i.	SMB Incentives for Participation
ii.	Further Access Incentives
b.	Bounties for growing hotspot participants
i.	Treasure Hunt

**Budget and Milestones**

Total Grant Request: $150,000

- **M1:** Technical requirements document a WiFi infrastructure owner can read, understand, and opt-into with existing network infrastructure. Will include level system and upgrade incentives. ($15,000)
**M2:** Bare-bone, end-to-end smart contract system accepting wallet connection as authentication to the network. ($50,000)
- **M3:** Add to the bare-bone system the ability to read the connected wallet to enable extra network functionality. ($35,000)
- **M4:** Onboarding and successful deployment of the web3 network infrastructure bridge on the hotspot. ($20,000)
- **M5:** A consumer successfully connects their wallet through the portal front end UI. ($30,000)

**Team**

Our team has previously participated in ETH, AVAX, and DASH ecosystems. Our entire team has been early blockchain adopters and participants in the ETH ecosystem with smart contracts. We are excited to participate in building new tools for STX and CityCoins. 

The team previously built systems helping Fortune 500s and companies like Brinks streamline and secure their operations. We’ve co-founded, led, and helped build the #1 and #3 fixed wireless providers in the United States. E8 is currently expanding nationwide, offering end-users fiber and wireless internet services. We are passionate about bringing blockchain new utilities.

- Kevin Grace
- Jonathan Van
- Sebastian Ornstein

Unique Perspectives:

- SaaS
- Wireless
- Legal
- Founders

**Risks**

The dependency for the web3 network infrastructure bridge includes working with RADIUS and other legacy network authentication systems. Each system will take some time to bridge; however, there are multiple systems to complete the full scope. Our team has extensive experience working closely with these systems and vendors.

**Community and Supporting Materials**

Our team has been building consumer and enterprise networks for the better part of two decades, reaching millions of consumers across the US and globally. So it’s an exciting opportunity to bring together that experience with the BTC/STX ecosystem to bring forth a user-owned internet starting with existing infrastructure and going beyond this project.

As we gather support for this project, we have support from key members of the Stacks ecosystem. In addition, we will be participating in the Stacks Accelerator - CityCoin track to bring this project to Miami, NYC, and other cities.

Our team will share our roadmap using the best available channels and roll out deliverables as we meet milestones to relevant stakeholders.

**Comment by castig** [comment]
Super excited for this! Please keep us updated on your progress. I'd be happy to beta test if it's useful.

**Comment by E8Stacks** [comment]
> Super excited for this! Please keep us updated on your progress. I'd be happy to beta test if it's useful.

Thank you! Look forward to it.

**Comment by AdamDavidJones** [comment]
I am so looking forward to this! This team is like the Chicago Bulls in the 90s!! I strongly believe this will be a wildly successful company that delivers high-speed internet to locations that desperately need it. This project could help alleviate intergenerational poverty in underserved communities and lay the infrastructure for Web 3 smart cities. 
Speaking to them and learning their vision has been very exciting.

**Comment by E8Stacks** [comment]
> I am so looking forward to this! This team is like the Chicago Bulls in the 90s!! I strongly believe this will be a wildly successful company that delivers high-speed internet to locations that desperately need it. This project could help alleviate intergenerational poverty in underserved communities and lay the infrastructure for Web 3 smart cities. Speaking to them and learning their vision has been very exciting.

Thank you! This is a big part of our mission.

**Comment by will-at-stacks** [comment]
Hi @E8Stacks -

Thanks very much for presenting on Friday.  This is a really solid application.  Before approving it, can you please speak to your level of confidence that the City of Miami will be open to engaging you and/or your plan for navigating that situation?  If you have any kind of a statement from a city official you can submit to ensure they are going to be willing participants that would be ideal.  

Thanks, 
Will

**Comment by GAV07** [comment]
>
> Hi @E8Stacks -
> 
> Thanks very much for presenting on Friday. This is a really solid application. Before approving it, can you please speak to your level of confidence that the City of Miami will be open to engaging you and/or your plan for navigating that situation? If you have any kind of a statement from a city official you can submit to ensure they are going to be willing participants that would be ideal.
> 
> Thanks, Will

Hello Will this is [Erick Gavin](https://www.linkedin.com/in/egavin07/), Executive Director for Venture Miami an office within the city of Miami. I have been discussing with Johnathan and the Element 8 different approaches for leveraging Web3 Technology for infrastructure improvements as their are communities in our city that need better access. I cannot make legally binding commitments at this juncture but I am excited to work with the team to determine what community partnerships and additional resources would be necessary to make this impactful for the Miami community.

**Comment by E8Stacks** [comment]
> Hi @E8Stacks -
> 
> Thanks very much for presenting on Friday. This is a really solid application. Before approving it, can you please speak to your level of confidence that the City of Miami will be open to engaging you and/or your plan for navigating that situation? If you have any kind of a statement from a city official you can submit to ensure they are going to be willing participants that would be ideal.
> 
> Thanks, Will

Thank you Will -- Erick commented above to offer context of the work so far. We are excited about the progress and opportunity to help Miami. What we see right now is a strong need, and a very collaborative community surrounding CityCoin and Venture Miami.

**Comment by will-at-stacks** [comment]
@E8Stacks -  Thank you for all your work on this application.  This is a really exciting project and use case.  We are going to approve this grant.  The only caveat is that I would like you to set up a call with me as you conclude M1 so we can continue to stay in the loop regarding how things are being received with the City of Miami before we disburse M2 funds.  

@GAV07 - Thank you for commenting and for supporting such innovative work at the civic level!  Miami is a model to the rest of the country!  We look forward to engaging you throughout this process.

Best, 
Will

**Comment by E8Stacks** [comment]
Thank you @will-at-stacks - we look forward to it.
