### ISSUE TITLE
Hybrid Virtual/In-person Stacks Conference

### ISSUE THREAD

**Issue by NRL-ashlie** [stacksgov/Stacks-Grants#298]
### Throw a Hybrid Virtual/In-Person Stacks Conference

**[Watch the Trailer for our last conference!](https://youtu.be/qF2j4gSstmo)**

**World-class Event Production** 
REIMAGINE is a semi-monthly virtual blockchain event brought to you by MouseBelt Blockchain Accelerator. Our mission is to empower newbies and veterans alike with the knowledge they need to build a decentralized future. We have successfully created a forum for education for academic, industry, and enterprise communities that serves as the industry standard for virtual blockchain events. Now, our goal is to use our platform to tell the world about the Stacks network and all the community has to offer.  

**Our Success**
We have worked with some of the biggest names in crypto, including over 500 industry partners and universities, for a total of over 400 hours of curated content. Our viewers include more than 50,000 attendees from across 20 countries who have watched 2M minutes (33,000 hours) of content. Notable speakers include industry leaders such as Min Kim, Roger Ver, Michael Saylor, Mark Yusko, Erik Voorhees, Sam Bankman-Fried and many more.

**The Numbers:**  
25M+ twitter impressions
400K+ live viewers and attendees
50K+ event responses
Accelerating Stacks adoption in 2022

### How We’ll Do It
**Invite the Community**
- Stacks miners and operators 
- Stacks ecosystem projects
- Critical influencers from the ecosystem  
**Host panels & discussions**
- Core members from the Stacks team  
- Technical Partners and Contributors 
- Complimentary projects, supporters, and partners  
**Deliver the Highest Quality Content** 
- All the tools and resources needed for top production value
- Dedicated production crew for the project
- Not just another zoom call… we’ll have video editors, audio technicians, production grade equipment, cameras/mics, lighting 
**Workshops: Products, Features and Demos** 
- Collaborate with Stacks community partners to produce workshops such as...
- “How to” events. Ie. How to launch a smart contract, etc.
- Technical tutorials & product demos -  Wallets, DEXs, Infrastructure plus oth 8 others 
- Stacks token giveaways 
### We want to hear from you!
**What else do you feel is critical for this Stacks conference?**
Our team will work directly with community members regarding their input and suggestions for the success of this event. This is an event for Stacks by Stacks! If funded, our goal is to have the community join the conversation, guiding the direction of the event and having a say on what content we highlight. Help us spread the word about the Stacks ecosystem!

### The Team Behind This Project
**MouseBelt** 
MouseBelt Blockchain Accelerator is an ecosystem building the future of blockchain innovation and education. We’re constantly working to improve the blockchain industry through our full-service accelerator, engineering services, media, and educational programs. Some notable projects include:
- Accelerator portfolio boasts successful participants valued at over $100M
- [REIMAGINE Virtual Conference](https://www.ri2020.io/) - Over the last 2 years have produced 11 of the highest quality virtual conferences in the world 
- [COINS](https://www.youtube.com/channel/UCLfJQI2quidWaKpUyDsY04w) - First-of-its-kind, Hollywood-level documentary series telling the story of the tidal wave caused by crypto and blockchain, the ways it has upended the global financial system and beyond. Receiving over 700k views, this series interviews some of the top leaders in crypto: Erik Voorhees, Sam Bankman Fried, Paolo Ardoino, Raoul Pal, Meltem Demirors, Bill Barhydt and more.
- [MouseBelt University](https://mousebelt.university/) - a network of students from over 100 universities in 24 countries. Includes the Blockchain Education Alliance, a network of industry leaders supporting blockchain education and research at universities and beyond….

### Community Title Sponsorship - Stacks  
**Marketing the Stacks brand:**
- Sponsor wipes - “This segment brought to you by…” before, during, and after segments
- During Interviews - “Sponsored by Stacks shown 2-4x per interview
- Video Commercials - 15-30 sec ads between segments 
- Host endorsement - Hosts talk about Stacks, Stacks partner projects, Stacks community, updates, programs, campaigns.
**Maximum Distribution**
- All content immediately posted on Youtube channel for replay.
- The Stacks Foundation, Stacks participants, partners may reuse the content for further marketability  
- 24/7, 365, Globally - Youtube, Website, blogs, PR, Newsletter, conference participants
- International Visibility - borderless, airing in multiple countries/regions, in all time zones
**Partner Reach**				
- We’ve established a robust network of ecosystem partners, businesses, conference participants promoting the event resulting in exponential growth on a global scale

### Roadmap 
**Pre-Production Schedule**

- 8 weeks out - Coordinate with conference participants, community, formulate the direction of the conference. Booking and scheduling logistics.
- 6 weeks out - Begin production on event banners, websites, marketing assets, animation graphics and guest artwork, send first newsletter to community
- 5 weeks out - Speaker booking begins, traveling, set up at location, on-set logistics
- 4 weeks out - Start interviewing over 2 week period, second newsletter to community with speaker names announcement 
- 2 weeks out - Editing all event interviews, social media pre-marketing deployment strategy activated, targeting all participants via twitter
- 1 week out - Continued social media deployment and marketing campaign, 3rd newsletter to community with schedule, guest announcements, giveaways, and updates 
- 3 days out - Reminder newsletter, rollout of final speaker announcements, conference agenda/schedule shared publicly
**Launch** 
- 0- Conference live stream kicks off, aggressive social media drip campaign activated, newsletter and twitter announcement to kick off event, all live stream links shared to community, partners, speakers to access content
- +1 day - prepare for day 2 live stream, send out ICYMI emails, next day speaker announcements, conference announcements, day speaker agenda 
- +2 days - repeat
**Post Conference**
- Thank you note sent via newsletter 
- Post videos on youtube
- (ICYMI) - Drip campaign of promo clips of interviews

<span style="font-size:16pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Costs</span></p><div dir="ltr" style="margin-left:0pt;" align="left">

REIMAGINE 2021 v12 |  
-- | --
Budget Report |  
Graphic Designer | Cost
TOTAL SPEND: | $3,442.00
Video Production | Cost
TOTAL SPEND: | $7,200.00
Online Advertising | Cost
TOTAL SPEND: | $1000.00
SaaS & Streaming Infrastructure | Cost
TOTAL SPEND: | $1,825.45
Staff Related | Cost
TOTAL SPEND: | $39,700.00
Press Release Distribution | Cost
TOTAL SPEND: | $277.00
Hospitality, Venue, Travel, Lodging | Cost
TOTAL SPEND: | $6935.00
  |  
RI2021 V12 Production Related Expenses | $61,029.45

</div><h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /></span>

### Funding Requested for this Proposal

**Requesting 25,000 USDC The conference team will cover remaining costs.** 

**Payment Schedule** 

- To kick off the conference logistics: 12,500k USDC
- Execute conference deliverables/expenses/roadmap plans, last payment: 12,500k USDC 

### Contact Us
Adam Leon: Reimgaine@mousebelt.com
[Reimagine Conference.pdf](https://github.com/stacksgov/Stacks-Grants/files/8157939/Reimagine.Conference.pdf)
>

**Comment by will-at-stacks** [comment]
Hi @NRL-ashlie  - 

Thanks for the proposal.  Sounds like a really exciting opportunity.  I am going to reject this grant as a collaboration like this would be approved through a different budget and with feedback from other Stacks Foundation staff members.  Could you please email me a summary version of your proposal at will@stacks.org so that I can forward it to our Events and Community Growth persons?

Thanks,
Will
