### ISSUE TITLE
STACKS DEGENS GAMING UNIVERSE

### ISSUE THREAD

**Issue by BowTiedDeployer** [stacksgov/Stacks-Grants#299]
STACKS DEGENS GAMING UNIVERSE

**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

Related to gaming in general, a problem we identified is players who enjoy gaming do not typically have the opportunity to own a piece or share in the success of the games they enjoy. They may buy the game and receive the privilege of playing the game, but they do not profit from its popularity and success like the company who made it, unless they were also shareholders. Players may be able to buy in-game skins or items, but they typically may not sell those back or trade to other players. And if the game goes away, so does their in-game items.

Another problem we identified is that pay-to-play games, the standard for gaming now, require the trading of time and money for that privilege of playing. Games cost money, money costs time. The point of a game is to compete for the time of players. Players time costs money, yet players are not currently being compensated for their time or monetarily rewarded for their success at it. The best they can do to monetize their time playing the game is through streaming, getting sponsorships, or competing in tournaments with a high skill barrier of entry.

To a very large and growing part of the population, gaming is a popular way of unwinding. However, it is nearly impossible for the average gamer to make a living off playing a game. If players were able to make a living off playing a game, they would have more time to play the game. Since it is in the interest of game makers to have players play their game as much as possible, it is equally in the interest of game makers to provide an opportunity for players to make a living playing their game.

We aspire to create a gaming universe based on NFT collections (built on Stacks) that players may compete in and trustlessly earn rewards with our in-game currency. The mining mechanism for our in-game currency will be Proof of Transfer, where it is built on Stacks and secured by Bitcoin. Proof of Transfer enables a unique monetization model that rewards Stackers while also bootstrapping the Stacks Degens team with funds for fulfilling our Roadmap. With no pre-mine and halvings programmed in similar to CityCoin, the protocol ensures supply is digitally scarce and no one entity in control of issuance.

Players may be able to own NFTs to compete in our games and tournaments and earn rewards, or trade their NFTs. The game is the platform, a player's NFT is their key to playing the game, and the in-game currency is the cost for competing and earning. We want to afford players the ability to play the game as much as possible. But if a player no longer wishes to play the game, they may simply sell their NFT and the rest of their in-game currency to someone else. These benefits are a positive improvement from the status of Pay-to-Play games and in alignment with the mission of a user owned internet.

**Project Overview**
What solution are you providing? Who will it serve?

Stacks Degens will be providing a Play-to-Earn Gaming Universe that is built on Stacks and secured by Bitcoin that players and communities can join, compete, and earn. We plan to do this effectively by both expanding our user base, integrating other communities into the game, building value for the community, and innovating for the best possible gaming experience.

Currently, Stacks Degens has three NFT collections which may be used to compete in our web-based racing game. Miami Degens, our first collection, features 420 unique skeletons racing in Lambos, and New York Degens, our second collection, features 420 unique aliens racing in Bentley's. We recently integrated StacksPunks, one of the first NFT collection and marketplace on Stacks, into our game. StacksPunk holders may customize a race-able StacksPunk in our Degenerator, where they will receive their StacksPunk in a personalized Ferrari that they may race in the game.

We believe that integrating popular NFT communities like the StacksPunks into our game not only aligns with our objective of expanding our user base, but it also solves another major problem. Right now, NFT projects are having tremendous difficulty building use cases for their collection outside the blockchain. Our gaming universe creates a way for NFT communities to have off-chain utility by giving their collection the ability to join, compete against other communities or amongst themselves, and earn. In addition, we have plans to become interoperable with the Ethereum blockchain by creating a bridge that allows for the integration of the Degenimals NFT collection into our gaming universe.

As for making for the best possible gaming experience, we have outlined on our Roadmap tasks in which, once completed, will have a positive impact on the gaming experience. Coming up very soon, we will be releasing four new maps in which to race, as well as completing our tournament revamp. The tournament revamp featured a game health update that improves the scalability of the racing game and improvements to the tournament structure to make it more competitive.

In the near future, we will be launching our in-game currency which will serve as the basis for distributing player rewards. Players may already connect their wallet and compete in tournaments if they own the appropriate NFT. Soon, they will be able to commit our in-game currency to a rewards pool and record runs in a tournament. The best times at the end of the tournament will earn the most and the worst times will earn the least, and all the rewards will be distributed trustlessly out of the rewards pool at the closing of the tournament.

These are examples we have for ultimately serving our community, the Stacks community, and gamers-at-large. There are plans to continue innovating on what is possible inside our game. We will always be looking to create new game modes and earning opportunities for players. We have plans to incorporate public and private lobbies to allow for a more individual-driven or private gaming experience, real-time multiplayer racing for a more competition-oriented event, and a mobile application so players may take the game on the go. You may see more in our roadmap:

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The game we are building is a based on the pseudo-3D concept. It uses geometrics and trigonometry to distort shapes in such way that it creates the impression of a multi-dimension universe. Unlike some other racing games this approaches the style met in the golden era of gaming where you are not taking part in open-world action, but focus on multiple session/races to score a better time. The retro look has 2D textures and code generated polygons as it's main interface between the user and the universe.

The game is web based. This is so the Hiro wallet web extension may be connected to the game to play the game. The Hiro wallet is the default wallet for engaging with dapps built on the Stacks blockchain. It lets the end users select the NFT they want to compete by querying multiple APIs to see which are of the given user. This is necessary for the use of the Degenerator as well, which allows StacksPunk holders the ability to claim a customized race-able StacksPunk if it is detected that their wallet holds the original StacksPunk.

The in-game currency deployed on the Stacks blockchain and will utilize the Proof of Transfer mining mechanism to issue block rewards of the currency. There will be an Early Mining Incentive, where the block rewards are initially high for three months, then drop and rewards go to halving every four years. This is to create digital scarcity similar to Bitcoin. At the end of every Stacking Cycle, the STX commited to mining our in-game currency is 90% distributed to Stackers of our coin, and 10% goes to supporting Stacks Degens as we continue to integrate other NFT communities into the game and expand the gaming universe itself. The mining proceeds that goes to supporting Stacks Degens is 3x less than the amount that is donated to cities from the CityCoin protocol, another very popular project built on Stacks that utilizes the Proof of Transfer mining mechanism.

Stacks Degens will be accountable for the success of our in-game currency. We will do what is necessary to facilitate the infrastructure for trustlessly mining, stacking, earning, and swapping it. This will include working with partners, such as the Syvita Mining, for setting up user-friendly dashboards for mining and stacking. We will also establish Liquidity Pools to allow for swapping in or out of our currency via Stacks or coins from partner communities, and push for its listing on major exchanges.

The reward pools for tournaments, games, and lobbies will be created via Smart Contracts coded on Clarity programming language. When deployed, it will allow for the acceptance from players of our in-game currency and the trustless distribution of rewards at the end of tournaments and games.

We will measure success of our gaming universe through the growth of our community and active players. We can get an idea to this based on Twitter followers, Discord members, and daily, weekly, and monthly active players. We may measure the success of our coin based on it's mining and stacking interest, as well the amount of volume going towards competing for rewards. These will be based on metrics the team has determined most useful for measuring performance, in which better performance translates into growing success.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $50,000

Three of the five team members are working full-time on Stacks Degens, and expenses for hosting the game, improving our operations, and boosting our Discord are coming out of the pockets of the team. With some funding, they may better be able to support themselves while working towards making the project self-sustainable with our unique monetization models.

With 10% of mining proceeds from the in-game currency protocol going to Stacks Degens to continue to build the game and expand our player base, we always be provided funds for fulfulling our promises to the community. With 10% of commits for competing in the game going to Stacks Degens as well (and 90% into the Reward Pool for that tournament or game). The in-game currency received by the team may be Stacked, further earning the team more in mining proceeds to work with while also removing supply and creating more scarcity.

For this monetization model to account for anything, it will require having the resources ready for quickly establishing a strong gaming experience with a growing player community. We are requesting initial funding to allow us to increase visibility on our project, establish the infrastructure necessary to support our in-game currency, and invest in a strong gaming experience so that the project may take on a life of its own. Received funds would immediately go towards performing a game engine update(1000 hours), enabling real-time multiplayer racing (1000 hours), and developing a mobile game application (1000 hours).

There will also be instances in which we are required to integrate a vetted NFT community into our gaming universe. This will require labor by our artist and utilization of photoshop tools and licenses. Initial funding will allow him to recreate unique NFTs from partner NFT communities into the game seamlessly and efficiently so we may move as quickly as possible at expanding our player base.

Additionally, we would like to pursue our PlayEarnLearn Initiative as soon as possible and with the support and resources of the Stacks Foundation. We would like to develop an Interactive Stacks Masterclass to help onboard individuals into the Stacks ecosystem so they may start participating in web3 secured by Bitcoin. We would also like to develop a thorough tutorial and walkthrough to help break Stackers into our GameFi via Stacks Degens. To go one step further, we would also like to establish a Degen Bootcamp in which we will help teach and mentor community members on how to become skilled at Clarity development and game development so they may one day contribute to Stacks Degens or contribute to the Stacks ecosystem in general. This initiative will require funding, collaboration, and possible expansion of the team, in which funding could serve as pivotal.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work.

BowTiedSirJonathan.btc is the founder of the Miami Degens, project which has transitioned into the Stacks Degens. Key abilities are marketing, communication and recognising talent in people. This has played an important role into maintaining a healthy workflow between the team members, keeping everyone satisfied and focused on the project. Besides having spent over 5 years into various charitable communities in a leadership role, he has made his living through e-commerce. Now, all his focus is put into this project, quitting all of the previous just to see the success of Stacks Degens happen.

BowTiedDeployer.btc is the deployer of website, game, contracts and integrations that includes the Stacks Degens Gaming Universe. His background includes but is not limited to two times Gold Medalist National Computer Science Olympics and one time Silver Medalist, multiple hackathons run, first place in one creating in a team of 4 in less than 24 hours a multiplayer 3d school universe where people could walk, write, teach and learn using white boards and interact with others using VR headsets. Also first place in a national contest regarding keeping the earth healthy by creating a real time multiplayer game card game with references to pollution and how to combat it to help bringing awareness in that regard. Always liked writing code and building stuff, especially web based since it was the most flexible option and the easiest to get people to use. Started with ethereum and writing smart contracts there and web dapps to interact with them, found it quite interesting how the blockchain works . Later on found about stacks and clarity and decided to max out on combining his various areas of expertise in developing a project that can have real impact.

Vali is the head of design inside the Stacks Degens Gaming Universe. He has over 8 years of experience in the visuals field of work starting from photo to video producing, all the way to vector and game design. He knows his way around most of the Adobe creative software and has been using them for over 5 years. He has general coding skills enough to shape the art inside our project.

BowTiedFellow.btc is an active user in the Stacks Ecosystem and extremely bullish on Bitcoin, Stacks, and Proof of Transfer. He is a tremendous believer in web3 and believes it will be built on Bitcoin via Stacks. He has recently transitioned from a leadership role in the United States Army to now doing SaaS sales full-time while also helping build projects on Stacks in his free time. He is a respected advisor to the team and helps brainstorm the direction of the project and keeps the team organized and focused.

Andrei Alexandrescu more recently came on board because of his extremely thorough technical skills and industry experience. He has an MS in Computer Science from the University of Oxford and has worked as a Forward Deployed Software Engineer at Palantir Technologies. Currently, he serves as a Software Engineer Manager and Senior Frontend Developer at Mosaic.tech. He has experience in front-end development, software, and research and demonstrates proficiency in java, react.js, angularJS, redux.js, NgRx, and more. 

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
There is a risk the market rejects our in-game currency. We have partnered with Syvita Mining to help facilitate the mining and stacking, and will be creating Liquidity Pools on DeFi protocols to enable the swapping in and out. We will be constantly building out the game to provide more opportunities to earn, providing more utility for our in-game currency. Worst case scenario, we maintain the game infrastructure and begin facilitating the use of other coins as rewards.

It is of utmost importance that our game allows all players a provably equal and fair chance to earn rewards. Thus, security will be of utmost priority. Because of the need to perform a transaction before recording a run, we hope this may limit bots from being able to pollute the game. Such an instance could deter players from competing because it would ruin the element of fairness. However, this could be resolved by creating or utilizing an API to block any connected third-party software.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

**Comment by BowTiedDeployer** [comment]
Pitchdeck: https://1drv.ms/p/s!AhZ60a1hO7Z0lUaxOSXjwVpOzTQK?e=iAQgb1
Website: https://stacksdegens.com/

Twitter: https://twitter.com/StacksDegens
Discord: https://discord.gg/ZwDXRgHJ
Medium: https://medium.com/@stacksdegens

Contract for MIA Degens: https://explorer.stacks.co/txid/SP1SCEXE6PMGPAC6B4N5P2MDKX8V4GF9QDE1FNNGJ.miami-degens?chain=mainnet
Contract for NYC Degens: https://explorer.stacks.co/txid/SP1SCEXE6PMGPAC6B4N5P2MDKX8V4GF9QDE1FNNGJ.nyc-degens?chain=mainnet
Contract for SDGU StacksPunks: https://explorer.stacks.co/txid/SP1SCEXE6PMGPAC6B4N5P2MDKX8V4GF9QDE1FNNGJ.SDGU-stackspunks?chain=mainnet

**Comment by will-at-stacks** [comment]
@BowTiedDeployer I am going to close this issue since you and your team are submitting a revised proposal per our DM on Twitter.  Thanks, Will
