### ISSUE TITLE
PlayNFT: A cross-chain NFT utility marketplace

### ISSUE THREAD

**Issue by EnigmaCEO** [stacksgov/Stacks-Grants#303]
**Background**
"I just bought a NFT... now what?"

PlayNFT is a marketplace for NFT Utility created by blockchain game content. This utility is the next evolution of the NFT ecosystem. We are solving the problems of blockchain segmentation and the lack of NFT utility.

**Project Overview**
PlayNFT connects NFT holders and NFT Collection creators to in-game content of blockchain games. Game developers can use this platform to create content for NFT holders from any of the supported blockchains.

**Scope**
PlayNFT is an open source Web3 platform built using Javascript/HTML with Node.JS backend. We have successfully integrated multiple blockchains which adds more value to the platform. Full support for NFTs and Dapps for the Stacks blockchain is our development goal.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $25,000

M1: Stacks blockchain and NFT integration. (480 Hours)

M2: Testing utility payment and cross chain functionality. (180 Hours)

**Team**
Xavier D. Moore - 20+ years experience in the game industry. 3 years designing blockchain games with P2E economies.
Irving Malcolm - 10+ years of game development experience. 2 years of integrating blockchain mechanics.
Chris Hildebrand - Art / Marketing veteran with over 20 years of published titles.
Juan Barba - Backend developer with experience developing blockchain APIs.

**Risks**
No obstacles anticipated. The documentation is very clear and the metadata aligns with other formats that have been successfully integrated before.

**Community and Supporting Materials**
Our project is open source and currently live at: https://www.playnft.io/
We will be working with the most popular NFT projects on the blockchain to ensure that they are aware of our utility content.

[PlayNFT_Pitchdeck.pdf](https://github.com/stacksgov/Stacks-Grants/files/8200261/PlayNFT_Pitchdeck.pdf)

**Comment by will-at-stacks** [comment]
@EnigmaCEO Hello and thank you for the grant application.  Unfortunately, we are going to reject this application in its current form.  We felt the website you linked to had a lot of dead end links and a lot of the content appeared to be dormant, which gives us pause.  Beyond that the scope and milestones lacked detail in regards to your objectives and the value proposition for the broader Stacks community.  

If you are able to revise your proposal and elaborate on your objectives and why you feel this grant would yield new and novel technology for the Stacks community - AND indicated strong interest from potential NFT partners on stacks, we would reconsider the request.  If you could also provide links to code repos that include code commits highlighting your contributions to other blockchain communities that would also be very helpful.

Thanks,
Will

**Comment by will-at-stacks** [comment]
Hi @EnigmaCEO we look forward to reviewing your new application.  We recently moved over to our own Grants Dashboard.  Please fill out an application at grants.stacks.org.

Thanks
Will
