### ISSUE TITLE
Bitcoin Cafe Dakar 

### ISSUE THREAD

**Issue by darkwaynes1** [stacksgov/Stacks-Grants#304]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

- To create a discussion space for those who wish to discover or exchange about Bitcoin 
- To raise awareness and knowledge among young people
- To allow the population to emancipate itself through the tools of the blockchain
- Develop the local ecosystem around Bitcoin

**Project Overview**
What solution are you providing? Who will it serve?

A platform for exchange and an inclusive environment conducive to discussion and without social, gender or origin discrimination.

1st step: (Bitcoin Cafe Dakar) Organization of a free event open to all. In the form of an aperitif barbecue. Distribution of solar phone battery charger, tee-shirt, stickers and giveaway of 20stx per participant. For the first event we want to reach 30 participants.

2nd step : Bitcoin Hackaton, develop a solution to a local problem

3rd step : Stacks Senegal Chapter, develop the stacks community in Senegal

The first two steps allow us to identify and measure the interest of the population in Bitcoin.
The last step is to develop the synergy of users and technologies through Bitcoin

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

- We will collect feedback from participants.
- Take pictures that will be published on twitter.
- Open a Discord server.

The number of new members on the server will measure the impact of the event.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $8600

The organization of the project will take 55 hours. The event itself will be in the format of an afterwork.

Searching for a venue: 4h
Setting up the venue (location, furnitures, bbq...): 8 hours ($1500)
Search for local service providers (food & beverages): 4h ($1200)
Animation (bbq, dj, barman, hostess and host) : (6h) ($600)
Communication of the event (flyers, advertising..): 10h ($500)
Promotion (goodies) of the event: 8h ($3800)
Post-event Integration of participants: 12h
Restoration of the place: 4h 
Team fees: ($1000)

Duration of the event : 6h

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

The team is composed of Waynes and Remy.
Waynes : An entrepreneur who settled in Senegal to help the local population develop a more rational agriculture. 
He designs biotechnology that protects people from health and ecosystem risks.
He is the CEO of MNA and MNA Technology.
https://mnatrading.com
https://twitter.com/darkwaynes
https://twitter.com/bitcoindakar

Remy : Who settled in Senegal to help inclusion of Women throughout formation to be able to work and generate revenues.
He's a Radio and Social Media Journalist at DW French for Africa service. Interested in News, Innovation and Digitalisation. 
https://dakaroiseries.wordpress.com/ma-bio/
https://twitter.com/AmonRemy?s=20
https://t.co/3GePiESYxJ

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

The fear of some people to see a project succeed and develop can lead to wanting to sabotage or prevent the project.
In Africa unfortunately this is frequent, so it will be necessary to be able to control the event from A-Z.

We will be 100% involved in all aspects of the organization and logistics.
Fortunately the fact that we live in Dakar today allows us to know some aspects. Our network will help us to avoid this kind of problem.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

Waynes has already participated in the organization of festivals where his company has sponsored the River Blues, a festival organized by the Senegalese artist Baaba Maal, who participated in the soundtrack of Black Panther.
Remy is a trained journalist which will be very useful for the communication of the event.

We are active in the stacks community, and have invested in several nft projects, including: indigo, CrashPunks, BitcoinMonkeys, Megapont, Tigerforce, StacksPops...
Concerning the technical part we count on members of the community such as @axopoa.btc

**Comment by mardi00** [comment]
Very nice initiative! Thank you @darkwaynes1

**Comment by will-at-stacks** [comment]
Hi @darkwaynes1 - 

Thank you for the grant proposal.  We are going to reject this specific proposal, but not because we don't support your efforts.  Rather than approve this one off event, we want to be sure to empower you to be supported in a more sustainable / long-term manner.  Would it be possible for you to send me an email at will@stacks.org so that I have your contact?  We have a new Community Growth lead starting in a couple of weeks and I want to be sure you interact with him as this sort of project is more directly aligned with initiatives he will be leading.

Hope to hear from you soon.

Best,
Will
