### ISSUE TITLE
CityCoiner - Media Outlet - Covering all things CityCoins

### ISSUE THREAD

**Issue by kurtgrela** [stacksgov/Stacks-Grants#306]
**Background**

CityCoins are captivating attention from Miami to New York City to Austin.  There are other U.S. cities and international cities that can’t even be mentioned yet.  The Stacks Accelerator has a track for new projects and applications looking to build on CityCoins.

CityCoiner is a media outlet covering all things CityCoins.  We host a weekly Twitter space covering recent CityCoins developments.  In the last 30 days, we had almost 50,000 impressions on our Twitter account!  Almost 8,000 profile clicks!  That’s with only 254 followers and 21 tweets!  We are grateful to all the people who retweet and share our tweets.

<img width="1267" alt="Screen Shot 2022-03-08 at 7 47 15 PM" src="https://user-images.githubusercontent.com/6758348/157374698-af8e3f5a-32f3-4da9-9e2f-eaf4794b80f9.png">

In the coming weeks / months, we expect New York City to accept the multi-million dollar STX wallet, Austin to launch its CityCoin, the Stacks Accelerator to support several (or many) apps building on CityCoins.  Then there are other cities looking to launch their own CityCoins.  This is going to be a very busy year, and CityCoiner wants to cover all things CityCoins.

**Project Overview**

CityCoiner will engage with the CityCoins community, people within the local governments, CityCoin builders, the Stacks community, and the general Twitter community.  CityCoiners plan to amplify the message and content for City leaders and city dwellers.  We will create new content that builds or further expands on popular content or frequently asked questions, such as onboarding info for new cities, advocacy, mining, stacking, claiming rewards, new projects, and new applications for CityCoins.

**Scope**

**Website build out** - right now, the site is the bare bones:  https://www.citycoiner.com/  Looking to add blogging, landing pages, and a newsletter.  Copywriting would help as well.

**Content editors, reviewers** - we rely on community members to review and edit content before blog posts are posted to the website and Twitter.

**Content writers** - write blog posts on CityCoin related projects and developments.

**Twitter Space hosts** - Facilitate the Twitter space with introduction, thoughtful questions, expand on engaging concepts, and manage the room and participants. Everyone loves a great Twitter space experience!

**Repurpose and highlight content** from our Twitter spaces - Take the audio, import it into descript, have community members highlight the key quotes and content. Edit the text, so it makes sense.  Then create audiograms and quote cards for Twitter.

**Video editors** - we plan to host several livestreams and CityCoins generates video content.  We seek to take clips from the videos and highlight key parts to create evergreen content.  Assistance with timestamps to create YouTube video chapters.

**Graphic design / meme creator** for blog posts and YouTube thumbnail - every content piece usually has a graphic.  CityCoiner will rely on a graphic artist or several to create graphics.

**Discord / Twitter Community Manager** - assign a person to interact and engage with our community.  As of now, we only use Twitter two days a week:  on Tuesday and Wednesday to promote the Wednesday evening Twitter Space.

**Conference Stipends** - $250/day to offset traveling expenses (transportation/food/hotel/Airbnb) - sponsor CityCoiner representatives to travel and attend pre-approved CityCoins related conference events.  $5,000 (20 days).  Stacks in Miami, SXSW in Austin.

Success is measured by Twitter analytics.  As of now, almost 50,000 impressions in 30 days. WIth so many possible developments in the CityCoins pipeline, CityCoiner would be well placed and funded to make an impact around the globe.

**Budget and Milestones**

M1 - CityCoiner Seed Grant - $24,500

Total Grant Request: 

M1: $24,500

**Team**

**Jake Blockchain** - Jake is the host of the popular Built on Bitcoin podcast https://www.builtonbitcoin.xyz/.  His inquisitive mind and popular podcast highlights all the progress that the Stacks ecosystem is accomplishing on a weekly basis.  He founded CityCoiner with a simple tweet inviting others to join him and create content together for the CItyCoins community.

**Kurt Grela** - Founder of 101 Blockchain St.  Livestreamer.  Content creator and Twitter space host. https://twitter.com/kurtgrela 

**Diego Mey** - Interactive Designer, Branding, Web and Digital Marketing. Founder of CityPacks. Working at the intersection of art and technology.  https://twitter.com/DiegoMey 

**Altmom** - Community lead, public speaker, convention representative, content editor and creator, educator, IRL brand ambassador.  https://twitter.com/AltMomTrades 

**James** - Content creator and reviewer

**Logan** - Content creator and reviewer

**Risks**

The CityCoiner project is a community run news outlet. Our biggest obstacles are learning how to coordinate DAO members in this new, decentralized way of working to consistently put out good content that pushes CityCoins forward.

We intend to meet weekly to make sure we are staying on mission.

**Community and Supporting Materials**

https://twitter.com/citycoiner 
https://www.citycoiner.com/
The Built on Bitcoin podcast shares some content creation skills that we will be using in the CityCoiner.
https://www.builtonbitcoin.xyz/

Our deliverables will be shared out to the public on an ongoing basis.

The community can follow our work as we release content on a daily basis.

**Comment by will-at-stacks** [comment]
@JakeBlockchain please resubmit this application under your name since @kurtgrela will be stepping back from this project.  Could you also consider reducing the budget for this grant and revise the scope so that it covers one full iteration of the core process.  My understanding is that that would be:

- (1) Twitter Space and (1) Livestream
- (1) sample of repurposed content (video edited and graphic design)
- (1) blog

Seeing these deliverables will be a huge help before considering a larger grant.  If you could also note any contributions from the CityCoin team in terms of money / feedback / support that would be a huge help.  We want to make sure your efforts align with theirs.  

Thanks, 
Will
