### ISSUE TITLE
Stacks dapp public web-accessible landing page

### ISSUE THREAD

**Issue by paradigma-cl** [stacksgov/Stacks-Grants#308]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?
Stacks decentralized applications (dapps) are very good to keep its data private and/or share among other dapps as it can use the Stacks Decentralized Domain Names using the BNS smart contract. But how can we make some of the information stored in a user's account be web-accessible publicly to any user? Initially, the idea was to have a decentralized explorer for it, but that project was discontinued for the moment.  Is there another way to do it?

**Project Overview**
What solution are you providing? Who will it serve?
At Paradigma we developed a prototype solution that gives a Stacks Dapp the possibility to share a selected set of data publicly to any user, or specifically for a user or service and show it in a more personalized way (Each user could have their own layout and design). This capability should be very useful for the Stacks Dapps.  We see that we need to refactor the code, develop some new functionality, retest it, package it and create the documentation in order to have other developing teams include this capacity.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
There are four components of the solution.  
1. The definition of the dapp's data that needs to be publicly web accessible.
2. Domain and subdomain name routing service.
3. Accessing the public dapp's data.
4. Data layout designer.
The deliverable will be the code necessary for each component to integrate this capacity to a dapp, an example on how to do it, and documentation.  This project will be a success if at least one development team manages to integrate this functionality.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: STX 7000

M1. Definition of the publicly web-accessible dapp's data.  12 hrs
M2. How to set up the domain and subdomain name routing service. 15 hrs
M3. Procedure to access the public dapp's data. 15 hrs
M4. A simple design tool to define the data layout. 50 hrs
Each milestone has its own documentation plus general documentation. 30 hrs

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 
The developers are Jose Fontirroig (https://jfontirroig.xck.app) and Phillip Roe Smithson (https://phillip.xck.app) that both have experience of developing Stacks Dapps since 2018.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
Changes on the Stacks dapps development specifications could invalidate the way we initially built this solution.  It will require more development to include the changes.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan with the community over time and as the final deliverable?
We have developed https://xck.app and forked development of https:// domains.paradigma.global
We have received positive feedback from potential clients and other development teams, and that motivated us to make another effort to refactor, package and document it for the benefit of the Stacks community.
We will publish the code as open-source with the documentation under our github account.

**Comment by friedger** [comment]
Do you have an example for app data to clarify the proposal?

**Comment by paradigma-cl** [comment]
> Do you have an example for app data to clarify the proposal?

The app data that one would like to be publicly accessible should be defined by the app developers, then also the dapp user could specifiy is a field is accessible or not.  For ie.  a personal profile of the dapp, including links, or pointers to special contents.  Like https://phillip.xck.app

**Comment by will-at-stacks** [comment]
Hi @paradigma-cl ,
Could you email me and we can set up a call to discuss your application?  will@stacks.org

**Comment by will-at-stacks** [comment]
Hi @paradigma-cl please use this link to schedule a meeting to discuss your application.  Thanks, Will

https://calendly.com/d/cq8-hj7-xq2/25-minute-meeting

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
