### ISSUE TITLE
Life After Debt

### ISSUE THREAD

**Issue by revival-inc** [stacksgov/Stacks-Grants#313]
**Background**
[Revival ](revivalfunds.com)is solving the $15T consumer debt problem. Our platform allows borrowers to buy out and eliminate their debt at the same pennies on the dollar rate that it gets sold to debt collections agencies. To date, we have helped thousands of borrowers eliminate more than $1.8M worth of debt.

**Project Overview**
We are requesting a grant to build Defi consolidation loans using Stacks into our platform. When we work with borrowers, we are typically only able to solve one of the many lines of debt they have tanking their credit score. It isn't uncommon to find a handful more of identical loans with incredibly predatory interest rates. 

We want to offer borrowers loans where we ask borrowers for 25-50% as collateral, and while they pay back the remainder of the loan, the borrower is able to yield interest from staking that they keep once payments are completed. Through the use of Stacks, those yields can grow to net the borrowers more than they originally owed when they took out the loan, not to mention getting the bad marks off of their credit as well as helping them through not charging any interest to the borrower.

This is a product that could benefit anyone living in the United States but we think it would be most helpful to focus on people who have received Payday loans, as they are often the most harmed.

**Scope**
We are planning to launch our mobile app in Q3 of this year. We are currently building our web platform using Node, Python and ReactJS. We plan to launch the mobile app using React Native which will help for a speedy entry to both the Apple and Google Play stores. 

[Our prototype](https://www.figma.com/proto/7MGFm5BG9No8DJMMsKGMh2/Revival-Visitors?page-id=0%3A1&node-id=2%3A401&viewport=241%2C48%2C0.38&scaling=min-zoom&starting-point-node-id=2%3A270) gives a good look into how seamless our mobile experience will look.

We will measure success both by the amount of debt we are able to eliminate and how many people we can get out of predatory loans that are still harming their credit scores.

**Budget and Milestones**
Budget Breakdown: 
$50K in Debt Cancellation
$50K Product Build

Total Grant Request: $100K (Hours: 50)
- Front End Interface Development Web App (Hours: 10) _April 15th_
- Getting Stacks Integrated (Hours: 20) _April 31st_
- Building Proper Pathways to Track Borrower Staked Capital, Earned Interest, Monthly Payments, Proper Payout Total (Hours: 10hrs) _May 15th_
- Front End Interface Development Mobile App (Hours: 10) _June 15th_
- Mobile App Launch _June 30th_

**Team**
**Daryl Holman Jr.**
Daryl designed the websites for two of the leading organizations in the fight against student debt and later served as a US Senate panelist on the topic. He has also led conversations on the need for broad-based debt cancellation with everyone up to the US Secretary of Education. At Revival, he leads design efforts and helps investors understand why the debt industry needs change and why we're the ones who can get it done.

**Greg Renfro**
Greg has over 5 years of experience in medical billing and recently got into web development through a coding bootcamp. At Revival, he uses his unique understanding of billing industry and compliance to build ethical software that helps consumers rather than the traditional impact medical bills have had on the American public.

**Henry Veasley III**
Henry has been working in the debt industry for over 20 years. He's seen every aspect of the business from calling borrowers in a cubical to selling portfolios to lenders as well as buying them from some of our country's largest lenders. At Revival, he predicts portfolio return value, advises on licensing, and most importantly makes sure we have a never-ending pipeline of portfolios so we can help more borrowers find their way out of debt.

**Risks**
Our biggest operational risk is servicing borrowers outside of the 16 states where we're currently able to work. Right now we're currently expanding and working to bring our offerings to new states as soon as we can.

**Community and Supporting Materials**
We currently have code commits on our Github relative to the new web platform which launches in two weeks. We have been putting out feelers for consolidations for two months with a lot of people eager for our launch. We have also been pursuing debt facilities from startup lenders to increase our ability to release borrowers from the predatory lenders they have been working with. 

At Revival, we believe in building in public and we think transparency is especially important because of how harmful the credit and debt industry has been, historically. To combat this, we will detail on Medium the results from this project as well as share it with the press to help expand understanding of the financial system and how Defi can help fix it.

**Comment by will-at-stacks** [comment]
Hi @revival-inc - Thanks for the application.  This is a really promising use case for crypto/defi.  Can you please clarify the following:

- What is entailed in the $50k for debt cancellation?
- Please expand on how this project leverages the Stacks network, what aspects of that work could be considered 'new and novel', and what components of your project will be open-source.

Thanks, Will

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
