### ISSUE TITLE
Real Estate Developments into Web3

### ISSUE THREAD

**Issue by reinaldobtc** [stacksgov/Stacks-Grants#315]
**Background**
What problems do you aim to solve? How does it serve the mission of a user-owned internet?

Real estate developers underestimate the power of neighbourhood opposition to a development approval. Failure to get community support may delay or denied the approval of a  project, costing thousands and even millions of dollars to developers and municipalities. 

Even if the developer proposes something that zoning regulation allows, neighbours, can put enough pressure on the city council and **kill a project, if they feel it will not add value to the community**, regardless of the laws are on the developer's side.

Developers and Cities must approach projects fully aware of the importance of neighbourhood participation. 
But this comes with another problem, Developers and Cities fail to reach and attract participation,  maybe it is because of their lack of trust in the process or just because they don't want to waste their time,  but what we do know is that we are going to change this with a web3 ecosystem that will attract and reward participation, **so participants can capture the value that they help to create.**

**Project Overview**
What solution are you providing? Who will it serve?

We are creating the first built to earn ecosystem that adds value to the real estate developer, the city and their citizens in the physical and digital space. So, that is why we plan to launch our genesis PFP collection named BUILD**OGS**, the OGs of Real Estate developments in web3. 

A community of builders that will become the co-developers of real projects by having access to proactively participate in public and private RFPs (Request for Proposals) in an easy to use and interact web3 ecosystem that rewards participation and give back ownership of digital assets created during the RFP process to its community.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
The immediate Goal to kickstart our project are as follow: 

1. Landing Page, Social Media and Digital Marketing Ecosystem Implementation
2. Develop and Mint Buildogs PFP Collection
3. Develop RFP web3 MVP management software Ecosystem
4. Source and close strategic partnership with  Real Estate Developers 
5. Source and close strategic alliances with  Cities and CRA's

Success will be measured throughout the entire process, from the Digital Marketing Ecosystem there will be metrics to measure succes like Traffic to landing, Lead Conversion rate and Mint Conversion rate, we are going to target a community of web 3 architects, artist, creators and real estate oriented communities.

For the MVP web3 ecosystem success will be measured by the **participation rate growht** from the Buidlogs community into  the RFPs opportunities that we are going to present.

Real Estate Developers **acquisition rate growth** will be one of the most important metrics to measure success, each developer using our platform will commit a percentage of their development budget back to the BUILDOGS community. We are Real Estate Developers and we are going to be among the first Real Estate Developers to work with the Buildogs community.

Cities within City Coins' acquisition rate will be as well a key important metric,  we want to plug into the city's RFP process to help them attract participation from City Coiners while supporting and incentivising City Coin mining and stacking. 

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $75,000

M1: Budget $25,000
       Duration: 4 Weeks
       Starting date: April 1st

- PFP Illustration design and accessories
- Website & Landing page and digital Marketing Ecosystem Strategy  & implementation 
-  Discord channel
- API Mint interface integration with Stacks.
- PR and VR pop up activation participation in Miami events, related to Stacks, Prop Tech, and NFTs.

M2: Budget $20,000  (Once Mint is above 60%)
       Duration: 4 Weeks 
       Starting date: May 1st, 2022

- UX/UI design implementation for the MVP RFP management tool
- Always-ON Marketing Campaign
- Real Estate Developers lead capture strategy and implementation

M3: Budget $30,000  (Once UX/UI is at 80% completion)
       Duration: 4 to 6 Weeks
       Starting date: June 1st, 2022

- Web3 development and integration for the MVP.  We plan to work with a tech partner [(ArchiDAO)](https://archidao.io/) to work on the web3 deployment and testing for the MVP.

M4: Budget $0 
       Starting date: July 15 th, 2022

**Release of the first RFP to the Buildogs Community**: We plan to release to the  Buildogs Community our AWACATE Project. A 25 Mixed used project, that we will built in Wynwood Miami,  currently under permitting. We have invested over $500,000 for the land acquisition and soft costs. The building is already on a social metaverse environment in which the Buildogs Community will have access to interact in real-time with other members and proactively participate to add additional value to the project. The digital asset of this building is going to be minted and ownership will be given to Buildogs.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

[Reinaldo Padron.](https://www.linkedin.com/in/padronreinaldo/)
Real Estate developer and technology-driven entrepreneur with over 12 years of experience in the industry. Reinaldo recently build a team that participated and won a public RFP to develop a $34M project that will break ground in May 2022.  Reinaldo is pushing the boundaries to innovate with technology to change the way we create, interact and invest in real estate developments. He has also invested and created the [Awacate Project](https://dpzj0rbjoo1.typeform.com/to/daTdKtw0?utm_source=grant) which is going to be the first one to be released to the Buildogs Community.  

[You can read more about Reinaldo in this Podcast Interview](http://placemakingpodcast.com/from-venezuela-to-miami-learning-real-estate-from-the-university-of-life-with-reinaldo-padron-ep-46/)

[Isaac Peckel](https://www.linkedin.com/in/isaac-peckel-6128199/)
Isaac is a Real Estate developer and Investor, in south Florida with over 14 years of experience. He Founded [MIR Developments](https://mirdevelopments.com/) a developer in Orlando that has completed over 1,000 residential units in the past 4 years and [The Worx Orlando](https://theworxorlando.com/), a workspace brand operator rapidly growing in the Orlando Market

**Are there skills sets you are missing that you are seeking from the community?**
At the moment we are missing our lead tech engineer. However, we are going to be working closely with tools and API available from other projects from the community members to complete the work described on this grant, for the PFP collection and MVP.

 We are in conversations with ArchiDAO which is a Web3 first Architecture Design Technologist developing solutions and experiences that transcend physical-digital boundaries that will not only help us support our technical needs but will also bring incredible talent to the Buildogs community.

We are confident that once our PFP collection has successfully minted, we will have the traction and the support within our own community to get the lead tech person on board that shares our values, vision and passion.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

Unsucesull mint. If we don't reach above 60% of the mint before May 1st we will revisit our digital marketing strategy and make the necessary changes to reach a the right audience. 

Run out of Cashflow for the web3 MVP implementation. In the event that the web3 deployment for the MVP requires additional capital, we will source it and invest whatever more is required.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

We plan to create a blog to post updates of our project as well as a Discord Channel to be in direct contact with the community members and partners.

In a previous project related to a real estate development, we did an approach to the community in order to get their feedback and participation because we were at risk of getting the project denied by the city. That survey helped us to understand the voice of the local community and get the project moving forward.  We will make this type of participation more active, interactive and rewarded with Buildogs [Survey report](https://admin.typeform.com/form/IucRTkWc/reports)

**Comment by will-at-stacks** [comment]
Hi @reinaldobtc  - 

Thanks for the application.  While this is a really cool project and one that particularly resonates with me, we don't feel it is best supported by a grant.  We try to keep grants limited to funding primarily open-source work and work that can have an immediate & widespread positive impact on the Stacks community.  Not to say that your project won't accomplish these things, but deliverables laid out in your milestones appear to be highly proprietary to your endeavors.  Additionally, we like to work with first time grantees on smaller grants before considering a grant of this size.  Please give this feedback some thought.  If you are able to abstract out the components of your project that can be open-sourced and resubmit that idea as a new application we would certainly be open to working with you on it.  We hope this feedback is clear and gives you some ideas on how to proceed.  

Thanks, 
Will

**Comment by reinaldobtc** [comment]
Thank you for the feedback Will. It does make sense. I will work on it and come back with abstracts from the project that will be open-sourced and more aligned with the grant mission.
