### ISSUE TITLE
Making NFTs more accessible

### ISSUE THREAD

**Issue by hh8899** [stacksgov/Stacks-Grants#318]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

NFTs have begun to break out. Conversations can be overheard in local launderettes between fathers and sons marvelling at the cost of pixel art on Open Sea, while waiting for their clothes to dry. Artists, grinding beans as baristas are wondering if they can supplement their income with NFTs - not really knowing what that means. Everyone is talking about NFTs and many want to be involved but don’t know where to begin.

It has become almost a cliché but this project is actually on the intersection between art and technology. We intend to capture the imagination of the local community in Brighton, UK, through a combined physical / digital popup art exhibition. Digital artworks will be presented in a unique encasement: handmade to both display and enrich the experience of the digital art and bridge it into the physical realm. Customers can buy NFTs at the event using various payment methods including fiat or at their leisure using an online marketplace.

The key innovations in the project are:
1. enable sales of NFTs for bitcoin via OpenNode integration
2. enable sales of NFTs for GBP (fiat) via SquarePay integration
3. help crypto newcomers set up xverse or Hiro web wallets in order to receive their NFT
4. display Stacks NFTs in a physical gallery space

This project builds on the work delivered in a previous application - [stacksmate](https://github.com/stacksgov/Stacks-Grants/issues/137) - by extending the infrastructure developed there to integrate OpenNode / SquarePay payment flows with on-chain minting and transfer of NFTs via a custodial wallet. 

To make this happen we are asking for a small grant which we will match fund. The grant will help us cover the upfront and fixed costs of the project and enable us to reach out to the non-crypto community of Brighton and Hove.

**Project Overview**
What solution are you providing? Who will it serve?

The project has two tracks: web based platform and physical art exhibition. 

Because the project builds on previous grants the scope of the technology track is limited to an integration between the payment flows and smart contract integration - the software is open source and available via npm repository. This involves minor changes to our latest NFT contract that has been delivered a [generalised fungible token marketplace](https://twitter.com/radicleart/status/1502661427827458049) on Stacks.

On the other track we intend to rent a small gallery space in the heart of Brighton to stage a popup exhibition over a 2 day window in May or June. The artwork will be displayed in custom made frames for maximum engagement. We will focus on engagement with the general public - helping them set up and understand a Hiro or Xverse wallet and send them a free NFT.

All artwork on display will be available to buy using:
1. Fiat currency (GBP)
2. Bitcoin (btc) or bitcoin via the lightning network (lbtc)
3. STX or any fungible asset e.g. xBTC

with the NFT being transferred automatically to the users address.

The artwork will also be available online after the exhibition closes.

Note: off-chain purchases will be limited to the first sale cycle where we are selling direct to the customer to allow us to control for unexpected eventualities such as double payments. Secondary sales will be on-chain but will be possible in STX and any fungible token we choose to support. 

While we support and admire the lnswaps project and the idea of atomic swaps after talking with other members of the community we think there is also a need for off chain payment integrations especially as an on-ramp for non crypto folk and this is really the focus of this application.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

We are able to keep the scope of the technical ask small by reusing open source code developed for the [StacksMate](https://github.com/stacksgov/Stacks-Grants/issues/137) grant. This also benefits from recent work which delivered an NFT marketplace for generalised fungible tokens. Therefore the main technical work to deliver the project is 
1. OpenNode payment flow / smart contract integration
2. SquarePay payment flow / smart contract integration
3. A new web based NFT marketplace to host the artwork4. 

Note: steps 1 and 2 are available via npm registry and we are asking for help with the cost of this work. Step 3 is outside the scope of this grant application as this is not reusable by the community.

Success of the project will be measured in new wallets, footfall and sales. We create a buzz through access to word of mouth and local business networks in order to attract potential customers. Sales will reflect the success of the project in financial terms.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Ask: 8,216.11 USD

See breakdown below

Total Grant Request: 

Milestones | Time (days) | GBP (@ 250 per day)
-- | -- | --
*Technical Milestones* |  | 
OpenNode Integration | 7 | 1750
SquarePay Integration | 5 | 1250
UI Development | 20 | (not included in ask)
*Exhibition Milestones* | |
Materials - frames, screens, assembly | - | 2600
Venue hire (2 day weekend in May) | - | 600  
**Total GBP** || **6200 GBP**
**Total USD** || **8,216.11 USD**

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Our team is a combination of fresh new faces in the stacks family together with some old wisened ones.

On the creative side Liverpool born artist Chris Radcliffe is heading up delivery of the exhibition. Its not his first art show rodeo! Together with Terri, lead designer at Brand Republica they are also working on the brand strategy, marketing strategy and design for a new NFT marketplace on Stacks for fine art. More on this soon!

The tech team benefits from the energy and experience of lead developer and product manager Hsiu Rowen; Mike Cohen (not a recipient) will provide support porting code from stacksmate.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

The general state of the global economy and the crypto bear market are obvious risks for the exhibition - in effect this grant application is a mitigation against being able to cover the cost through sales of artwork. For this reason we are also thinking of the exhibition as a trial run so in effect we are building a template to make future events easier to set up and run.

Risks associated with the payment integrations, bugs etc will be mitigated by a) code reviews, b) smart contract code reviews, c) tightly controlling sales through the platform d) unit/integration tests.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

This is a new team which combines people well known to the stacks community with new faces bringing new ideas, marketing channels and experiences into the ecosystem. Chris and Terri have many years experience delivering on brand strategy and as a result have a network of relationships within the local art scene. It is through these channels that we will target the local collectors and art enthusiasts in Brighton.

A more general marketing strategy is being prepared for the the launch of the NFT Gallery which accompanies this grant proposal. We are setting up a new dedicated discord server to manage the marketing for this platform within the stacks community but this work is beyond the scope of this application.

**Comment by will-at-stacks** [comment]
Hi @hh8899 
Thanks for the application. This is a really interesting concept and we would love to support the technology.  We don't usually support events with grant funds, but I would like to meet with you and our event planner to see if there is some way to facilitate this.  Could you email me and we can set up a Zoom call to discuss in a bit more detail? We are all out next week, but we can chat the week after. My email is [will@stacks.org](mailto:will@stacks.org).

Thanks,
Will

**Comment by hh8899** [comment]
Hi Will

Thanks for giving us the opportunity to discuss our project. It was really nice to meet you and Vanessa too. 

I will submit the grant application asap and we look forward to the next meeting.

Thanks
Hsiu

**Comment by hh8899** [comment]
Hi Will, Shannon,
I've tried several times to submit the grant application and haven't been successful. I've attached a screenshot of the message which simple reads "Grant application not sent". Would you be able to direct me to a support team who can help with this error?



ThanksHsiu
    On Wednesday, 20 April 2022, 18:55:59 BST, Will Corcoran ***@***.***> wrote:  
 
 


Hello Hsui thank you for the application and great meeting you yesterday!

We would like to ask you to please submit your grant application again using our new Grants Dashboard since we will no longer be monitoring this repo. I will send and invite for us to meet with Shannon soon.

Thanks in advance,
Will

**Comment by will-at-stacks** [comment]
Hi @hh8899 -

Which process are you attempting to complete:

1. Request a review on grantsdashboard.stacks.org
2. Submit an application via grants.stacks.org

Thanks
Will

**Comment by will-at-stacks** [comment]
@hh8899 ah, I see.  you can just post the links I requested (code / presentations / etc) right here.  thanks, will

**Comment by hh8899** [comment]
OK will do thanks.
    On Tuesday, 11 October 2022, 16:39:00 BST, Will Corcoran ***@***.***> wrote:  
 
 


@hh8899 ah, I see. you can just post the links I requested (code / presentations / etc) right here. thanks, will

**Comment by hh8899** [comment]
Sorry its taken us a while to report back. This was primarily because we decided to push the gallery to end of year 2022 given the current wintery climate in the NFT market - hoping that things might have picked up and also playing on the fact that our app lets people mint SFT artworks as gifts /  Christmas presents. 

Despite the team has delivered on all the technical milestones, as you can see from the screenshots. Alongside this Chris has been sorting through his amazing collections and has been preparing for the exhibition. Feel free to take a look at the testnet site https://staging.electricart.gallery. We hope the attached document demonstrates that we have met our targets for milestones 1 and 2 for the fiat and bitcoin work for the interesting case of SFTs and hope you are able to disburse payment. 
[STAC-Electric Art Gallery-071022-122254.pdf](https://github.com/stacksgov/Stacks-Grant-Launchpad/files/9814934/STAC-Electric.Art.Gallery-071022-122254.pdf)
