### ISSUE TITLE
Education and Marketing Partnership

### ISSUE THREAD

**Issue by Paulagot** [stacksgov/Stacks-Grants#326]
**Background- The Problems**

There is an awareness of blockchain, cryptocurrency, and web3 but people don’t know what to do with it and don’t know how to use it.  

Many that buy into cryptocurrency have a very limited understanding of blockchain and web3 technology and don’t know where to go to learn more.

Fuelled by open-source development allowing for deployment of products in a fraction of time, the rate of innovation in the web3 and blockchain space continues to accelerate.

Much focus from developers has been on “Copy paste” projects due to the speculative and volatile nature of the crypto market and the possibility of quick gains.  This is reducing the focus and investment on real innovation in the space.

Innovation has been fast, yet quality training required to produce anything bar developers and cryptocurrency traders is not easily accessible and available. Education and training are key to the adoption and the rise of new innovations and ideas.

Not all ideas and innovations will come from developers - We need more changemakers, entrepreneurs, and other key roles educated in this space.

Those with existing skills are being snapped up by Fintech and others wanting to get in on the industry. This is leading to a shortage of skilled resources that should feed the adoption cycle as we move from Early adopters to the Early Majority.

This skills shortage has also left development teams with little or no business teams, thereby putting strain on the demand for partnerships and slowing down ecosystem growth.

The current user base and those with Web3 literate skills are spread too thin and need to grow rapidly to sustain the growth of development.

Adoption can’t come fast enough.

**Project Overview - The Solution**

Build a community of educated talented web3 professionals and advocates. Through education and network growth, we will accelerate the rate of adoption in line with the speed of innovation by equipping people with the skills needed to become the marketing innovators, entrepreneurs, and business innovators that will take Web3 to mass adoption.

***Our Mission***
It is our mission to accelerate the adoption of Web3, Blockchain, and Cryptocurrency Technology.

***Our Aim***
By providing quality education, we aim to create a Web3 literate community of innovators, entrepreneurs, professionals, and end-users ready to navigate, build on and champion the new economy and a decentralized future.

**Our Proposal to Stacks**
We will run a 26-week educational marketing campaign with the aim of showcasing Stacks and its ecosystem to the future entrepreneurs, change-makers, and professionals of the Blockchain, web3, and digital assets space.  This will put Stacks in front of the mind for future projects, developments, and investments.

This marketing campaign will consist of the following:
•	Educating 200 Learners in our feature training program – Expert Track in Web3, Blockchain, and Digital assets.  See below for more details on our Expert track. Stacks and its ecosystem and DApps will be featured in each section live class as case studies, examples, presentations, and discussions.
•	Integration of our eLearning platform with Stacks for the minting and issuing of Progress Completion Certificate NFTs.
•	All other awards relating to the Expert track will also be minted on Stacks
•	10 Online Presentation webinars on Stacks ecosystem, showcasing Dapps and other services built on top of Stacks.
•	5 1of1 Crypto art NFT giveaway contents minted on Stacks.
•	2 In-person Meetups, 1 in London and 1 in Dublin, both with Stacks swag for attendees and speakers, with light refreshments provided.
•	Ideathon – We will pull all the great minds together that we have educated over the 26 weeks and host an Ideathon with a prize fund to take the most impactful ideas to the next stage.
•	Stacks will be listed as a partner on our website, and certificates of completion will be co-branded with the Stacks logo.
•	ABlockOfCrypto will issue co-branded press releases on this partnership.

***Our Feature Training Program - Expert Track in Web3, Blockchain, and Digital Assets.***
We will provide World Class Training & a community for innovators, entrepreneurs, professionals, Cryptocurrency enthusiasts, and end-users.

Over 18 weeks Students will Learn about Web3, Blockchain, and Digital Assets whilst getting ready to navigate, build on and champion the new economy and a decentralized future in an interactive way.

Students will become blockchain and cryptocurrency literate. They will learn from experts in a guided interactive way and they will master the lingo and skills needed to succeed in the Blockchain, Web3, and Digital Asset space.

Using a blended learning approach, this Web3, Blockchain, and Digital Asset Expert track will have weekly live classes, live coaching sessions,  self-study material, activities, and assignments.  The live classes and coaching sessions will take the learning to a deeper level using case studies and discussions and make up a core component of the track.

Over 18 exciting weeks, students will learn about
• Blockchain Technology
• Ecosystems and Tokenomics
• Cryptocurrency and Value
• NFT’s and the Metaverse
• Governance and DAO’S
• DeFi
• Web 3
• Network, Communications, and Infrastructure
• The Future of Blockchain and Cryptocurrency

This expert track is suitable for learners of all levels and is of particular interest to:
• Cryptocurrency Enthusiasts
• Financial and Legal Professionals
• Gamers
• Innovators and Entrepreneurs
• Creators and Artists
• Coders and Developers

Students will be awarded NFTs as they progress through the track. We will also have a unique award NFT which will be given out thought-out the track and at the end.  These will be for outstanding contributions to the community, and study group leaders.
A Certificate of completion is available once the student completes the necessary requirements and criteria.

**Scope - Integration of E-learning platform with Stacks**

Each section of this Expert track will have a progress completion certificate students can mint. There are 9 in total to mint. These NFTs are unique to each block of students and will bring future benefits.  Each one will have different benefits and learners must collect all 9 of them to get all the benefits.  In addition to future benefits, these NFTs also serve as certificates for skills completed in each section.  Students will be able to log into their web3 wallet and interact with the contract without leaving the course platform.

**How Stacks will benefit from this marketing campaign**
Brand Awareness, Adoption, Increased usage.

Over the 26-week partnership, via the different educational events, online, in-person, and recorded sessions we will reach 100,000 people.

Ideathon awards will be favored for projects that will help grow and expand the Stacks ecosystem or improve the overall blockchain or web3 space. This will be sponsored by Stacks and is captured in the campaign ask.

We will be working with established artists for the 1of1 NFT giveaways, allowing them and their followers to explore what Stacks have to offer.

Our in-person meetups will bring a Stacks presence to Ireland and the UK.
 
**Where we are now**
+22K email subscribers
+1200 online meetup members
Block 1 of the expert track started on the 21st Feb with 200 students.
We have a further 600 registrations of interest for this track.
  
**What help do we need?**
It would be fantastic to get some Stacks experts and developers of Dapps and services to work with us on the 10 webinars. These need to be tailored in advance.

**Budget and Milestones**
This is a 26-week educational marketing campaign that will have 4 full-time employees.  Milestones shown are for cash flow release.  Budget is shown separately,

Total Grant Request: $240,000

M1: Minting contracts for progress completion NFTs and integration with eLearning site.  $60,000

M2: 200 Students begin course  $60,000

M3: Online webinars (10 * $4000) $40,000

M4: 1 of 1 NFT giveaways (5 * $2500) $12,500

M5:  In person meetups (2*$7000) $14,000

**Budget**
Wages and salaries (4 full-time staff) $120,000
Smart contract implementation and audit $20,000
Purchase of 1 of 1 NFT's $10,000
Ideathon prizes*** (can be paid in STX) $30,000
Travel/Acc/Speakers  $14,000
Room hire/swag/food/drink  $12,000
General Marketing (press release/online campaigns for events..)  $20,000
Contribution to profit $14,000

**External links**
Website https://www.ablockofcrypto.com/
Video from Orientation week https://youtu.be/ay0ychZb7c4

**A message from the founder**
Hi, my name is Paula and I thought it only right to give you some personal background as a partnership is an investment and most often, investments are about the people behind them.

The greatest gift I was given by my parents was the gift of Education. Born and raised in Ireland, I was lucky enough to go to college and study Applied Science. To do this, my parents had to sacrifice a lot as they needed to pay not only my college fee but also my accommodation and living expenses away from home. It must have been an awful kick in the face for them at first when I could not get a job in my field of study.

But having the ability to learn, and the enjoyment of college made me like education, and I would now consider myself a lifelong learner.

After my initial bout of education, I did not let the job situation get me down. It was not long before I switched fields and by profession I have been a CPA accountant now for many years.

In 2007,  on the birth of my first child, I gave up my well-paid desk job to create a suite of e-learning courses on CD-ROM and start a home-based business on web2. These courses were aimed at accountants and professionals wishing to upskill in Microsoft Excel and Spreadsheets. E-learning was not even a thing.

In 2010 Udemy launched, killing the CD ROM market for education, making it impossible to compete with content delivered online. As Udemy was growing so fast I jumped on board and happily earned income from my online courses. However, in 2016 Udemy changed its policy. Instructor revenues got slashed and as instructors, we had no option but to comply or leave and try and complete alone.

In search of a fairer way for content creators in 2016, I turned to blockchain and have been an advocate for Web3 and the creator economy ever since. In 2018, pioneering the way for content creators, I tokenized my website and blog, offering Learn and Earn Activities for students. In 2020 when the world went into lockdown, I gathered the world’s greatest Excel Instructors and award winners, and we released a course raising $15K for charity. In 2020 and 2021 I won the Microsoft MVP award for my continued community involvement.

Now I am giving up my Career in Excel as I have a new mission. You can check out my old business website here and my [Udemy profile here ](https://www.udemy.com/user/paulaguilfoyle/) and my [Youtube channel here](https://www.youtube.com/c/PaulaGuilfoyle-theexcelclub/featured)

**Risks**
In-person events could be hampered by Covid restrictions.  We are hoping not however we do have the ability to move these online.
I also foresee a problem with student dropouts and the completion rate which is common for online learning.  To overcome this we have dedicated student outreach.

**Community and Supporting Materials**
I am currently running the first block of students in the expert track and the feedback has been great so far.  So many are surprised we are offering this for free, and we hope with a partnership, we will be able to continue this.

**Let’s Discuss**
If anyone would like to hop onto a quick video call to find out more and talk with me directly, just let me know and we will hook up.
If you have any questions, comments, or suggestions for change/improvement to this proposal, please do comment below. I am looking forward to engaging with you all.

**Comment by SiDyr** [comment]
Looks fantastic - great to have a course focussed on non-devs, this is an area that is sorely lacking with good people not being blockchain literate and not considering working in the industry as a result

**Comment by will-at-stacks** [comment]
Hi @Paulagot - 

Thanks for the application, but we have decided to reject your request.  While we have supported similar (and much smaller in monetary terms) educational projects in the past we felt that a substantial amount of your budget line items fell outside of the parameters of what we fund with grants.  Grants are a mechanism to support new and novel, open-source technology and affiliated efforts.  We are also not familiar with you from the Stacks community and put a high premium on building relationships with builders through the course of small grants before awarding anything that even approaches this size.  If you would like a chance to speak by zoom about how you could reframe your application in hopes of having a small portion of it supported by a grant, please email grants@stacks.org.

Thanks,
Will
