### ISSUE TITLE
Educating through Podcast - She's All Over The Place by Katie Chonacas

### ISSUE THREAD

**Issue by NFTchonacas** [stacksgov/Stacks-Grants#327]
**Background**
What problems do you aim to solve? How does it serve the mission of a user-owned internet?
For the masses that have little knowledge about the blockchain and its capabilities, and are scared away by technical jargon. These are not necessarily problems, but our mission is to inform, educate people on staking in Stacks on bitcoin, educate people on web 3 technology, raise awareness, and educate them more about STX.

**Project Overview**
What solution are you providing? Who will it serve?
Katie Chonacas, the host of She's All Over The Place, wants all her audiences to be more knowledgeable. We serve beginners who are just getting into the space and experts alike by educating, inspiring, and bringing topics closer to the mainstream.
We help beginners start with the best tool for web 3.0 -- Bitcoin. With more than 20 million people already participating in the new internet, we want to make it easier for everyone to join the next generation of web users. 

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
The components of the project are all self-produced, with high-quality equipment, TLM 103 microphone, and self-edited with an admin team and social media team. It goes out on over 31 podcast platforms internationally.
We measure our success through statistics, downloads and plays, engagements, and promos over social media.
She's All Over The Place is in the top 5% of all podcasts (4.5 million) and the top 48 out of all the 60 Arts Podcasts.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: 
$4,000
Podcast creation will take us 8 hours of work per episode, from setting up and recording the guest and editing, mixing, and mastering the episode. We also need to add time for administration and social media promos.
We aim to have 16 episodes for this grant.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 
Katie Chonacas, self-produced podcast. Katie was introduced to the world of blockchain in 2018 and has been using it to be educated and now focusing on the niche of blockchain, NFTs, etc. She's All Over The Place podcast focuses on Women's Empowerment, the business in the entertainment industry, the arts, culture, mental health, web3 education, NFTs, etc.

She is especially excited by all that she has learned about Stacks, and she is excited to share it with her community.
Links to previous episodes:
https://www.chonacas.com/podcast/
[Bitcoin STX Executive Director of the Stacks Foundation - Brittany Laughlin](https://directory.libsyn.com/episode/index/id/22604489)
[NFTs and Fashion NFTs with Hey Layer Marketplace](https://directory.libsyn.com/episode/index/id/22377224)
[Jimena Buena Vida NFT Artist from Colombia](https://directory.libsyn.com/episode/index/id/22314041)
[NFTs Sketch by Sketch Mental Health with Sheila Darcey aka sketchpoetic](https://directory.libsyn.com/episode/index/id/22455890)

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
None. 
Contingency: Sponsors of 16 episodes for the podcast.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

Yes, season 4 of She's All Over The Place is an NFT podcast that focuses on everything about the blockchain.
People loved the podcast they think it's very informative.
Streaming every Tuesday consistently, on over 31 Podcast streaming platforms internationally on Katie's IG and Twitter, Youtube, LinkedIn.

**Comment by will-at-stacks** [comment]
Hello Katie and thank you for the application!  

We would like to ask you to please submit your grant application again using our new [Grants Dashboard](https://grants.stacks.org/) since we will no longer be monitoring this repo.  

Thanks in advance, 
Will
