### ISSUE TITLE
Bitcoin Beach Camp

### ISSUE THREAD

**Issue by tunniverse** [stacksgov/Stacks-Grants#330]
**Background**
### Bitcoin Beach Camp in Thailand.
We've seen success stories from Bitcoin Miami that benefit users and developers and project city coin. Bitcoin Beach in El Zonte, El Salvador was also a pioneer in the country's Bitcoin adoption. For Bitcoiners Phuket is one of the best destinations in Asia. Phuket, Thailand is a diverse city and a popular tourist destination. This meetup could lead the way for something significant in the future for example startup boot camp.

**Project Overview**
We will create meetup camp in Thailand it will be a community of Bitcoin user and developer including finance and investment part. Meetup camp will be monthly meetup the theme will be rotating from user, investor to developer. 

The main purpose of the meetup is to educate and create an active community. Participants will share and learn from each other during the event to develop Bitcoin ecosystem. For example people skip fundamentals of Bitcoin to other smart contract and other blockchain just because they have no idea they can send bitcoin lightning fast and also misconception they can not create dapp around Bitcoin.  

**Scope**
**Core Values**
1. Education: We will share and learn together about Bitcoin including its technology and economic perspective.
2. Rise Adoption: Searching for a Solutions for Bitcoin adoption in Thailand.
3. No Shitcoin: Community-oriented for reduction of shit coin and scam projects.

**Meetup Frequency**
1. Will be hosted monthly in the last week of the month 
2. starting from May 2022 (If we're able to sign contract with in Apr 2022)

**Venue & Time**
1. Ideally Cafe, Co-Working Space, Hotel, Expect around 30-50 attendees
2. 30-50 attendees, Meetup period is 3 hours 

**Pre-Meetup**
1. The following Pre-Meetup tasks must be done two weeks in advance
2. Advertise the event on meetup.com and social media platforms
- The event will contain the topic, description, date, hour schedule, duration, and guest names.
- Events will be shared across all social media channels that we operate under the hashtag #bitcoinbeachcamp

**During the Meetup**
1. We will keep track of the number of attendees in a google sheet, or via any other metric possible. 
2. Gather visual media of the event. Record the meetup and take lots of pictures. 

**Audience**
1. Government sector
2. Faculty of university
3. Business association 
4. Investor

**Budget and Milestones**
We try to run this event monthly and we will keep it free but to make it happen we are looking for a small budget to support rental venue food & beverages. If you would like to support this event we believe it will benefit the brand reputation and attract new users. 
Total Grant Request: $1500

M1: Bitcoin Beach Camp #1, $500

M2: Bitcoin Beach Camp #2, $500

M2: Bitcoin Beach Camp #3, $500

**Benefit**
1. The sponsor's logo will appear in all of the media we use to promote the event before, during, and after it takes place.
2. Throughout the event, the sponsor logo will be displayed at all times.
3. Product introduction from Stacks team.
4. At the beginning and end of the event, mention the sponsor's product or service with a brief introduction.
5. Following the event, we will share photos and video clips, as well as sponsor logos.   
6. Create brand awareness and reputation for potential users
7. Onboard new users

**Team**
Tun Karnjanakul
Bitcoiner since 2011
[Linkedin](https://www.linkedin.com/in/tunkarnjanakul/)
[Twitter](https://twitter.com/TheTunniverse)

**Risks**

1. Need to invite talented people and keep in touch with attendees to make next meetup topic strong. 
2. Need support from Stacks tech team.
4. If organizer can't reach numbers of sponsor for this project to cover all expenses organizer might need to scale down event.

**Community and Supporting Materials**
Project proposal: [PDF File](https://docs.google.com/document/d/14vzOvMkg2X9RQkTe72D1abC4e2e-RAysc95MRW-j1oU/edit?usp=sharing)

**Comment by will-at-stacks** [comment]
Hello and thank you for the application!  

We would like to ask you to please submit your grant application again using our new [Grants Dashboard](https://grants.stacks.org/) since we will no longer be monitoring this repo.  

Thanks in advance, 
Will

**Comment by tunniverse** [comment]
I did resubmitted.

-------------------------------------------------------
Tunyalit Karnjanakul (Tun)
Tel: +66.81.668.7744
-------------------------------------------------------

**Comment by tunniverse** [comment]
Hi Will

My grant proposal is number 341. It's show Denied. I would like to ask you
or the person who is considering about the reason why this proposal got
rejected.

Best regards,
Tun

-------------------------------------------------------
Tunyalit Karnjanakul (Tun)
Tel: +66.81.668.7744
-------------------------------------------------------

**Comment by will-at-stacks** [comment]
Hi @tunniverse 

In general, we try to avoid funding events via grants because the it is difficult for the money / effort going into an event to 'scale' and have a widespread impact on the broader Stacks community.  We do plan to add event applications to the dashboard in the future.  However, I would encourage you to reach out to our Events Lead, Shannon at shannon@stacks.org.  She can take a look at your application and let you know if any funding could be made available.  Please be sure to let her know how Stacks will be presented / represented at your event.

Thanks
Will

**Comment by tunniverse** [comment]
Hello Shannon.

I plan to host a monthly meetup "Bitcoin event" in Thailand. I think it
will be your direct users at this meetup event. And it will be beneficial
for you. I'm not sure how Stacks considers sponsoring bitcoin events. I
sent you this Google Docs link
<https://docs.google.com/document/d/14vzOvMkg2X9RQkTe72D1abC4e2e-RAysc95MRW-j1oU/edit?usp=sharing>
for more details about the event.
I plan this to be a long-term strategy by gathering small groups in
different areas and seeing if this leads to bigger events in the future.
For now, it will be a monthly event. I expect around 50 people to join each
time for this meetup event.

Audience at this event
- Government sector
- Faculty of university
- Business association
- Software Developer & Startup

From there, it's not a final schedule yet. I'm open to your idea and will
see if we can collaborate and I can bring the best options for Stacks. For
example, some workshop ideas or representatives from the Stacks team speak
at the event.


Proposal:
https://docs.google.com/document/d/14vzOvMkg2X9RQkTe72D1abC4e2e-RAysc95MRW-j1oU/edit?usp=sharing

[image: Bitcoin Beach Camp Banner.png]


Best regards,
Tun



-------------------------------------------------------
Tunyalit Karnjanakul (Tun)
Tel: +66.81.668.7744
-------------------------------------------------------
