### ISSUE TITLE
Koryntia

### ISSUE THREAD

**Issue by gregoriopunzano** [stacksgov/Stacks-Grants#332]
**Background**

Koryntia your loan in less than 3 minutes in your decentralized account.

https://koryntia.finance

**Project description**

Koryntia is a decentralized lending protocol based on blockchain technology with a global ambition that aims to be the bridge between DeFi and CeFi to help millions of people obtain credit and enter an equitable financial system. 

1. Choose the amount in the best loan protocol in the world.
2. We accept your loan 100% transparently in less than 3 minutes. Without any hidden conditions.
3. You receive the money in account. Return it as you like. Welcome to Koryntia.

**Scope**

In the massive adoption of users to the protocol.

**Budget and milestones**

Total Grant Request: $350K (for 6 months)

M1: MVP, 1 performance, 6 months, $250K

M2: Growth Team, Round Preparation ($$) $100K

Deck: https://brieflink.com/v/hcfaj

**Equipment**

1. Gregorio Punzano: I build a Mcwatchesco. online luxury brand worldwide and made it known to millions of people, he has caught the attention of Vanity Fair UK for his unique designs.
https://www.linkedin.com/in/gregorio-punzano/

2. Igor Petrov: +8 years of programming experience with global projects and startups.
https://www.linkedin.com/in/igor-petrov-991667222/

LinkedIn's company: https://www.linkedin.com/company/koryntia-finance

**Risks**

The biggest risk is that it will take longer and cost more than expected and not be able to cover it.

How do I intend to solve this problem by working on an investment round while building the MVP.

**Community and support materials**

—+300 active users, community +4000
—$25 million LOI, STO investors

**Comment by will-at-stacks** [comment]
Hello and thank you for the application!  

We would like to ask you to please submit your grant application again using our new [Grants Dashboard](https://grants.stacks.org/) since we will no longer be monitoring this repo.  

Thanks in advance, 
Will
