### ISSUE TITLE
Two articles focusing on NFTs (clearness.dev)

### ISSUE THREAD

**Issue by hugoclrd** [stacksgov/Stacks-Grants#333]
**Background**
`What problems do you aim to solve? How does it serve the mission of a user-owned internet?`

The Stacks ecosystem needs to attract **more developers**. Either Web developers that could easily apply their knowledge to Web3. Or aspiring developers who want to dive in and learn Clarity.
There are already some resources available to get started. In my experience, they are often not accessible for novice or intermediate developers.

**Project Overview**
`What solution are you providing? Who will it serve?`

I started working on [clearness.dev](https://www.clearness.dev/) on the 17th of March 2022 (according to GitHub). As of today, I published 17 articles that are mainly part of two tutorials:
1. [Get started with Clarity - Develop an on-chain voting system](https://www.clearness.dev/01-voting-clarity-smart-contract/01-getting-started)
2. [Build the Web App for the voting system with micro-stacks](https://www.clearness.dev/03-build-the-voting-client/01-setup-web3-application)

I recently finished the first steps of these two tutorials. I now want to move forward to the next step: a tutorial focusing on NFTs with two articles (for now, in the scope of this grant):
1. Extend the voting system to reward voters with an NFT
2. Handle NFTs on the web app (with a focus on post-conditions with micro-stacks)

**In the continuity of the blog, these articles will target developers new to the ecosystem and beginners.** 

**Scope**
`What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?`

These two new articles will be available on [GitHub](https://github.com/hugocaillard/clearness/) and [clearness.dev](https://www.clearness.dev). I'm also currently considering publishing the articles on Sigle (which would be good for the persistence of the articles). To keep the same quality, I need to support Clarity syntax highlighting first (so I made a [PR](https://github.com/sigle/sigle/pull/422)].

The source code of these projects is also open-source on GitHub in these two repositories (MIT license): [Clarity Contract](https://github.com/hugocaillard/clarity-voting-tuto) and [Web App](https://github.com/hugocaillard/color-webapp-tuto). If you look at the closed PR, you can also see that there is one PR per article.

Success is measured through traffic which is measured with Plausible.io. You can see past performances through [this link](https://plausible.io/share/clearness.dev?auth=H651H2wU9TTbyOiudolaL) (this specific link will be temporary but I'll be ok to make the dashboard available to anyone asking in the context of this grant). Of course, this is still a new project but I'm starting to get a few visitors. Most of the marketing is done on [Twitter](https://twitter.com/cohars) and the Stacks Discord.

👉 Existing articles are published under [this license](https://github.com/hugocaillard/clearness/blob/main/LICENSE-posts.txt) but I'm ok to reconsider it for the articles in the scope of this grand request.

**Budget and Milestones**
`What grant amount are you seeking? How long will the project take in hours?`

**Total Grant Request: 1400 EUR => 1525 USD**

**M1:** 
Each article takes 8 to 10 hours to **write, review, publish and promote**. Including the time needed to **develop the projects** taught in the tutorials which is not negligible.

If granted, the money will also compensate the expenses linked to this project: 
- hosting (Vercel, although I started the process for [sponsorship](https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project))
- analytics (with Plausible who gave me a 25% discount)
- a month of Grammarly premium (which I'll be negociating as well). As a non-native English speaker, the free version has been a real help but if this grant is accepted, I'd like to increase the quality of my writing.

**Team**
`Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work.`

I'm working on it on my own, also the result is open-source and open for contributions (already have one external contributor on the blog).
Relevant experience: the past articles on [clearness.dev](https://www.clearness.dev), 6 years of professional software development and many hours of teaching computer science.

**Risks**
`What dependencies or obstacles do you anticipate? What contingency plans do you have in place?`

Based on the current progress of Clearness, risks are very low. Although I can't guarantee the number of new developers it will bring, I expect to have a valuable impact with time. If this goes well, I have other ideas for future articles (a series on the architecture to extend/update contracts in production and more standalone articles, see the [roadmap](https://github.com/hugocaillard/clearness#roadmap)).

👉 **At this stage, I'm willing to release articles about NFTs as I think it's an entry point into Web3 for a lot of developers and I think it can be very beneficial for SEO and marketing.**

**Community and Supporting Materials**
`Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan with the community over time and as the final deliverable?`

Here are all of the relevant links:
- [Clearness.dev](https://www.clearness.dev/)
- [Clearness repository](https://github.com/hugocaillard/clearness)
- [Smart Contract project repository](https://github.com/hugocaillard/clarity-voting-tuto)
- [Web App project repository](https://github.com/hugocaillard/color-webapp-tuto)
- [My Twitter](https://twitter.com/Cohars)
- [Clearness analytics on Plausible.io](https://plausible.io/share/clearness.dev?auth=H651H2wU9TTbyOiudolaL)

Once/if this grant is accepted, I expect to publish the articles in less than 10 days. Progress will be visible on GitHub and the release of the articles will be shared on Twitter.

**Comment by will-at-stacks** [comment]
Hello and thank you for the application!  

We would like to ask you to please submit your grant application again using our new [Grants Dashboard](https://grants.stacks.org/) since we will no longer be monitoring this repo.  

Thanks in advance, 
Will

**Comment by will-at-stacks** [comment]
my mistake.  I see you already di.  thanks, Hugo!
