### ISSUE TITLE
$ROOKIE x Stacks Collaboration

### ISSUE THREAD

**Issue by blackmambabtc** [stacksgov/Stacks-Grants#335]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?
 
$ROOKIE is a web3 brand that is bridging blockchain & basketball. Designed to help support WNBA, G-League, & International players. We have weekly podcast with players to discuss their journeys, successes, failures & crypto as a whole. We have connections in and around the NBA/WNBA. What we need is a partner who fully understands the web3 space and especially where we are at in history. 
Building on Stacks is very important, using bitcoin as a programmable layer brings bitcoin one step further to being that asset we all know it will be. Adoption starts with usage & building this product on Stacks will bring a whole new, non-crypto native crowd in.

**Project Overview**
What solution are you providing? Who will it serve?

Hoop-to-Earn. Get paid to play basketball. Anyone with a hoop & a ball will be able to make money, earn prizes, & even win a chance at a G-League try out. Seeing the success of STEPN really inspired us & proved that innovation never stops. We are currently shooting the commercial which will be shot worldwide, to emphasis the inclusivity & accessibility of Hoop-to-Earn. 

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

We are working from the solution backwards on this project. The technical aspects are simple, build a dAPP that can contain data, looks good, & produce a basketball with a tracker in it. Basketball technology is in place; dAPP is simple to build. The final deliverables will be a basketball with a tracker in it that can connect to a dAPP on your phone. Success will be measured by the impact of our marketing as well as how many active users & balls sold.

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

We are at the beginning stages of this. If your only sole & only motive is to make money than this isn't for you. The goal is to build a BRAND & PRODUCT that is used daily, all around the world. Something that is impactful & changes peoples lives. I will spend more than 40 hours a week on this. Anything worthwhile is not easy. The first milestone will be getting a working prototype, then a functioning beta; then getting the product out in the public. 

Total Grant Request: 
??? It depends. I want to solely work on Stacks. Bringing users & awareness to Stacks is something extremely important. Lets talk more & figure out the best way to do this.

M1: Scope of work, deliverables, and grant amount of total.

M2: Etc.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

We have 4 core team members. Me, founder, Basquiape, art/design, JJ, marketing/connctions, Dominco, Community Manager/ video lead. I am the one leading the charge & putting these moving pieces together. We will need more tech heavy members of the team to join but the Stacks community is FULL of them.

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

There is always the risk of failure, that goes without saying. The biggest obstacle lies in funding. Once we have the funding in place with the right partners nothing will stop us. Marketing is in place, connections are in place, just need a partner who sees the vision.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

https://rookieinu.co/
https://medium.com/@rookieinu/welcome-to-rookie-eea9dfa6fca4
https://twitter.com/RookieInu
https://www.linkedin.com/in/juandiego-gonzalez

**Comment by will-at-stacks** [comment]
Hello and thank you for the application!  

We would like to ask you to please submit your grant application again using our new [Grants Dashboard](https://grants.stacks.org/) since we will no longer be monitoring this repo.  

Thanks in advance, 
Will
