### ISSUE TITLE
Clarity language logo

### ISSUE THREAD

**Issue by eugeniadigon** [stacksgov/Stacks-Grants#336]
Hi all 👋 

First of all, apologies if this discussion isn't open in the correct repository, but I didn't find a better place to post this. This is not a grant application, but just a community proposal.

**Background**
It's been brought to the community's attention that Clarity language lacks a logo, which makes it hard for users and developers to quickly recognize it and to have a way of representing it. 

**Project Overview**
I'm offering a solution to this problem by presenting a logo proposal, open to the community's feedback and discussion

**The solution**
I'm attaching a PDF presentation. In this presentation, there are different logo applications/usages, and a showcase of the logo seen in context (websites, merch, social media)

To build this logo, I took some of Clarity's attributes and translated them into graphic elements. The attributes I chose to represent are: (1) The main syntax element of the language - parenthesis, (2) Clarity is predictable, (3) Clarity is decidable, (4) Clarity is safe/secure

(1) Parenthesis: The mid parenthesis assimilates to an outstretched C (of Clarity), without being too obvious
(2) Predictable: repetition of the parenthesis - a foreseeable sequence
(3) Decidable: The on/off (yes/no) colours in the parenthesis sequence
(4) Safe/secure: Graphic elements / typography visually "sheltered" by the parenthesis

The typeface used is Porpora, by the open-source foundry [collletttivo.it](http://collletttivo.it/)

Attributes I tried to avoid and why:
- Human readable, or being too literal on the word "clarity": previous logo options have shown as a representation of this some figures such as a human eye, which IMO makes it look like an optical store logo
- The "C" as the main element: there are already other very known programming languages that use the C as logo (C#, C++)

**Community and Supporting Materials**
If a majority is happy with this proposal, and once there's a consensus or agreement on the direction, I'll share the source files

[Clarity-Logo.pdf](https://github.com/stacksgov/Stacks-Grants/files/8476070/Clarity-Logo.pdf)

**Comment by will-at-stacks** [comment]
@eugeniadigon - these are amazing!  so thankful to have you as a member of the stacks community!

**Comment by will-at-stacks** [comment]
@eugeniadigon - I am going to close this issue since we will move the conversation to other communication channels per my email.  thanks again!

**Comment by fluidvoice** [comment]
@eugeniadigon @will-at-stacks 
I know this is closed and I replied to the email thread and survey, but I wanted to record my thoughts...
I like this logo design/idea quite a bit. I only wonder if it can be _improved when in tiny form of a browser **favicon**?_
Could a background shape or color behind the "CCC" help to make it more easily recognizable in a crowded list of browser tabs?  Or perhaps the spacing and thickness of the lines of the "CCC"?
Thanks for your work, looks great!
