### ISSUE TITLE
Remixable User-Support Videos for Developers Working with Enterprise-Level Clients

### ISSUE THREAD

**Issue by ryanarndtcm** [stacksgov/Stacks-Grants#34]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> End users who are part of enterprise customers are requiring extra education on simple things in the Stacks sign up process. They need to know in a simple way how to create an ID, what a seed phrase is, and why they should keep it safe.

This has come out of a defined need after hearing of troubles end users were having signing up and maintaining seed phrases when using enterprise-facing apps like Blocksurvey and Pravica.

## Project Overview

> The solution is remixable video assets that could be used by those in the ecosystem working with enterprise customers. In this way we could useful videos on basic concepts for all, but each developer could add in their own branding. The videos would also be able to be used for any end-user education that a developer may need.

## Scope

> The deliverable would be video clips explaining the topics below in everyday language (for those unfamiliar with crypto). This is not an exhaustive list but a starting point for discussion.

- What is a Stacks ID?
- What is a seed phrase and why is it important?
- I lost my seed phrase, what do I do?
- What is decentralized ID?
- What is the decentralized internet and why is it important? 
- Who controls my data?

Videos need to be branded with Ecosystem branding as seen on stx.design to be useful to as many developers as possible.

## Budget and Milestones

> Working on getting multiple ideas on this from content creators in our community.

## Team

TBD.

## Risks

Videos need to be made consistent with creating an ID using Blockstack Connect. If changes are made to Blockstack Connect, these videos would need to be updated. 

## Community and Supporting Materials

> the Blockstack FAQ (updates are needed here too - please only use as a starting point. They were not updated with Blockstack Connect release): https://blockstack.zendesk.com/hc/en-us/sections/360007620914-Blockstack-General-Questions

**Comment by HariniRajan397** [comment]
Brilliant idea! Voting up for this grant! Having remixable user-support videos is really good and it will definitely help the app founders and app users. @ryanarndtcm As discussed, adding the list of questions we (BlockSurvey team) often hear from users. If these topics are addressed as part of this grant, this will be really helpful for the whole community. Thanks.

1. Is GAIA storage GDPR compliant?
2. How to delete my decentralized ID / Can I delete my decentralized ID?
3. How to sign up using 'Connect'?
4. Common errors seen during sign up. eg. https://help.blocksurvey.io/article/74-your-username-could-not-be-registerd
"Your username could not be registered"
- This error is primarily seen when more account registrations are happening from the same network.  This could also happen when a common IP is used by the intern.
5. Why there is no email id and password id to sign up
6. Is my data on the blockchain? is it open and everyone can see it?
7. How can I delete my data?

**Comment by RaffiSapire** [comment]
Hey @HariniRajan397 are these questions for the community?

**Comment by ryanarndtcm** [comment]
@RaffiSapire I asked Harini to add other questions that Blocksurvey is coming across so that they could potentially be included as part of the wishlist grant. I will compile and update for time (my original addition was scoped for 1-2 days by a content creator.

**Comment by ryanarndtcm** [comment]
Here is a full list of combined questions.  With this full list of videos including content creation and editing, I am setting the budget at $1000 with a Milestone 1 for review by the Grant Committee when the first 6 videos are completed ($500) and Milestone 2 for the next 7 ($500). The videos should not have a particular introduction to the topic, but simply jump right in to answering the questions so they are the most useful as possible for remixing. 🙏 

Milestone 1
1) What is a Stacks ID?
2) What is a seed phrase and why is it important?
3) I lost my seed phrase, what do I do?
4) What is decentralized ID?
5) What is the decentralized internet and why is it important?
6) Who controls my data?

Milestone 2
1) Is GAIA storage GDPR compliant?
2) How to delete my decentralized ID / Can I delete my decentralized ID?
3) How to sign up using 'Connect'?
4) Common errors seen during sign up. eg. https://help.blocksurvey.io/article/74-your-username-could-not-be-registerd
"Your username could not be registered"
This error is primarily seen when more account registrations are happening from the same network. This could also happen when a common IP is used by the intern.
5) Why there is no email id and password id to sign up?
6) Is my data on the blockchain? is it open and everyone can see it?
7) How can I delete my data?

**Comment by zrixes** [comment]
Great initiative on the support videos! Love it👍

I’ll give it a go this wkend, to work out a sample video to answer 1-2 qns on the above for everyone’s feedback and take it from there.

**Comment by GabrielSto** [comment]
Hi There Ryan. Great Idea! It is a necessary development to provide educational videos. There is a need to clarify things for users, developers, miners, and potential investors, etc. My recent experience with the instructions provided for mining need to be way better and faster. While I do not mean to diminish the work done, and the difficulty creating it, once we see that potential miners are having difficulty following instructions then we know is time to improve. I'm very much interested in helping out in this area if possible. I have some experience in creating videos and I'm gathering also information about additional software and hardware that can be used. So I guess if you need some help, just let me know.

**Comment by ryanarndtcm** [comment]
> Hi there Ryan. Great Idea! It is a necessary development to provide educational videos. There is a need to clarify things for users, developers, miners, and potential investors, etc. My recent experience with the instructions provided for mining need to be way better and faster. While I do not mean to diminish the work done, once we see that potential miners are having difficulty following instructions then we know it is time to improve. I'm very much interested in helping out in this area if possible. I have some experience in creating videos and I'm gathering also information about additional software and hardware that can be used. So I guess if you need some help, just let me know.

Thanks Gabriel! I was actually watching one of yours last week from your work with Freehold :) 

Id like these videos be modular so they can easily be put together with new audio, video or text in other languages.

**Comment by GabrielSto** [comment]
> > Hi there Ryan. Great Idea! It is a necessary development to provide educational videos. There is a need to clarify things for users, developers, miners, and potential investors, etc. My recent experience with the instructions provided for mining need to be way better and faster. While I do not mean to diminish the work done, once we see that potential miners are having difficulty following instructions then we know it is time to improve. I'm very much interested in helping out in this area if possible. I have some experience in creating videos and I'm gathering also information about additional software and hardware that can be used. So I guess if you need some help, just let me know.
> 
> Thanks Gabriel! I was actually watching one of yours last week from your work with Freehold :)
> 
> Id like these videos be modular so they can easily be put together with new audio, video or text in other languages.

Yes Ryan it is very much possible! If done in scenes it is not necessary to update a whole shooting session. The same regarding language I can manage for example Spanish, English, Dutch and potentially Portuguese so I can redo with a subtitle or even speaking a different language. I have been testing Touchcast,  Loom, Imovie, OBS. Three things are apparent. One, the difference in ease of use, which is important if different developers are redoing part of it. Two, that they can be shared and work in teams. Three, quality hardware, such as camera and mic has to be compatible...and it is not always the case. Another note is that always remains a bit an art and not a science so I guess we will always have to manually adapt the recording. I have not yet investigated fully, but I know that that you have real online studios that seem to work very nicely. They are expensive. Other points are quality management and how to make them as simple as possible which derives in using other tools such as animation and pictograms. Just let me know if we can do a trial of some kind. Be glad to help.

**Comment by GabrielSto** [comment]
> Here is a full list of combined questions. With this full list of videos including content creation and editing, I am setting the budget at $1000 with a Milestone 1 for review by the Grant Committee when the first 6 videos are completed ($500) and Milestone 2 for the next 7 ($500). The videos should not have a particular introduction to the topic, but simply jump right in to answering the questions so they are the most useful as possible for remixing. 🙏
> 
> Milestone 1
> 
> 1. What is a Stacks ID?
> 2. What is a seed phrase and why is it important?
> 3. I lost my seed phrase, what do I do?
> 4. What is decentralized ID?
> 5. What is the decentralized internet and why is it important?
> 6. Who controls my data?
> 
> Milestone 2
> 
> 1. Is GAIA storage GDPR compliant?
> 2. How to delete my decentralized ID / Can I delete my decentralized ID?
> 3. How to sign up using 'Connect'?
> 4. Common errors seen during sign up. eg. https://help.blocksurvey.io/article/74-your-username-could-not-be-registerd
>    "Your username could not be registered"
>    This error is primarily seen when more account registrations are happening from the same network. This could also happen when a common IP is used by the intern.
> 5. Why there is no email id and password id to sign up?
> 6. Is my data on the blockchain? is it open and everyone can see it?
> 7. How can I delete my data?

Regarding the creation of content, it will be necessary to choose first the software being used prior to content creation, because it is needed to test how well we can collaborate with others and change language, logos etc. If we don't do this it will lead to incompatibility issues for sure. Once one is chosen then you can request to start creating content, granting access to the editing.

**Comment by ryanarndtcm** [comment]
I was thinking open file types in general so they could be imported to the majority of platforms and having all parts be separate from each other so the audio, video, text would be able to be assembled in any way.  I think doing taht would work work best rather than a particular software. @zrixes @GabrielSto what do you think?

**Comment by zrixes** [comment]
Great suggestions from both in my opinion. To make it modular so that developers have the flexibility to include content as they deem fit into their products. Also to have an open file type thats easily accessible by a wide range of users, thus editing/translating the content to fit what they are working on will be accessible to developers.

**Comment by GabrielSto** [comment]
Yes, indeed both approaches are possible. Maybe we have to look at the plus and minuses of each choice. Open files are indeed very flexible. They would allow everybody to edit with possibly a higher production number videos. Open files will allow for a lot of diversity and it is a good cost-effective solution in terms of software. On the other hand, using one type of software, allows faster editing, homogenous work, possibly requesting less coordination between editors.  In the end, these movies can be exported to open files to be edited by everybody.  Let me know if you agree,  I'm to open to try both ways.

**Comment by ryanarndtcm** [comment]
@zrixes @GabrielSto is this project something that you two would like to work on together? I know @zrixes has already gotten things started, but want to make sure if there are ways to make these videos the best possible that we are able to do so. Thoughts?

**Comment by GabrielSto** [comment]
> @zrixes @GabrielSto is this project something that you two would like to work on together? I know @zrixes has already gotten things started, but want to make sure if there are ways to make these videos the best possible that we are able to do so. Thoughts?

It would be nice to talk with @zrixes and see how we could collaborate. Let me know if we can meet,  as I have a 7-hour difference. Cheers

**Comment by zrixes** [comment]
> > @zrixes @GabrielSto is this project something that you two would like to work on together? I know @zrixes has already gotten things started, but want to make sure if there are ways to make these videos the best possible that we are able to do so. Thoughts?
> 
> It would be nice to talk with @zrixes and see how we could collaborate. Let me know if we can meet, as I have a 7-hour difference. Cheers

Yea sounds good for me! How can I get in touch with you @GabrielSto ? I'm contactable at zrixes@gmail.com. My timezone is GMT +8, but happy to find a schedule that works for both of us!

**Comment by GabrielSto** [comment]
> > > @zrixes @GabrielSto is this project something that you two would like to work on together? I know @zrixes has already gotten things started, but want to make sure if there are ways to make these videos the best possible that we are able to do so. Thoughts?
> > 
> > 
> > It would be nice to talk with @zrixes and see how we could collaborate. Let me know if we can meet, as I have a 7-hour difference. Cheers
> 
> Yea sounds good for me! How can I get in touch with you @GabrielSto ? I'm contactable at [zrixes@gmail.com](mailto:zrixes@gmail.com). My timezone is GMT +8, but happy to find a schedule that works for both of us!

Just sent a reply via Gmail

**Comment by GabrielSto** [comment]
I just had a nice talk with Ethan. We discussed many potential ways to setup videos but we think it would be good to meet you Ryan. Are you available any time soon Ryan?

**Comment by ryanarndtcm** [comment]
Could next week yes would that work? This week is very busy with the launch

**Comment by GabrielSto** [comment]
Yes it would be better to move it to next week. We are also busy creating a mining pool, making mining accesible for more people in the community and beyond. Our first trial is with the launch.

On 12 Jan 2021, at 20:29, Ryan Arndt <notifications@github.com<mailto:notifications@github.com>> wrote:



Could next week yes would that work? This week is very busy with the launch

**Comment by ryanarndtcm** [comment]
ok back to it :) gabriel and ethan could you both email me at ryan at stacks dot org and we can get a time worked out altogether?

Thanks!

**Comment by GabrielSto** [comment]
> ok back to it :) gabriel and ethan could you both email me at ryan at stacks dot org and we can get a time worked out altogether?
> 
> Thanks!
Hi Ryan. I went to Stack.org. I only found a link to you via Discord... is this right?🤔

**Comment by oiclid** [comment]
Is this still open?

**Comment by GabrielSto** [comment]
Yes in cooperation


On 5 Feb 2021, at 15:59, Oïclid <notifications@github.com<mailto:notifications@github.com>> wrote:



Is this still open?

**Comment by zrixes** [comment]
> Here is a full list of combined questions. With this full list of videos including content creation and editing, I am setting the budget at $1000 with a Milestone 1 for review by the Grant Committee when the first 6 videos are completed ($500) and Milestone 2 for the next 7 ($500). The videos should not have a particular introduction to the topic, but simply jump right in to answering the questions so they are the most useful as possible for remixing. 🙏
> 
> Milestone 1
> 
> 1. What is a Stacks ID?
> 2. What is a seed phrase and why is it important?
> 3. I lost my seed phrase, what do I do?
> 4. What is decentralized ID?
> 5. What is the decentralized internet and why is it important?
> 6. Who controls my data?
> 
> Milestone 2
> 
> 1. Is GAIA storage GDPR compliant?
> 2. How to delete my decentralized ID / Can I delete my decentralized ID?
> 3. How to sign up using 'Connect'?
> 4. Common errors seen during sign up. eg. https://help.blocksurvey.io/article/74-your-username-could-not-be-registerd
>    "Your username could not be registered"
>    This error is primarily seen when more account registrations are happening from the same network. This could also happen when a common IP is used by the intern.
> 5. Why there is no email id and password id to sign up?
> 6. Is my data on the blockchain? is it open and everyone can see it?
> 7. How can I delete my data?



Just wanted to share some very basic education materials I've created over the weekend to address the common questions listed above that end users may ask when they first come across Stacks and/or using dApps built on Stacks blockchain. I’ve kept it in a very basic modular format, hoping to make it freely available to anyone with the aim of allowing creators and developers to freely use them and build on top of it for their own requirements.

I've hosted the materials on my [website](https://ethan-tan.com/stacks-blockchain-materials/), feel free to download them/use them! 
Materials available for each question above are in the following format: Video with narration, Video without narration, Audio-only, Text only.

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
