### ISSUE TITLE
Grant - Crypto Exchange

### ISSUE THREAD

**Issue by CodeLaryna** [stacksgov/Stacks-Grants#38]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> What problems do you aim to solve? How does it serve the mission of a user owned internet?

Crypto currency exchanges go deep into the consumers personal information that is tied to the persons real identity.
  I want to make it more private for the consumer.

The solution will help serve the user owned internet by allowing ease of use by a private account that is used for all Gaia applications.

## Project Overview

> What solution are you providing? Who will it serve?

With the Gaia database, I want to create a crypto exchange that is directed at the Gaia account and not the Legal Person Credentials.

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

Exchange charts for numerous crypto currencies.
Exchange Crypto Wallet & transactions with third party wallets.
Gaia user account only
Daily Exchange results/information.
Buy/Sell/Trade crypto currencies

I will measure success by successful transactions/trades and deposits into wallet.

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

I am self employed and have a budget quota to keep monthly. So I am looking towards a amount of $3000 monthly.

I have worked on capstone projects in the past for Lambda School, so I am thinking for each major component will take at least 2-3 weeks each since I will be an individual developer.

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?

Can this be done as an individual? That is what I want to do, at least for the first few components as a challenge and learning experience. I would not mind having teammates. 
I have operated as a Team lead/Scrum master and Full Stack Web Developer for 1 year at Lambda School. 
I want to learn the skill set of a blockchain developer. I have already started self teaching currently for about 2 months.

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

Interfacing with third party wallets and trading between different crypto currencies.
Backup plans are integrating these dependencies into the application itself using a third party backend separate from Gaia, but still uses authentication of your Gaia account.

## Community and Supporting Materials

> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

Yes I have numerous projects to relate and use to help me. 
I am in the discord community and joined in the mining contest. Had a lot of questions that were answered and opened up my views and connection with the community.
I do plan to share my plan with the community.

**Comment by RaffiSapire** [comment]
Hey @CodeLaryna , would love to learn more about you and what you're hoping to work on here. Could you send me an email at raffi@stacks.org and we can get on a call next week?

**Comment by CodeLaryna** [comment]
Sounds good! Will get in contact with you.

**Comment by friedger** [comment]
Have you looked at the Cerebro Wallet? The exchange could use that data: https://github.com/cerebrowallet

**Comment by CodeLaryna** [comment]
I will add it to documentation! thanks!

**Comment by RaffiSapire** [comment]
Hi there, I haven't received an email but I may have missed it - please resend, let me know who its coming from and I'll keep an eye out.

**Comment by CodeLaryna** [comment]
Decided to put project on ice. Started another project elsewhere.
