### ISSUE TITLE
Multicurrency Neo dapp ( wallet+accouting ) for gig workers/freelancers

### ISSUE THREAD

**Issue by aj07** [stacksgov/Stacks-Grants#39]
## Background

# Problem:

The current payment system is completely broken for gig workers and freelancers. I talked with tons of freelancers and projects owners across south-east Asia and India. 
The three biggest pain point faced by them are :
1. Difficult to track incoming/outgoing digital assets, especially for gig workers who are in crypto.
2. Currency interchange cost: whenever there is an international transaction, there is at least 5% fee
3. No recurring platform for crypto assets

The problem above was discussed mostly by the project owners living in the West and freelancers working from South East Asia and India. 
In fiat ecosystem, there are Xero, QuickBooks for maintaining accounts. But these are mostly for business owners not for gig workers or freelancers.  For the international transaction, they use transferwise and banks which are eating lots of transaction fee.  

A small attempt has been made to solve this problem in HackDefi project( https://devpost.com/software/fistack )

## Project Overview

# Solution:

Provide a multi-currency accounting-wallet where the sender can send any crypto through stack dapp.  This will support multi-blockchain. The user won't be worried about the base layer blockchain. In fiat ecosystem, you can compare with Brex, Revolut where international transaction and accounting both done. 

 This dapp will include
1. The wallet would be multi-currency supported to send and receive digital assets in any blockchain layered platform.
2. It will be integrated with the accounting dapp. User can see the money sent/reive and perform basic functions of accounting app.
3. Added functionality like recurring payment will be made in the next iteration.

## Scope

The end product would include a multi-currency (crypto) wallet with primary accounting feature. The goal is to make it usable by freelancer/gig workers for tracking, sending/receiving money most cheaply with good UX.

Workflow: 
1. User Login in the system, 
2. Top Up their wallet.
3. Store & Send/Recieve the crypto.
4. Maintain personal accounting portfolio.
5. Schedule the payment (extended features for next round of application)

Success will be measured by deliverables and users onboarded.  First four features should be done in terms of product development. Get feedback from beta users and improve it. At the end shill the project with stack network and onboard users.

## Budget and Milestones

I am seeking for 5000USD grants. 

**Time Duration:** 135 hours in 7 weeks.
One hundred hours of dev work; 35 hours of community testing and development. Total work is divided into 4 phases.

**The first phase (10 days):** Wireframe, UX, Multicurrency wallet development work and test with early users which I have talked during customer validation.
**The second phase (15 days):**  Develop basic accounting app for crypto and integrate with first phase work.
**Third phase ( 10 days ):**  Test with coumminty and early beta users. Get feedback and work on improvement according to their feedback. 
**Fourth phase: (5 days):** Shill the project in community with stack foundation and work on adoption. 

## Team

 *Two people ( Full-stack person and designer )*

 Ankit (Full-Stack): Participated in HackDeFi, built Fi_Stack and worn 3rd spot. His profile can be found at aj07.github.io

Other person skills will be to work on the design. Ankit has filtered out some designer and took help one of them in the project.
During 4th phase need help from stack community to assist in marketing and adoption for broader reach.

## Risks

Accounting is challenging for many users.  Non-finance people are not comfortable in using even Xero,QuickBooks. 
This project goal is to build sleek UX by which any individual can do accounting/manage finance.  While doing so, it requires some multiple iterations.  Because of this, I have dedicated some extra time in the second and third phase.

## Community and Supporting Materials

Yes, there is a couple of work done by me in the same theme in the past. 

I have build a similar kind of app(for centralised system)  in the past: YouTube Link: https://www.youtube.com/watch?v=0AIYT4yDM_Q&feature=emb_logo
Market research: https://a4nkit.medium.com/reinventing-the-finance-48c86f2c4246
HackDefi: https://devpost.com/software/fistack

I have been involved in this segment form the last two years. Freelancer/Gig-workers always feel the need for this product. They are using some product in similar vertical in the centralized system, but for decentralized there are none.

**Comment by RaffiSapire** [comment]
Tell us more for gig workers. What is special about the wallet that makes it different than other wallets. How are you using  clarity or gaia or interacting with the protocol?

**Comment by aj07** [comment]
Thanks for asking question @RaffiSapire  Gig workers means short term employees. It can be yoga teacher, music teacher , software developer , designer, math teacher. Anyone who is looking for side gig or unorganized sector employment. And while doing so, they work individually, so for them accounting, banking is difficult.

How this wallet is different from other wallet ?
Wallet alone is not so unique in itself, But with added features, it has lots of use cases. This wallet will have name service facility with accounting features. (Later we will put recurring payment service also). 

This dapp will be used on stack layer. 
It will be integrated with on-off ramp service, which will change for changing fiat-other crypto ton STX. Later, when stack foundation builds cross-chain support, then it will be removed.

**Comment by friedger** [comment]
@aj07 Have you looked at https://github.com/cerebrowallet? Could the accounting feature an add-on to cerebro wallet?

**Comment by aj07** [comment]
@friedger Thanks for commenting!!

I have seen cerebo wallet which is really nice. But this wallet would be different from it. Here, name service (like Ethereum Name service, fiat on -off ramp service )  along with accounting would be available. 

Also, I can see the last commit done there was around 6 months back. Not sure, about their current development.

**Comment by friedger** [comment]
@aj07 Even more a reason to take up that work and build on top I think. Would adding more feature to celebero work?

Furthermore, how do you see integration with the Stacks Wallet? Will you manage private keys?

**Comment by aj07** [comment]
Yeah @friedger , that's definitely a good idea to start the work.  I have gone through it. Good work has been done there.


Stack wallet: We will be just integrating wallet to dapp. We will not store any pvt keys. It would be managed in decentralized way by users.

**Comment by aj07** [comment]
Hi @RaffiSapire !!

Any feedback for this.  ?

**Comment by RaffiSapire** [comment]
Hi there, this is approved, the grant will be disbursed via milestones, and I've clarified a few deliverables for each:

The first phase (10 days): $1000 Wireframe, UX, Multicurrency wallet development work and test with early users which I have talked during customer validation. _This hifi mockup could be shared back on the Feb 11 community call along with user feedback from a handful of user tests_

The second phase (15 days): $3000 Develop basic accounting app for crypto and integrate with first phase work. _All these features will exist: 
User Login in the system,
Top Up their wallet.
Store & Send/Recieve the crypto.
Maintain personal accounting portfolio.
Schedule the payment (extended features for next round of application)_

Third phase ( 10 days ): $1500 Test with community and early beta users. Get feedback and work on improvement according to their feedback. 
_This could result in user studies for at least 10 people, with research that is shared back and presented during community call, recommended updates, and implemented updates._ 

Fourth phase: (5 days): $500 Shill the project in community with stack foundation and work on adoption.
_Instead of "shill the project" I'd get concrete about goals on usage here (e.g. number of sign ups, number of comments on this github with feedback, usage metrics). The $500 is disbursed when those goals are achieved._ 

If you disagree with any of the specifics here, please do respond here with your adjustments. Else, please email me at raffi@stacks.org and we'll get you set up!

**Comment by aj07** [comment]
Connecting via mail..

**Comment by RaffiSapire** [comment]
Hi there! I haven't received an email, please could you send, or re-send if you haven't, or ping me on discord if you're having trouble getting it to me?

**Comment by aj07** [comment]
Hi!!

Mailed you again. Whats your nick name on discord ?

**Comment by p2pvid** [comment]
The latest development about work for Module 1 (Workflow, Wireframe and User feedback )  is updated here 
https://github.com/stacksgov/Stacks-Grants/issues/39

**Comment by RaffiSapire** [comment]
Hi @aj07 , thanks! Was expecting the wireframe to be done hi-fi mockup in figma or another platform for the amount that we've granted here.

**Comment by RaffiSapire** [comment]
Hi @aj07, I wanted to check in to see, is this update something that you are going to complete?

**Comment by RaffiSapire** [comment]
Hi @aj07 please let us know by Friday if you plan on completing this with an updated timeline, else we will mark as closed.
