### ISSUE TITLE
Stackedsats Marketing Campaign 

### ISSUE THREAD

**Issue by fintechrecruiters** [stacksgov/Stacks-Grants#40]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> **What problems do you aim to solve? How does it serve the mission of a user owned internet?**

Our Stacking pool platform called Stackedsats provides current STX token holders and crypto users who are new to the Stacks ecosystem, a non custodial solution to earn bitcoin if they do not meet the current threshold for btc rewards. Here's a quick snapshot of what Stackedsats provides:

1) A stacking pool service that allows Stackers to pool their STX with other in order to earn bitcoin if they do not have the minimum requirements needed.

2) The only stacking pooled service (that we know of) that is built with privacy design principles in mind. Our platform also supports and integrates with other Stacks apps such as Blocksurvey (used in our forms) Sigle (our blog) and Stacks Connect ID  for our login and password functions. 

3) Educational marketing campaigns to crypto users who are not yet familiar with Stacks and are currently participating as "stakers" in other blockchain ecosystems. These marketing efforts will increase the number of crypto users who own STX and in turn they will help further secure the Stacks network by stacking their STX tokens.

4) Stacks brand exposure to non-stackers who join our stacking pool. By reading our blog, they will learn about digital identity and online privacy tools. They will come for the bitcoin rewards and stay for the community.

5) A gateway to new Stackers to particpate in the larger Stacks ecosystem by creating links and buttons to other builders in the Stacks ecosystem. For example, we have included a "become a STX miner" button in the dashboard which will redirect people to the Daemon Technologies for STX mining information.  There is also a tab for Freehold in the dashboard that provides various Freeholder statistics that relate to stacking and hodling bitcoin and stacks. Links to the Stack Foundation, Hiro Systems and other Stacks resources will also be included on the bottom of each blog post.

## Project Overview

> **What solution are you providing? Who will it serve?**

We have built a non-custodial Stacking pool platform for STX token holders who believe that every individual, regardless of where they live, should have the right to perserve their wealth and retain their digital identity and online privacy. We have created a platform based on privacy by design principles and a belief that bitcoin can help millions of people around the world retain and even grow* their hard earned savings from the thievish effects of inflation.

Our site contains a blog that educates our audience about the role of decentralized tools, bitcoin and cryptocurrency in promoting economic empowerment and freedom for people of all walks of life around the world.  See our content plan for a breakdown of upcoming blog posts here: https://docs.google.com/document/d/1kxN1IYOsv4etamXoVB-3Eo0EIDeHnBvUrjytjaqlYCQ/edit?usp=sharing

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The specs of the project contain a website, blog, stacking dashboard, calculator and marketing campaigns. Note: Our website is the landing page that is connect to our Mining and Stacking Analytics formerly called the Stacks Monitor under grant #21 

Here is the website landing page https://www.stackedsats.com/ 

We will measure success based on the number of people who sign up to our platform. Our goal is to sign up 300 users in the in the first phase of our launch (month of Jan) and 200 in phase two (Feb - end of March). Totally 500 users.

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

I am seeking $4545
 dollars for Stackedsats a design and marketing campaign.

Website design visuals only (43 hours) - $1720 
Website frontend including (25 hours) - $ 1375
Marketing kit: icons, cards, poster, overall visual design - ( 25 hours) $1000
12 blog posts (including research) ( 24 hours) $1068
Explainer video and YouTube promos - $500 per video or 3 influencers =$1500 (outsourced)
Social media marketing platform Business version (gleam) - $150 per month x 3 months = $450 (re-evaluate after 3 months)
**Total cost: $4545**

**Milestone 1**
Website design (43 hours) = **$1720** 
Website frontend (UI/UX) (25 hours)= **$1375**

**Milestone 2**
Social media - viral marketing platform - **$450**
Marketing kit (graphics and icons on the site): **$1000**

**Deliverables**: live website at https://www.stackedsats.com/  
Marketing kit (graphics and icons on the site):and link to the social media posters and cards:
https://www.notion.so/Stacks-bull-card-design-poster-1-e88e0840f0984769a0e4b631f1a34144
https://www.notion.so/Stacks-bull-card-design-poster-2-704883bbdac44866a6567b50072ad044
https://www.notion.so/Stacks-bull-card-design-poster-3-f6c02d3341a84d72805987d38a4c1665
https://docs.google.com/document/d/1kxN1IYOsv4etamXoVB-3Eo0EIDeHnBvUrjytjaqlYCQ/edit?usp=sharing
https://www.stackedsats.com/blog

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?

Nako Mbelle
Nako is a fervent believer in community driven technology that empowers and promotes the sovereign right of the individual to shape their digital lives. She's the Founder of Fintech Recruiters, a niche recruitment agency that specializes in blockchain, crypto and Fintech jobs.

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
The dependencies of the project are based on the mainnet and Dashboard launch. The website is already live. 
My contingency plans are to announce via Twitter updates on the launch if there are setbacks. Risks are mainly based on timelines of the completion of the Stackedsats dashboard and users will be notified of postponed date. 

## Community and Supporting Materials

> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?
This project is tied to Grant #21 and I have shared screenshots of the project via Discord in the Business Model channel and in Freehold.

**Comment by RaffiSapire** [comment]
Hi there, could you please reach out via email and lets find time to sync and talk about this grant and grant #21? Thank you, Raffi. We're not comfortable providing a grant for marketing for a product that isn't built, however, we are really excited about finding the right way to have you engaged in the grants program.

**Comment by RaffiSapire** [comment]
Hi @fintechrecruiters please email me at raffi@stacks.org, we would love to find a way to support you.

**Comment by fintechrecruiters** [comment]
Update on StackedSats project.

Hello Fellow Stackers,

I hope this message finds you doing well.

1) As you have all witnessed, the value of bitcoin has skyrocketed and as a result a lot has changed in the marketplace. In Canada (where I live) a bitcoin ETF has been approved and will be launching very soon.  Large players like Tesla and Old Mutual now have bitcoin on their balance sheets.  

2) The entrance of these high profile companies and investors have brought extra scrutiny and regulatory oversight to all businesses who touch cryptocurrency in any shape or form; this includes StackedSats. Our regulators in Canada are tightening up regulations based on these seismic changes that have happened over the past few months. 

3) As a result of these changes, I have decided to open up the platform to everyone and not to run it as a business anymore. This means there will be no fees associated with participating in this pooled service. By making Stackedsats 100% community owned and operated, there will be less exposure to the regulatory risk that a for-profit project entails. 

4) The platform is still in very early beta, but there is enough of a foundation built that a combined community effort can get it fully functional. Friedger has been incredibly helpful in the past 6 weeks and his contribution to the platform has helped my developer get it to where it is now. 

5) We hope the community will join us in merging Friedger's pooling initiative with StackedSats because this project will now belong to you ---the Stackers. 

6) But as with all open source projects, we now face the challenge of pulling all of the pieces together and making it work for everyone involved.

The developer is finishing off a few things and will push the code out to the repo along with the documentation later today. Everything associated with the project will be open source.  I'll send a separate email with the announcement.

Thank you for your patience and I look forward to continuing this journey alongside you as an equal participant and not as a service provider.

Onward and Upward,
Nako

**Comment by fintechrecruiters** [comment]
Open source code of StackedSats found here:https://github.com/StackedSats (7 repos in total)

**Comment by fintechrecruiters** [comment]
This issue will be closed because marketing will be done by community members.
