### ISSUE TITLE
[Wishlist] Decentralized exchange for Stacks tokens (ie Uniswap)

### ISSUE THREAD

**Issue by jeffdomke** [stacksgov/Stacks-Grants#45]
**Background**

In the next year we’ll likely see 100s of new protocols, products, and services built on Stacks—many will introduce novel token economics and growth strategies. That is why we need a decentralized exchange (DEX) to supply these projects with liquidity and support many new innovative tokens. 

We’ve been able to learn a lot from other ecosystems, so there are great examples to study. For example, [Uniswap was originally an Ethereum Foundation grant](https://esp.ethereum.foundation/en/projects/uniswap/). Also see [Swapr](https://github.com/psq/swapr), a proposed exchange created by [Pascal](https://github.com/psq) during our Clarity hackathons. 

**Project Overview and Milestones**

**Phase 1: Design**

In the design phase teams will share their exchange design with the Stacks community. Plans should include how the DEX plans to attract liquidity, new assets, and new users:

- Basic DEX functionality:
    - Price discovery
    - Direct swaps between fungible Stacks tokens
    - Automated market making mechanism
- Detailed paper rigorously describing the protocol’s design and system properties, and presenting detailed token economics.
- Public announcement of project.
- Protocol design must be fully-distributed and resilient to reasonable node failure modes.  It must account for economic risks, and incentivize long term network participation. 
- Bitcoin and Stacks community evangelism is encouraged. 

**Phase 2: Build**

In the build phase the winning team implements their solution in code:

- Smart contracts published on testnet.  
- Security audits performed. 
- Entire protocol is functional and can be tested. 

**Phase 3: Launch**

In the launch phase, teams launch a completed decentralized exchange product for use on the STX blockchain:

- Smart contracts and node software in production. 
- High quality web client must be able to interface with existing Stacks wallet(s). 
- Ability to swap two Stacks based tokens. 
- A successful public launch. 

**Recommended team**
This project will require expertise in token economics, smart contracts, user experience, and marketing. Launching and growing liquidity will take many months. An experienced team with a diverse skill set and a long-term vision to build a business is encouraged. 

**Recommended grant** 
- I suggest breaking down the project into milestones with evaluation criteria and specific grant awards for various phases such as design, successful launch, etc. 
- $50,000 + security audit costs

**Comment by CodeLaryna** [comment]
Hiya, I was wondering if I could hop on the team. I am eager to learn blockchain technology, and already had a similar proposal(https://github.com/stacksgov/Stacks-Grants/issues/38).

**Comment by jeffdomke** [comment]
@CodeLaryna this is a wishlist grant so I'm just suggesting that some team take this on.

**Comment by RaffiSapire** [comment]
@CodeLaryna https://grants.stacks.org/proposals/1370316309-decentralized-exchange-for-stacks-tokens-ie-uniswap?tab=discussions 

Please hop in here!

**Comment by oiclid** [comment]
@jeffdomke Can more than one of these projects run at the same time?

**Comment by louiseivan** [comment]
When Swapr? This is very much needed. Thanks putting this together @jeffdomke

**Comment by PureF** [comment]
Is this funded? Is Swapr building it?

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
