### ISSUE TITLE
OpenRiff - Marketplace for collectibles

### ISSUE THREAD

**Issue by friedger** [stacksgov/Stacks-Grants#5]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> What problems do you aim to solve? How does it serve the mission of a user owned internet?

![Screenshot from 2020-09-04 13-45-30](https://user-images.githubusercontent.com/1449049/92241968-604c5180-eebf-11ea-922b-85174223f22e.png)

Physical and digital goods can be represented by non-fungible tokens on the chain to manage ownership (and other features). This can be names of BNS, virtual monsters or companies. To exchange these goods freely a marketplace is required that works without interference of the token creator or marketplace developer.

## Project Overview

> What solution are you providing? Who will it serve?

The goal of the project is to create a marketplace that can be used by all users who want to participate in the exchange of digital goods represented by non-fungible tokens living on the stacks chain. The marketplace contract is open and gives the users a choice of apps how to join the marketplace.

Think of small version of OpenSea for STXs.

The project is educational in the sense that 
* it should teach normal users what it means to own their digital goods.
* it should teach assets creators what the same current "standards" are and/or encourage them to give input on the standards
* it should teach wallet creators how to display digital goods. 

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

The [OpenSea project](https://docs.opensea.io/) provides a great set of resources for this project. Furthermore, there is a [marketplace contract](https://github.com/friedger/clarity-marketplace) in clarity and an educational app [Speed Spend](https://github.com/friedger/speed-spend/).
We will reuse as much as possible.

### Smart Contract
The core of the marketplace is a smart contract defined in https://github.com/friedger/clarity-marketplace . It following functions exists already: 
* offer an NFT publicly for sale
* bid for an NFT publicly
* accept a bid
* pay for an accepted bid

**Tasks of this project**
* extend the contract to set constraints that bids are placed, accepted and paid with fixed time frames. 
* provide more unit tests
* publish documentation of the trait that NFTs must implement so that they can be traded on the marketplace.

Out of scope is 
* flexible time frames for the bidding process
* crowd sales

### App
One web application will be built in react and connect that interacts with the smart contract. It provides UI for
* listing owned NFTs and offer them for sale
* listing NFTs that are offered by their owners and corresponding bids (if public)
* biding for an offered NFTs
* accepting bids (by the owner)
* payment processing in STXs

The app will be based on (OpenSea Whitelabel](https://github.com/ProjectOpenSea/opensea-whitelabel).

The app will not be related to OpenSea marketplace other than that UI looks similar.

**Tasks of this project**
* adapt opensea white label app to stacks chain and contracts, remove ethereum references.
* deploy the app
* exercise with monster NFTs defined on https://github.com/friedger/clarity-marketplace

Out of scope is 
* Payment processing in fiat via stripe
* Business model for maintaining the marketplace app

### Educational material
To engage the community into the project, I propose to have a weekly session of 30 minutes explaining/discussing the following topics related to NFTs and marketplace:

1. What is an NFT? What Can You Do With It? - explaining the simple-market contract
1. NFT Meta Data - Where to Store and How? - discussing different options and agreeing on the one used for OpenRiff
1. Integrating NFTs into a web app - explaining how to query ownership and history, using stacks-blockchain-api-client

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Budget: 800$

* Milestone A: 100$
Listing offers, bidding and finishing deals are functional on Speed Spend
Session 1

* Milestone B: 500$
App with basic functionality deployed under beta domain
Session 2

* Milestone C: 200$
Polished app removing unsupported features adding more branding deployed under final domain
Session 3

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?

I am building it together with a designer from the community. Hopefully, we will receive pull requests from the community as well.

I have build [Speed Spend](https://speed-spend.netlify.app) that includes the monster NFTs and a first start to integrate the marketplace.

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

The design of the marketplace contract could create too many transactions on the chain. If this happens the app would switch to a new contract, support off-chain deal making and only submit one transaction for the change of ownership.

Blockstack engineers don't have time to fix bugs or review pull requests or publish new release of libraries used in the web app. If this happens we would open a new grant proposal here to improve the situation :-)

## Community and Supporting Materials

> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

First reactions on Telegram:
![Screenshot from 2020-09-04 12-56-39](https://user-images.githubusercontent.com/1449049/92232063-24f55700-eeae-11ea-82d2-05a4b6e66883.png)

Speed Spend Source code: https://github.com/friedger/speed-spend

[Video of current state at Speed Spend mainly about NFTs](https://www.youtube.com/watch?v=V3jA5jcPTkM)

[OpenSea Whitelabel](https://github.com/ProjectOpenSea/opensea-whitelabel)

**Comment by friedger** [comment]
Closed in favor of #12

**Comment by friedger** [comment]
I reopen it to have an alternative proposal

**Comment by friedger** [comment]
Re-reading #12 again, I think both proposals are connected but are different that OpenRiff focuses on a general marketplace while Loopbomb focuses on creating NFTs.

**Comment by blocks8** [comment]
**Review Committee Feedback from 9/8/2020: We'd like more information on your proposal.**

Thank you for your application! We are excited to see the possibilities inherent in bringing OpenSea to the Stacks Ecosystem. As a next step, we’d like to see a little more information on how the smart contracts would work with OpenSea. It wasn’t clear if you would build the STX smart contracts into OpenSea, or create OpenRiff as a similar marketplace to OpenSea just for STX. If it’s the latter, what type of users and use cases would exist on the new OpenSea app? 

We’d also encourage you to add the steps you could take to showcase the completed smart contracts and apps to others in the ecosystem. Could you showcase the demo you have from the previous hackathon to get feedback on the types of use cases others in the community may use? Would you be able to demo the use of your smart contracts to other builders who may want to offer NFTs? 

We’re excited to have you continue to build in the ecosystem! 

If you would like to update your proposal with the above feedback, you may do so as a reply to this comment or edit the original application entry above.

**Comment by friedger** [comment]
I have updated the proposal 
* to clarify that OpenRiff is a small version of OpenSea for STX
* with a set of weekly sessions discussing NFT related topics (as part of the milestones)

**Comment by blocks8** [comment]
**Review Committee Feedback from 9/15/2020: Scoped and approved.**

Hi @friedger - We're pleased to approve this grant proposal for $800 which will result in: 

- Listing offers, bidding and finishing deals are functional on Speed Spend
Session 1
- App with basic functionality deployed under beta domain
Session 2
- Polished app removing unsupported features adding more branding deployed under final domain
Session 3
- Weekly discussions on NFT

We'd like to highlight your work through two blog posts to share with the community, one update mid-way, and another once this grant is completed. We'll add an additional $200 to bring the total funding to $1,000 for this additional work. 

As a next step, please send an email to grants {at} stacks {dot} org with your preferred email and name. We'll send over a contract to complete the grant agreement, followed by funding. We're also happy to help work on promoting the weekly discussions among the community. 

Thank you!

**Comment by friedger** [comment]
As @mijoco pointed out, the referenced opensea whitelabel repo is only an iframe around the real opensea site which is closed sourced.Therefore, instead of using the open sea white label, I will use the https://github.com/decentraland/marketplace

**Comment by blocks8** [comment]
Grant Funded! 
$1000 which will result in: 
Listing offers, bidding and finishing deals are functional on Speed Spend
Session 1 : App with basic functionality deployed under beta domain
Session 2 : Polished app removing unsupported features adding more branding deployed under final domain
Session 3 : Weekly discussions on NFT
Two blog posts to share with the community, one update mid-way, and another once this grant is completed.

**Comment by RaffiSapire** [comment]
Hi, reopening this, was closed by mistake. @friedger, when do you think is a good week to aim to share the mid-way blogpost?

**Comment by friedger** [comment]
Just to clarify that the Milestones are
- M1: 
   - Listing offers, bidding and finishing deals are functional on Speed Spend
   - Session 1: NFTs - Storing Digital Items on Chain
- M2:
    - App with basic functionality deployed under beta domain
    - Session 2: NFTs - Which Standard to Use
-M3:
     - Polished app removing unsupported features adding more branding deployed under final domain
     - Session 3


Re Progress:
M1: The Session1 was held on last Thursday. Contributed some fixes to Connect to make it use on krypton testnet.

**Comment by friedger** [comment]
Mid-way blog post should be good next week.

**Comment by friedger** [comment]
Slides of the weekly sessions are published on https://www.tofauti.net

**Comment by RaffiSapire** [comment]
Hi @friedger , thank you for summarizing the milestones above. Are M1 and M2 complete, and you're working on M3? Will make sure we've disbursed 1/3 for each Milestone.

**Comment by friedger** [comment]
Due to issues with Connect and the testnet, the project is a bit delayed. M1 is completed by now, the marketplace is working on the Speed Spend web app.

**Comment by friedger** [comment]
I would like to put this proposal on hold or revert it altogether.

After completing the three sessions about NFTs and after working on the code, I currently don't want to finalize the marketplace according to milestone 2 and 3. There are still too many uncertainties in how NFTs will be used on the Stacks chain. I think I can use my resources better in educating other developers about NFTs and Clarity in general (like the [stacks api client tutorial](https://github.com/blockstack/docs/pull/791)) or extending Speed Spends, e.g. its marketplace feature using sponsored txs or multi-signature transactions.

**Comment by blocks8** [comment]
Hi @friedger - I'll message you to find time so we can discuss next steps.

**Comment by friedger** [comment]
I created a separate page on Speed Spend for Open Riff: https://speed-spend.netlify.app/openriff

This concludes this project for now. For now, there won't be more work on a new UI for the marketplace. All further standards and feature will be first added to Speed Spend's Open Riff page

The payment for M2 and M3 ($666) will be returned or directed to a different proposal.
