### ISSUE TITLE
Grants site SEO shows old logo

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/Stacks-Grants#51]
Similar to #50, caught this during the ecosystem update.

![20210121_001_Selection](https://user-images.githubusercontent.com/9038904/105370237-9c5b2700-5bc0-11eb-95dd-f1452c632ada.png)

**Comment by ryanarndtcm** [comment]
thanks! working on this with the developer. :)

**Comment by ryanarndtcm** [comment]
complete :)
