### ISSUE TITLE
Gaideo Mobile

### ISSUE THREAD

**Issue by models-72** [stacksgov/Stacks-Grants#53]
**Background**

There are two important issues with video streaming from Gaia storage on mobile devices.  Videos cannot be decrypted in a browser when running on an iPhone, and for both iPhone and Android the video encryption performance is very slow because of the fact that transcoding is running in javascript instead of natively.  Since video creation and consumption largely happens today on a user's phone, it is important to make streaming on Gaia storage as accessible as possible to the stacks user base.  Additionally the performance benefits to running natively will help increase adoption for impatient users.

**Project Overview**
The proposed solution is to create two mobile apps for Gaideo, one for iPhone and one for Android.  In order to leverage the existing functionality already built, the plan is to host a WebView to gaideo.com, with hooks into the web application to handle transcoding natively, and for iPhone to override video streaming requests in order to do decryption.

**Scope**
Two new public github repos will be created, one for the iPhone application (Gaideo.IOS) and one for the Android application (Gaideo.Android).  Each application will be implemented using a cross platform technology stack of Xamarin and C#.  

The final success criteria will be the following:

1. Both mobile applications in their respective app stores
2. Both mobile applications capable of transcoding/encrypting video natively
3. The iPhone application will be able to play encrypted HLS videos stored on Gaia

**Budget and Milestones**

Total Grant Request: $13600

M1: (~40 hours - $3400)

- Prepare the development environment on Windows
- Setup VS Code with new Xamarin projects
- Setup phone emulators
- Prepare development environment for iPhone using Mac-MIni
- Create working application that hosts a web view to gaideo.com for each platform
- Changes will need to be made to the Gaideo web application to detect that it is running in a web view
- implement UI specific to mobile apps for the back button and refreshing when the web application is running in a WebView

M2: iPhone app with native FFMPEG (~40 hours - $3400)

- Implement script messaging layer between the Gaideo web application and the native iPhone application.
- Use messaging layer to execute FFMPEG natively instead of using the javascript FFMPEG library
- Use messaging layer to communicate the file outputs to the web application when running FFMPEG natively

M3: Android app with native FFMPEG (~40 hours - $3400)
- Implement JS bridge messaging layer between the Gaideo web application and the native Android application.
- Use messaging layer to execute FFMPEG natively instead of using the javascript FFMPEG
- Use messaging layer to communicate the file outputs to the web application when running FFMPEG natively

M4: iPhone app support for decrypting Gaia video stream segments and publish both applications (~40 hours - $3400)
- Join the Apple Developer Network needed for publishing to the apple store
- Use messaging layer to communicate Gaia location and crypto information from the web application to the host native application
- Implement custom scheme handler to intercept video requests and decrypt video segments on the fly
- Testing on emulator and physical devices
- Apply for approval of iPhone app to the Apple store
- Apply for approval of Android app to Google Play store

Duration: 4-8 weeks

**Team**
I will be the only developer on the team.  I have completed previous grants with the foundation related to Gaideo (#4 and #31). 

**Risks**
I do not anticipate any significant risks or obstacles to this project, other than the unknown for what is involved in getting final approval for each application in their respective app store.

**Community and Supporting Materials**

There is a public github repository for my previous grant work at: https://github.com/gaideo/gaideo and you can visit https://gaideo.com to see the current state of Gaideo's web application

**Comment by RaffiSapire** [comment]
Hi there, the main feedback we have here is twofold:
1. We'd encourage you to pick one of these: android, ios or desktop, and do it really well, and build a killer dapp first, before making it compatible across all platforms.
2. We'd like to learn more about the usage to date. Do you have metrics on monthly / weekly usage, and how that has trended month over month since completing the second grant? 
Thank you!

**Comment by models-72** [comment]
I would say that iPhone would be the best platform to start with since it is the most privacy focused and currently Gaideo will not work completely using the web application on that platform.  One thing to keep in mind with Gaideo and usage statistics is that the web application is written in React as a single page application.  Once a user has downloaded and cached the application everything runs client-side in javascript with most if not all of the HTTP traffic going to Gaia storage, unless a user specifically navigates in the address bar or refreshes the browser.

Here are some stats on gaideo.com for the month of February:

**Reported period	Month Feb 2021**
First visit	01 Feb 2021 - 03:25
Last visit	25 Feb 2021 - 05:50

Unique visitors: **157  (Jan 2021: 133, Dec: 2020: 76)**
Number of visits: **218**
Pages: **4141**
(1.38 visits/visitor): **1,265**
(5.8 Pages/Visit): **4,141**

<table>
    <tr>
        <th>Locales</th>
        <th>Pages</th>
        <th>Hits</th>
    </tr>
    <tbody>
        <tr>
            <td>United States</td>
            <td>1,093</td>
            <td>3,372</td>
        </tr>
        <tr>
            <td>China</td>
            <td>34</td>
            <td>62</td>
        </tr>
        <tr>
            <td>Great Britain</td>
            <td>24</td>
            <td>99</td>
        </tr>
        <tr>
            <td>Russian Federation</td>
            <td>13</td>
            <td>47</td>
        </tr>
        <tr>
            <td>Poland</td>
            <td>12</td>
            <td>48</td>
        </tr>
        <tr>
            <td>Sweden</td>
            <td>8</td>
            <td>11</td>
        </tr>
        <tr>
            <td>Austria</td>
            <td>8</td>
            <td>55</td>
        </tr>
        <tr>
            <td>India</td>
            <td>6</td>
            <td>34</td>
        </tr>
        <tr>
            <td>Germany</td>
            <td>6</td>
            <td>24</td>
        </tr>
        <tr>
            <td>Australia</td>
            <td>5</td>
            <td>30</td>
        </tr>
        <tr>
            <td>Spain</td>
            <td>5</td>
            <td>26</td>
        </tr>
        <tr>
            <td>South Africa</td>
            <td>4</td>
            <td>4</td>
        </tr>
        <tr>
            <td>Belgium</td>
            <td>4</td>
            <td>7</td>
        </tr>
        <tr>
            <td>Netherlands</td>
            <td>4</td>
            <td>16</td>
        </tr>
        <tr>
            <td>Pakistan</td>
            <td>4</td>
            <td>15</td>
        </tr>
        <tr>
            <td>Angola</td>
            <td>4</td>
            <td>21</td>
        </tr>
        <tr>
            <td>Kenya</td>
            <td>3</td>
            <td>15</td>
        </tr>
        <tr>
            <td>Turkey</td>
            <td>3</td>
            <td>29</td>
        </tr>
        <tr>
            <td>Romania</td>
            <td>3</td>
            <td>13</td>
        </tr>
        <tr>
            <td>Guatemala</td>
            <td>3</td>
            <td>17</td>
        </tr>
        <tr>
            <td>Japan</td>
            <td>3</td>
            <td>40</td>
        </tr>
        <tr>
            <td>Portugal</td>
            <td>3</td>
            <td>11</td>
        </tr>
        <tr>
            <td>South Korea</td>
            <td>2</td>
            <td>9</td>
        </tr>
        <tr>
            <td>Greece</td>
            <td>2</td>
            <td>4</td>
        </tr>
        <tr>
            <td>Italy</td>
            <td>2</td>
            <td>4</td>
        </tr>
        <tr>
            <td>Guatemala</td>
            <td>3</td>
            <td>17</td>
        </tr>
        <tr>
            <td>Others</td>
            <td>7</td>
            <td>128</td>
        </tr>
    </tbody>
</table>

**Comment by models-72** [comment]
Here are some updated milestones without Android in the mix:

Total Grant Request: $10200

M1: (~40 hours - $3400)

- Prepare the development environment on Windows
- Setup VS Code with new Xamarin projects
- Setup phone emulator
- Prepare development environment for iPhone using Mac-MIni
- Create working application that hosts a web view to gaideo.com for each platform
- Changes will need to be made to the Gaideo web application to detect that it is running in a web view
- implement UI specific to mobile app for the back button and refreshing when the web application is running in a WebView

M2: iPhone app with native FFMPEG (~40 hours - $3400)

- Implement script messaging layer between the Gaideo web application and the native iPhone application.
- Use messaging layer to execute FFMPEG natively instead of using the javascript FFMPEG library
Use messaging layer to communicate the file outputs to the web application when running FFMPEG natively

M3: iPhone app support for decrypting Gaia video stream segments and publish both applications (~40 hours - $3400)

- Join the Apple Developer Network needed for publishing to the apple store
- Use messaging layer to communicate Gaia location and crypto information from the web application to the host native application
- Implement custom scheme handler to intercept video requests and decrypt video segments on the fly
- Testing on emulator and physical devices
- Apply for approval of iPhone app to the Apple store

**Comment by MarvinJanssen** [comment]
Hi @models-72, I am helping out at the Stacks Foundation. A couple of things that came up whilst reviewing your proposal:

- We feel that M1 is overestimated. We would like to understand where the 40 hours are coming from, as it looks to be mostly preparation work. There are many WebView samples projects out there.
- As mentioned prior by @RaffiSapire, focusing on a single platform like iOS or Android will probably help scope this project, before making it compatible across different platforms.
- We would like to hear more about the chosen approach, why a WebView over a native implementation?
- [Apple’s App Store policies](https://developer.apple.com/app-store/review/guidelines/#minimum-functionality) generally disallow apps that merely feature a WebView. What are your thoughts on this? We think an open source iOS library that can read & stream content from Gaia with a reference app implementation would be a lot more useful to people at this stage.

**Comment by jennymith** [comment]
Hey @models-72 thanks for your response! I think there are a few points here worth discussing on a call. Will you please email me at jenny@stacks.org to set up a time? Thanks!

**Comment by friedger** [comment]
What about a "creator" app that has a minimalized native UI for encoding and uploading, then the view can just use the web app.

**Comment by models-72** [comment]
The creator app would solve the problem of performant encoding on the device you will most likely have your videos.  But it still won't play on an iPhone if the video is encrypted.  You need special hooks into the video player that uses a custom scheme handler to override the stream segment requests being done by the video player and perform the decryption from Gaia storage using the Stacks users private key or a shared private key.  On other platforms than iPhone you can achieve this in a web app using Media Source Extensions which is supported in most browsers.  It even works on an iPad but not an iPhone.
