### ISSUE TITLE
Stacks Trade "Giveaway and Tips"

### ISSUE THREAD

**Issue by mardi00** [stacksgov/Stacks-Grants#68]
**Background**

I am managing with the help of some other community members:
- https://twitter.com/StacksTrade
- https://t.me/StacksTrade

About me: I am a software engineer currently living in Zurich and I have participated to the app mining program one year ago with: 
- https://www.youtube.com/watch?v=qYpBxF0ovF4&ab_channel=BeehiveDapp

I am following Blockstack since 2016 and I love it.

While mostly the focus is on builders, I believe investors, traders, etc. are an extremely important part of the ecosystem. I believe that bull markets are the best period to convert/attract community members. If you look at the Blockstack community, lot of people were considering themself as investors or traders before becoming valuable community members.

**Project Overview**

I am looking to do very simple things which can increase the influence of Stacks Trade on Twitter and more globally of the Stacks ecosystem:
- Tips in STX
- Giveways of STX
- Puzzles with rewards in STX
- Small airdrops of STX
- Donations 
- etc.

I just want to precise that the FULL grant will be used for this and I will not charge anything for my time.

Here is some examples:
- This account https://twitter.com/STXbot created a bot to post the price of STX daily on Twitter, I would like to tip 5 USD.
- https://twitter.com/badhop0603 created a document in Japanese to describe Stacks, I want to tip 5 USD
- Someone post a really good meme related to STX, I will tip 5 USD
- Do a 150 USD giveway when the account reach 1500 followers
- etc.

All the tips/giveaways etc. will be in STX and public with a cool message. I will always post the transaction link from the Stacks explorer publicly. This is done to reward small independent initiatives.

**Scope**

No technical spec. To be honest I just want to test this, so it will be only one month for now. The goal is to increase the influence of StacksTrade and more globally of the Stacks ecosystem.

**Budget and Milestones**

It will be only one test milestone for now since I am not sure of what would be the impact.
I would like to do in the next 30 days:
- 60 tips of 5 USD = 300 USD (average of 2 per day)
- 150 USD giveaway for the 1500 followers  
Total Grant Request: 450 USD

**Team**
Probably only me for now

**Risks**
None

**Community and Supporting Materials**
None

**Comment by louiseivan** [comment]
Thank you for building the trader community. You guys made so much impact for such a little time. From increasing social volume and positive sentiment around $STX on Twitter to lowering down the fees in Binance & KuCoin. All with the community power.

Kudos to you guys. Looking forward to seeing more.

**Comment by friedger** [comment]
How does the tipping work? Just a request via DMs?

**Comment by espadon8004** [comment]
Actually I am not sure "tip" is not the appropriate word. It's more like a small donation. If there is a cool content I will just post a comment for example "Hey nice meme, update your profile with a STX donation address and I will pay you a coffee". Once done and I will transfert the funds and publish a comment with the tx link from the Stacks explorer. All this process will be manual for now.

**Comment by espadon8004** [comment]
Update: https://github.com/stacksgov/Stacks-Grants/issues/59#issue-818117383 

Just saw this grant request, and that's awesome. I will just wait until it is released, it will be much better.

**Comment by mardi00** [comment]
Actually I am not sure "tip" is the appropriate word. It's more like a small donation. If there is a cool content I will just post a comment for example "Hey nice meme, update your profile with a STX donation address and I will offer you a coffee". Once done and I will transfert the funds and publish a comment with the TX link from the Stacks explorer. All this process will be manually (for now).
As I say it's just an experiment, I just want to see how people react, if they are more active after that, if some other people will tag me on their tweets/content hoping to get a free coffee, if this increase followers acquisition, etc. I don't have any precise goal or target to reach.

Edit: Just checked online, tip is actually the appropriate word :)
Edit 2: Just saw: https://github.com/stacksgov/Stacks-Grants/issues/59 and it's really cool, I will just wait until it's released

**Comment by RaffiSapire** [comment]
Hi there, this is approved. What we'd like to do is also ask that you share back the following upon completion:

here’s what happened: where did you post, what audiences, how did you reach them? here’s what I did, and here is what I learned. Meaning, what worked, what didn't, what surprised you, what resonated with the audiences? We can pay you in USD currently, or if you wait a couple weeks we can pay you in STX to distribute. 

Please email me raffi@stacks.org with the following so we can get you set up on bill.com
1. Name/email for the contract:

2. Bill.com info:
Name, email, country of bank, country of individual

**Comment by mardi00** [comment]
Awesome thank you to support this :) I can wait couple of weeks, not an issue. I will not do the 150 USD giveaway and focus only on the tips.

**Comment by RaffiSapire** [comment]
Hi there @mardi00 sorry if I've missed it in my inbox but I don't see an email from you. Please email me at raffi@stacks.org and we'll get you set up.

**Comment by mardi00** [comment]
Hi sorry my bad, I forgot. I will email you now. Thank you.

**Comment by RaffiSapire** [comment]
@mardi00  is this grant gating on STX Me? If so, we'd prefer to wait til that is complete before funding this grant.

**Comment by RaffiSapire** [comment]
@mardi00 please let us know.

**Comment by mardi00** [comment]
Hi, yes sorry for the response delay, I will just close it for now, and I will reopen it at appropriate time.
