### ISSUE TITLE
Polish Content Creation  : Ecosystem Growth

### ISSUE THREAD

**Issue by Andrzej0xa0** [stacksgov/Stacks-Grants#7]
### Background ###

Problem: 
Developers (Java/C++/Go) are either not interested in blockchain tech or are tied to Ethereum ecosystem these days.

There are many experience developers in Poland, both blockchain and non-blockchain devs, who could contribute to BlockStack ecosystem growth. At the same time awareness about the BlockStack platform in Poland (and CEE overall) I think is pretty limited, both in enterprise and startup world.
BlockStack has its unique value proposition (Bitcoin-tight consensus protocol, Clarity language, privacy focused approach).
Regarding the market in Poland, most of crypto devs these days work with Solidity / Ethereum and are suffering due to limitation of the Ethereum platform, while many of these issues are already addressed by BlockStack and will be further addressed with Clarity. Non-blockchain developers are typically having good jobs (e.g. as Java devs) and are reluctant to move to Blockchain space (high barrier of entry, not seeing benefit of the tech)

My intention would be to increase awareness about BlockStack in Poland among developers and broader community (entrepreneurs, students, passionates, startups, stakers), encouraging more people to engage, get them on-board, and help building the decentralised and private version of the internet apps with Blockstack and Clarity. 
(PS. I am also an ambassador for Algorand, so am particularly fascinated with the synergies for BlockStack and Algorand thanks to the Clarity language mutual work by both companies)

### Project Overview ###

I have corporate background (15 years), while for the past 3 years I am focusing purely on expanding awareness about blockchain in Poland as my private undertaking - being passionate of crypto world. 

Past 3 years I am a content creator (Video Content https://youtu.be/yuS0PslCMgk, Articles, and other) and would like to use my skills to expand awareness about Stack 2.0, Clarity, BlockStack ecosystem and uses cases). 

My goal is to start with video content (as per the example above) and articles (references below). 
These would be targeted to both technical audience and non-technical audience. Once the critical mass is built and awareness about BlockStack in stronger, I would love to organise meet-ups and webinars to go into more direct interaction with Devs and other community members. 

My overall goal is to grow Blockstack ecosystem, both by :
- inspiring Devs to build (d)Apps 
- attract startups (and possibly Enterprises) interested to built on top of BlockStack
- reach out to STX and BTC holders who want to help securing the network.

### Scope ###

#1 Video Content creation (YouTube)
Prepare and publish overall 6 videos over the period of 2 months (= 3  videos per month). 
   Average length of one video = 45min
   3 videos would focus on technical aspects (dev focus)
   3 videos would cover ecosystem, adoption, use-cases, roadmaps
   Videos would be prepared in professional manner : and publish on YouTube channel with 9k subscribers 

https://youtube.com/DziennaDawkaDyskomfortu
This channel already has a technical audience and non-tech audience focused on crypto 
(I do talk projects there like Algorand, Polkadot, RootStock, The Open App Network, Cardano and others) 

#2 Articles (publish0x, HackerNoon)
Prepare and publish 2 Articles about blockstack (1 technical + 1 ecosystem focused).
  Articles would be published on Publish0x or HackerNoon or my private blog.
  Average length of the article = 1500 words
  Articles will be actionable, with clear "call to action", relevant for particular story.

Once the critical mass of audience is built, I plan to organize meet-ups or webinar, as the next phase of the grant program.

### Budget and Milestones ###

I ask for 2.5k USD (1st Grant). There will be another ask (2.5k) to cover next 2 months (6 vids + 2 articles), as per the suggestion below by Fridger.

DELIVERABLES 
(+ Estimates)

VIDEOS : 6 videos
  Prepare content = 4h
  Record video = 2h
  Edit video = 4h
  Publish and Marketing = 3h
  Follow up with audience (comments / emails / question) = 1h
EFFORT per 1 video = 14h

TOTAL = 6 videos * 14h =  84h to prepare all videos

SCHEDULE:
Month_1 = 3 videos published
Month_2 = 3 videos published

ARTICLES: 2 articles
  Draft version = 4h
  Refine and quality check = 2h
  Publish and Marketing in social media = 1h
EFFORT per 1 article = 7h

TOTAL = 2 articles * 7h = 14h to prepare all articles

SCHEDULE:
Month_1 = 1 article published
Month_2 = 1 article published

### Team ###

This is work by 2 people (me + assistant).
I have worked for 14 years for big it tech company (hp) on various positions, and I do believe I have a  background to talk to the technical and non-technical audience.
I am doing similar stuff (youtube, content creation) for the past 3 years, and feel comfortable already with it 
(references in supporting materials blow)

### Risks ###

This is pretty straight forward and I do not see strong external dependencies. 
Most of the risk I can manage on my own. Just to name some:

#1 Risk: My Availability
Mitigation: Sep-Oct-Nov-Dec seem to be pretty easy month on my side. 
I can re-priotize other stuff if something unexpected pops-up

#2 Covid..
Lockdown or other related stuff could possibly impact future phases (f2f meet-ups impossible), but as a mitigation, certainly webinars are good option.
Anyway this 1st phase of the grant is rather “off-line” (while I am thinking of live events in future phases of this program)

### Community and Supporting Materials ###

I will be sharing progress with community on the ongoing basis. Below are references to my past work (both videos and articles).
My videos are generally receiving good feedback from viewers 
(read some random comments) and good traction (average 1k views), 
so I think I can reach out to pretty well defined audience of crypto and blockchain enthusiasts. 

I would be happy to leverage any support from Blockstack team to share this content with BlockStack community and expand the reach even further.

Examples of my work:
YouTube: https://youtube.com/DziennaDawkaDyskomfortu
PUBLISH_0X: https://www.publish0x.com/strong-fundamentals
HACKERNOON: https://hackernoon.com/u/andrzej_0xa0
TOKENY_PL: https://tokeny.pl/author/andrzej-winiarski/

**Comment by friedger** [comment]
I like this and your references looks promising (although I don't understand polish)

According to the guidelines deliverables should be completed in a 4-8 week. So, the proposal could be improved to better meet the guidelines by just dividing the project in half:

6 videos, 2 articles, budget $2500 delivered in roughly 6 weeks.

.. and ask for a second grant afterwards.

@Andrzej0xa0  To improve the value for the community outside of the polish speakers, would you be prepared to share/publish graphics, videos or so in an editable format under a permissible license? Also to create translations more easily.

**Comment by Andrzej0xa0** [comment]
Thank you for the feedback @friedger :)
I think you proposal makes sense - I will make respective edits to split it by half, and go for 2nd half in the next round.

Regarding sharing the content in editable version : I think I am fine with this. 
Note that these videos are done in Final Cut Pro X, so it is pretty niche platform - not sure how would you like to get it / edit it? Eventually I could also do English versions at some point. 
With articles and other content, this is much easier - in general I have not problem sharing editable documents of any kind, if this adds value.

:)
cheers. 
Andrzej

**Comment by Andrzej0xa0** [comment]
AT @friedger 
thx! :)

**Comment by Andrzej0xa0** [comment]
> I like this and your references look promising (although I don't understand polish)
> 
> The title should mention "Polish" to make it more precise.
> 
> According to the guidelines deliverables should be completed in a 4-8 week. So, the proposal could be improved to better meet the guidelines by just dividing the project in half:
> 
> 6 videos, 2 articles, budget $2500 delivered in roughly 6 weeks.
> 
> .. and ask for a second grant afterwards.
> 
> @Andrzej0xa0 To improve the value for the community outside of the polish speakers, would you be prepared to share/publish graphics, videos or so in an editable format under a permissible license? Also to create translations more easily.

I

**Comment by Andrzej0xa0** [comment]
this was closed by me accidentally - I am reopening with corrected inputs (including suggested changes by @friedger )
