### ISSUE TITLE
STX Guardian 🛡️ - Customizable Scammer-Detect Bot for Stacks Communities

### ISSUE THREAD

**Issue by OmurCataltepe** [stacksgov/Stacks-Grants#70]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?
Stacks has 22 Telegram community and protecting these 22 communities from scammers is key.
The newest trick up the fraudsters’ sleeves involves name-dropping Musk into the Bitcoin address itself, which has helped them fleece victims out of more than US$2 million worth of bitcoin over the past two months.
In Stacks communities, Stacks investors can be scammed and lost their investments because of these scammers.
Moderators can delete these messages, but these messages stay for hours when moderators are not active. In the meantime, the moderators are less active on the weekends. Thats makes community vulnerable. 
STX Guardian will work for secure the Stacks communities on Telegram.
For example:
![ffad5dec-b157-416b-84a2-02764803cf61](https://user-images.githubusercontent.com/33328414/111073956-f35ee780-84f1-11eb-823b-56383e9afed7.jpg)
![USDT-icon](https://user-images.githubusercontent.com/33328414/111302646-b7985f00-8664-11eb-97a3-0bf23512489c.png)

**Project Overview**
What solution are you providing? Who will it serve?
I can build a bot and the bot can scan all Stacks communities 24/7. In this way, most of the scammers will be removed automatically while our community managers aren't online.
My bot will help to protect all Stacks investors from losing their investments. Losing investments doesn't just hurt investors. Projects takes damage too. Because it will lose its investor.

Please check out ESET's report to see how serious the situation is:
https://www.welivesecurity.com/2020/06/22/scam-uses-elon-musk-name-trick-people-us2million-bitcoin/

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
STX Guardian will be a scanner bot and will scan all messages from all Stacks communities on telegram. Scammers can send pictures instead of messages but artificial intelligence will also scan the pictures, so the majority of them will be detected and banned easily. 
Community members and investors will be protected from the majority of scammers. We will measure success by protecting them. 🛡️ 

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Overall Timeline: 90 hours over 3 weeks
M1: 40 hours, designing algorithms and basic structure & image reading structure
M2: 15 hours, Integrating Telegram API to AI
M3: 35 hours, designing, analyzing, testing and deployment

Total Grant Request: We are seeking 2.100$ for building STX Guardian.

M1 - Week 1:
 
Designing algorithms and basic structure - 500$
Preparing the image reading structure of the AI - 500$

M2 - Week 2:

Integrating Telegram API to AI (Getting Messages, Images and converting & importing the images to AI) - 500$

M3 - Week 3:

Designing, Analyzing, Testing and Deployment Fee - 500$
Server Fee (Yearly) - 100$

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Omur Cataltepe - Stacks Turkey Lead, .NET Developer
Abdusamet Kurt - Senior Full-Stack Developer

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
STX Guardian may not be able to recognize some messages. Every unrecognized message will be added to the STX Guardian's database and the bot will get stronger each time.
I think risks will be inversely proportional to time in that project.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

I'm currently building Stacks Turkey community with the other lead and community managers. I'm also a developer and I'm developing projects. My teammate Abdulsamet is a Senior Full-Stack Developer and we have the competence to do this job together.
More than $2 million was stolen from crypto communities because of this scamming method. Protecting communities is key.

**Comment by OmurCataltepe** [comment]
This project isn't related to the Stacks Turkey Chapter but it can be used on there if it'll approve.

**Comment by espadon8004** [comment]
Yes we start to have this issue as well on the Stacks trade telegram channel :( 
Good luck with your project :)

**Comment by OmurCataltepe** [comment]
That's why it is necessary to get STX Guardian deployed :) Too many members can be victimized while moderators aren't too active especially on weekends. 
Thanks for your support! @espadon8004

**Comment by mardi00** [comment]
Yes we have the same issue on Stacks Trade :( Hopefully this can be a solution to this problem.

**Comment by OmurCataltepe** [comment]
That's why it is necessary to get STX Guardian deployed :) Too many members can be victimized while moderators aren't too active especially on weekends.
Thanks for your support! @mardi00

**Comment by RaffiSapire** [comment]
Hi there, we discussed as a group and this is a pass for us. Reason being is there are other bots that exist that do this and we don't see the step-change value in building another one here.

**Comment by OmurCataltepe** [comment]
Hello Raphaela,
There are bots that scan and delete _messages_, but the difference in that bot is scanning all of the texts on _pictures_ that coming from Telegram groups. I had not heard of a telegram bot like that.

**Comment by OmurCataltepe** [comment]
The vast majority of scammers do this by sending pictures to bypassing these text-scanning based bots.

**Comment by OmurCataltepe** [comment]
The vast majority of scammers do this by sending pictures to bypassing these text-scanning based bots. They are sending these pictures and current bots can't detect them. We are deleting messages when we were see and they are sending again immediately. Its getting hard to fight with them because they are sending these pictures more often than ever.

My point is detecting scammers and protecting Stacks communities by scanning images.

**Comment by hasijasaurabh** [comment]
We would like to use anti-spambot for India community, we want it to be integrated into the Stacks India to protect our community from scammers.

**Comment by RaffiSapire** [comment]
Hi there, we reviewed your responses and this is still a pass from us. Whilst the very specific bot they are seeking to build may not exist, a quick internet search turns up bots that can do OCR or recognize things on images.
https://github.com/gabrieltanhl/OCR-Telegram-Bot 
https://towardsdatascience.com/weekend-hack-building-an-image-recognition-bot-for-telegram-using-python-958646b4c4e5
