### ISSUE TITLE
Stacks Authenticator

### ISSUE THREAD

**Issue by Pravica-Inc** [stacksgov/Stacks-Grants#71]
**What problems do you aim to solve? How does it serve the mission of a user owned internet?**

There is a problem with building DApps on mobile iOS/Android native or cross-platform on top of Stacks infrastructure and the current unsupported community SDKs are outdated, and would not have the stacks 2.0 support unless much much work is put into these SDKs (almost a revamp) closing that process into an open source app for auth/payments/contract interactions would make it much much easier to integrate through experiences the likes of Metamask TrustWallet.

![image0](https://user-images.githubusercontent.com/61974592/111363875-3c9d6b80-8699-11eb-955c-e39a30b5ef34.png)

**Project Overview**

We came with a solution to ease the user’s journey authenticating through Stacks BNS. With a single tap the users and dApp developers could access the plethora of potential stacks blockchain features and services, the idea of this authenticator is, The user will login with his wallet one time using the Authenticator, and every time any other apps try to authenticate it will ask the user’s permission to generate the identity for the current usage app, so basically, the flow is:

- The DApp requests the appPrivateKey from the Authenticator.
- The user will review the app data within the Authenticator interface and then decide to either grant or reject access request by that app to use any of his currently set up identities on the authenticator.
 - The Authenticator will generate appPrivateKey for the app, once it’s generated it will redirect the user to the app with the required data.
 
![image1 (1)](https://user-images.githubusercontent.com/61974592/111368923-1f6b9b80-869f-11eb-9375-16c7ce82baf2.png)

**Scope**

Basically, developers who are building dApps will no longer need to use deprecated SDKs, to build their apps on top of Stacks, they will focus on their app journey and not the hassle of creating a better UX for their authentication, and STX transfers and contract interactions in the future.

We will not stop from here, we’re looking further to implement more features for this product, our vision is to make life easier for developers, the second phase of this app is to provide the identities real information which is not found in the current connect ux, such as avatar, full name, social media and more personal information the user will decide what are the information the app asking takes.

Also, we’re planning to implement STX transfer where users will be able to transfer STX from other apps through our authenticator.
And more features to come such as:
- Stacking Delegation
- Smart Contract Deployment, and Smart Contract interactions 
- Stacking
- NFTs

**Budget and Milestones**

The total requested budget is $11,000 for the next milestones
Applying for a grant. We expect to spend more than that on development efforts over the next couple of months. Milestone would be to be able to have a basic working version of the project. The project will be split over the following milestones across 3 months.

**M1: (2 weeks / March 2021)  (DONE)**

- Designing architecture for the app workflow 
- Designing UI/UX for the authenticator 

**M2: (1 Month 15th April 2021) 150h grant -  $6,000 (In-Progress)**
- Initiate Android/iOS projects for developing the authenticator 10h
- Implement UI design through both iOS and Android 20h
- Implementation of authenticating wallet logic (iOS/Android) 30h
- Implementation of redirecting and giving permission logic (iOS/Android) 30h
- Implementation of JS library for (React-native apps) to access the authenticator 15h
- Handling testing and secure apps from dangerous URL schemes and re-routing apps frauds 20h
- PIN code for securing the authenticator 25h

**M3: (1 Month 15th May 2021) 50h grant $2,000**
- iOS Native SDK for native apps that accessing the Authenticator 25h
- Android Native SDK for native apps that accessing the Authenticator 25h

**M4: (1 Month 15th June 2021) 75h grant $3,000**
- STX transfer for the authenticator UI 20h
- STX transfer logic implementation 25h
- Implementing the transfer in iOS SDK/Android SDK/JSLib 30h

From here we can start asking the community what features and requirements they would like to implement next, we will not stop from here, we’re targeting that authenticator wallet to be the standard tool for mobile apps for Stacks apps

**Team**

Pravica team

**Risks**

None was found till now according to these milestones.

**Comment by friedger** [comment]
@Pravica-Inc There is the Circle App for Android that is the Stacks Authenticator that you describe: https://github.com/blocoio/stacks-circles-app

**Comment by Pravica-Inc** [comment]
@friedger 
While circles is a great app and a great start for mobile app auth, what we're providing is something unique

- Circles is only for Android, our app goes further with cross-platform and both Android/iOS Native apps, cuz we're implementing JS libs and the SDKs
- Our app would have more and more features in the future the likes of Metamask and Trust Wallet, in the next couple of months we're going to implement Stacking, Delegation, Smart contract calls, and STX transfer
- Making a standard SDK for react-native developers as start and cross-platform development, in general, is essential for any starting up apps not diving directly into native apps.
- Having an opensource conversation about security, open-closed principle in this implementation is well thought out, and cross-platform apps are the best target to get more developers onboarded quickly.
- While we were implementing our mobile app, we faced some issues with the authentication and the ux of the deprecated browser, We are building this tool to improve user's UX and accelerate the development process for us and for upcoming mobile apps (Auth. functionality will be shipped next month) for both Android and iOS, that's why we decided to have this as an open-source for the community to make it a standard tool for mobile developers in the future.

**Comment by RaffiSapire** [comment]
Hi there, 
We discussed today and wanted to share a few to-dos for you:
From our understanding from Mark at Hiro,  the legacy SDKs are being updated by Hiro, for the reason mentioned in the proposal. Also, the app seems to have a lot of overlap with pre-existing authenticator apps (as pointed out by Friedger), and wallet apps (like Boom, etc.) Could you check with Ken (Secret Key) and Mark (Hiro) and figure out addtl contribution to what Hiro team is working on. One thing that really resonated in terms of additional contribution is that if we have react native libraries, we can attract broader audience. Would be great to check with them and share back how you see where you are adding additional contribution here given what other folks in the ecosystem are working on, and lets hone in on those aspects.

**Comment by friedger** [comment]
There is also the the react-native blockstack wallet for stacking and stx transfer: https://github.com/pradel/blockstack-wallet

I think it would be great if Pravica can bring these all together and advance them :-)

**Comment by Pravica-Inc** [comment]
Hi @RaffiSapire, thanks for responding.
As we've been waiting so long for the SDKs and the authenticator apps we came out with our proposal and implemented it already within a month, As we can see the Circle app hasn't already provided authentication for apps, and it hasn't been maintained since two months ago, And after all, it's only for Android.

Our proposal is a bit different, and we have brought a full team that only working on this product, We've already implemented the authentication in both Android and iOS.

We've made two videos that show the old experience and the new experience of the authentication

The old implementation of the SDK authentication.
https://drive.google.com/file/d/1vyoJpcp_reNVsD878v53DxKtFoEKKanl/view?usp=sharing

The product we've implemented already.
https://drive.google.com/file/d/1Q21CjJQfsPshaEco6RULsfxJU4epxQuZ/view?usp=sharing

Also according to wallet and Stacking, delegation, and other stuff, they're additional stuff, in our perspective as long as the user only has one standard tool that authenticates with Stacks apps, holding their wallet, stacking, transfer STX, etc.
It would be easier for them to trust a single app than multiple apps, And as @friedger said, we're bringing all together in a single product, which is we believe this would be the single source of truth for users

**Why this helps the community?**
We will provide some more interesting stuff, We're making developers' life easy, they will focus on their main product meanwhile they can use this product, for authentication, STX transfer and multiple stuff, through their app with some lines of code.


We wanted to share this with the community, so we can make the user experience more easier and developers as well.

**Comment by RaffiSapire** [comment]
Hi @Pravica-Inc, we discussed at length and unfortunately this is a pass for us. Reason being, we see the contribution here around a react native library, but that already exists. We’re not seeing additional value here beyond that given the work others in the ecosystem are pushing forward.

**Comment by mardi00** [comment]
I don't get this, even if this have been already been built, won't this make the ecosystem more decentralized?

I think having multiple implementations of the same thing by different team can be beneficial to the ecosystem. In my opinion it's not because we have already have one lib or one implementation that we shouldn't have a new one or a different one.

**Comment by Pravica-Inc** [comment]
@mardi00 We started our journey and we built the authenticator called `Wise`, We believe to make it the standard tool for mobile authentication and the wallet for holding your digital assets. 
Now you can find it on both App store and play store, you can test it using Pravica as well, here is the link:
https://wiseapp.id
We would like to know your feedback.
