### ISSUE TITLE
A co-creation platform for collaborative skills developement

### ISSUE THREAD

**Issue by RuwenReinhard** [stacksgov/Stacks-Grants#76]
**Background**
The pandemic has rapidly increased the need for digital but collaborative solutions in the area of knowledge management growing. Home offices and distributed workspaces require easily accessible and efficient tools that are ideally still be enriched with aspects of gamification. For the home office, difficult topics such as motivation of the employees and structure in the working and learning environment urgently need supporting approaches. Even after the pandemic, a significant proportion of home workplaces will remain, and studies predict a decline in the willingness to travel long distances. even the right to a home office is being discussed politically. Thus, the requirements for collaboration and learning solutions for employees in companies are increasing as well as the needs of users in terms of professional development and lifelong learning. Despite a large number of e-learning and digital knowledge management solutions on the market, there is a lack of convergent, open approaches and, above all, collaborative solutions. collaborative solutions. These should ideally be open-source, with state-of-the-art technology, platform-independent, sustainably usable, user-generated or at least user-rated, inexpensive or freely accessible, and protect user data. protected.

**Project Overview**
Open Innovation circle is to become the first co-creation platform for collaborative skills development, where every person can educate themselves free of charge on the topics of startup, innovation, leadership and digitalization. The innovative learning journeys used for this purpose can be shaped and improved by any person at any time without losing the original author. Through the integration of STX authentication, each person can track at any time which of their own learning journeys have been forked and what has been improved. Learning journeys can thus also be used across tools or platforms and integrated into own solutions without losing the authorship. The STX Foundation can, for example, offer innovative learning journeys for all the topics around stacking, mining and holding of STX and make them available to the community. The platform can thus be used by companies for private data and still be operated in a decentralized manner. By collecting royalties from companies for using the platform and creating the private data, the public spaces can be run and the creators of very good learning journeys can be compensated. (e.g. in the form of STX).

**Scope**
The platform stores knowledge, gives the knowledge a new structure through interaction with the participants (learning paths) and enables a qualitative filter (rating) of the content. In this way, it gains an inherent improvement dynamic through the crowd. It combines elements of different existing solutions, such as open knowledge platforms (Wikipedia, Wikimedia), learning paths in course offerings (Udemy, Udacity), collaboration solutions (Miro, Mural, Hoylu) and development environments (GitHub). (GitHub) into a universal learning management system.

In the past months, a prototype with a sample data set on the topic of "innovation management" and a learning path based on "Working out Loud" was realized. a learning path based on "Working out Loud" (https://workingoutloud.com/). The development was based on the agile approach according to Lean, basically an iterative approach with the help of Scrum is used, this helps to get all the This helps to implement all work steps quickly, structured and "in time".

The technical components are currently planned with the Angluar framework and thus state of the art in web development. In addition, the standardized services of STX are to be fully integrated (user management, transactions, etc…).

**Budget and Milestones**
Milestones:

Q3 2021: Implementation of the development team, start of development ready for series production.
By the end of 2021: Sales target of 5 companies, 1 teaching institute, 100 private individuals; further product evaluation; first theme: "start-up and innovation
Q1 2022: Expansion of sales strategy, marketing
Q2 2022: Market maturity version 1, start of scaling;
Q2 2022 onwards: implementation of further topic areas, e.g. "Artificial Intelligence, Machine Learning".
Two of us have already invested more than 500 hours, so we no longer give milestones in hours.

**Team**
Ruwen Reinhard: Master of Business Administration, state-certified media and communications computer scientist, 4 years Innovation Manager at AEB SE (software house for logistics solutions), experience in the start-up sector.

Johannes Freyer: Studied Business Administration at the University of Mannheim, currently founder and managing director of several companies in the fields of IT and e-learning (Margraf New Media GmbH), collaboration and coworking (Cowork Group GmbH, Next Campus Deutschland GmbH (formerly Europa Institut Company Deutschland GmbH)) and AI/Foundation (Innovationszentrum Westspitze GmbH), member of the Federal Expert Committee on Digitization and AI as well as of the BfA Media of the German Cultural Council.

We need more developers from the community as well as knowledge carriers on the topics of innovation, startup, digitization, leadership and STX topics.

**Risks**
We currently have several interested parties who either want to invest in the platform or want to become a customer on the platform. Therefore, our plan B is to make it a regular business model in addition to the variety for the community and the user owned internet.

**Community and Supporting Materials**
We have been building with the lean startup method for a year on the continuous development of the MVP and are now at a step to think the whole thing big. We have received excellent feedback and our first prospects. Thinking about the whole thing as a user-owned variant and no longer making knowledge exclusively available can be the next big step.

The MVP can be found at https://openinnovationcircle.com.

We want to integrate and consult the community from the very beginning of further development. The best way to learn is from the customer. And who better than the community?

**Comment by RaffiSapire** [comment]
Hi @RuwenReinhard 
We discussed at length today and unfortunately it's a pass for us. Reason being, we don't see this being a priority for the ecosystem, the proposal is quite high level and difficult to understand what you're actually proposing or how it would be implemented. Thank you for taking time to apply.
