### ISSUE TITLE
STX CONVERTER

### ISSUE THREAD

**Issue by narcisG** [stacksgov/Stacks-Grants#77]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

There are some places where you can see the price of STX. They usually only convert to Bitcoin. If you want more options, it is complicated and time-consuming. They also have a lot of other confusing information and ugly ads all over. 

**Project Overview**
What solution are you providing? Who will it serve?

A converter of STX to USD, BTC, EUR, and SATS in one place. All the combinations between them in both directions. Easy to use, clean and simple.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

- Technical specs: A web app built with HTML5 and Javascript
- Final deliverable look: A web app with responsive design. It will adapt to any device and size: desktop, tablet, and mobile. Clean and simple. No distractions.
- Measure success: Visits to the site. 

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $5,500

1- Minimum Viable Product (MVP)

Graphic representation of the product. Explain its functionality and collect the first impressions from possible users.

$500
10 days from the starting point
90 hours estimated

2- Programming. Basic Converter

The core of the product. Convert STX to USD, EUR, BTC, SATS, and all the combinations between them in both directions.

$3,000
3 weeks
60 hours estimated

3- Art Direction and marketing 

Emphasis to make the program very clean and simple. Easy to use in desktop computers and responsive for mobile devices.

Explanation of the product. Origins. How to use it.

$1,500
2 weeks
60 hours estimated

4- Extra features

Very difficult to predict the timing and budget. It depends on the feedback. I reserve two weeks to evaluate, incorporate some extra features and consider more substantial future changes. Organize a new strategy and a possible future grant if necessary. Study other income resources.

$500
2 weeks
60 hours estimated

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

I have studied marketing in universities like Esade Barcelona and Harvard Business School in Boston. I teach myself programming. I have more than ten years of experience in marketing and programming.

I know how to program and solve this problem from a technical point of view. I know how to market the product.

More details about my background:
https://www.mig-marketing.com/narcis

Some of my projects. Portfolio:
https://www.mig-marketing.com/portfolio/

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

I am sure there will be obstacles in the way. Despite that, I feel qualified to face them. 

My weak points are my weak presence in social media and the fact that I am not a native English speaker.

(I am in Catalonia/Andorra. I read and write fluently in English, but I do not have many occasions to speak in that language. This is something that I am working on)

I try to improve in that aspects by collaborating on different challenges with Freehold. For instance, I have participated in and completed two moderation challenges with the Stacks Telegram channel.

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

I am active in the Telegram Stacks channel. Reputation: 94 Level: 9 (3452)

I will improve my presence in the Stacks Reddit channel and the Stacks Forum. I am active, but I will strengthen my activity on Twitter.

I have been in YCombinator Startup School. I will be more active in Hacker News.

As I have mentioned here are some of my projects. Portfolio:
https://www.mig-marketing.com/portfolio/

**Comment by friedger** [comment]
Which data sources are you using?

**Comment by narcisG** [comment]
> Which data sources are you using?

Hello Friedger,
I have been playing with different data sources. By now I use CoinGecko

**Comment by RaffiSapire** [comment]
Hi @narcisG, this is a pass for us, reason being, we don't see how this is significantly different than coinmarket cap that would warrant an additional grant. https://coinmarketcap.com/converter/  

Happy to work with you via office hours to help find another idea to apply with.
