### ISSUE TITLE
STX Donation to Friedger Pool

### ISSUE THREAD

**Issue by louiseivan** [stacksgov/Stacks-Grants#79]
**Background**

**It's time to champion builders within the Stacks ecosystem.**

Stacks found a product-market fit with Stacking. Due to this, we can't deny the fact that our community is growing faster than ever. This particular scenario is a piece of evidence to accelerate support for builders within the ecosystem that provides tools to increase STX access and TVL of Stacking. 

Let's take a deep dive with Stacking. Currently, we only have 6 Stacking pool options. One is custodial; two have a minimum threshold of 10,000 STX ([Staked.us](http://staked.us/)) and 90,000 STX(Hiro wallet).Five out of the six pooling options take a fee of 5% to 10%. For an average stacker, most of the community pool options seem unreachable. We need to solve the lack of community-driven stacking pool option for our average Joe and Jenny, who has as little as 50 STX.

**Project Overview**
A pool built by the community for the community. Friedger pool is the only community pool option that doesn't take fees and rewards users with Stacks native token (STX). The community-led project had an undeniable momentum from its initial launch. Please see the table below for the pool growth cycle after cycle. 

<img width="743" alt="Screen Shot 2021-03-30 at 4 42 54 PM" src="https://user-images.githubusercontent.com/58204144/113008154-1686c980-9177-11eb-9309-c5f4e5e3f8c8.png">

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

-Automated Friedger Pool by the end of 2021. 
-Used by users and app builders as their preferred stacking delegator.

**Team** 
Friedger Müffke has been a long-time contributor to the Stacks ecosystem. His early contributions can be traced back to the [Android SDK](https://github.com/blockstack/blockstack-android). Since then, he has submitted many patches, test libraries, and tools as they have become available, too many to count, I guess. He developed Stacks apps, have mined Stacks earlier this year, and even deployed the [first user contract](https://explorer.stacks.co/txid/SP1K1A1PMGW2ZJCNF46NWZWHG8TS1D23EGH1KNK60.badges?chain=mainnet) on mainnet.

Friedger is inspired by all work that helps to bring back a user-owned internet. He is offering friedger pool as a stepping stone to achieving that vision. **A true OG Stacker with his community first mantra.**

**Budget and Milestones**
The maker needs funding until everything is automated thru a smart contract. For now, all the cost will be used to maintain the pool, develop scripts and tools. 

10% Donation of the total payout for administrative costs until Friedger pool is automated thru a Smart Contract in Q42021. 

<img width="738" alt="Screen Shot 2021-03-30 at 4 46 27 PM" src="https://user-images.githubusercontent.com/58204144/113008639-7f6e4180-9177-11eb-8a71-9cbde867e17e.png">

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

The only risk factor that we can see is time and how long friedger pool will take to automate. Friedger is currently targeting Q42021 as the completion date. It is important to note that Friedger has only one pending grant application which isn't completed because of the BNS issue that is still persisting which other devs are also complaining about.

**Community and Supporting Materials**
[https://explorer.stacks.co/txid/SP1K1A1PMGW2ZJCNF46NWZWHG8TS1D23EGH1KNK60.badges?chain=mainnet](https://explorer.stacks.co/txid/SP1K1A1PMGW2ZJCNF46NWZWHG8TS1D23EGH1KNK60.badges?chain=mainnet)
[https://pool.friedger.de/](https://pool.friedger.de/)
[https://boom-wallet.medium.com/how-to-get-your-first-boombox-d97a9404e759](https://boom-wallet.medium.com/how-to-get-your-first-boombox-d97a9404e759)
[https://twitter.com/fmdroid/status/1375559117020991493](https://twitter.com/fmdroid/status/1375559117020991493)
[https://twitter.com/fmdroid/status/1375064527230930948](https://twitter.com/fmdroid/status/1375064527230930948)

**Comment by mardi00** [comment]
Really cool idea! I think Friedger did an amazing job with this community pool and with all his previous contributions to the ecosystem.

**Comment by RaffiSapire** [comment]
Hi @louiseivan @mardi00 we would like to be supportive to Friedger but want this to come from him. @friedger Could you please refine and resubmit as yourself?  We’re here to help you get to the next stage, what does that look like and what would that take from a support perspective?

**Comment by RaffiSapire** [comment]
I'm closing this as he has submitted his own.
