### ISSUE TITLE
Grant

### ISSUE THREAD

**Issue by Valerio888** [stacksgov/Stacks-Grants#8]
*We prefer clear, concrete, and concise applications. If an application is incomplete or unclear, we will request an update to the application.*

## Background

> What problems do you aim to solve? How does it serve the mission of a user owned internet?

We are creating a social network state CryptoTox for free communication and interaction of projects, enthusiasts and new participants in the industry.

## Project Overview

> What solution are you providing? Who will it serve?

Our solution https://cryptotox.com/
Your project page https://cryptotox.com/stacks/
In the future, our site will be the place of absolutely every person, since cryptocurrencies will eventually become the new money.

## Scope

> What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

We have been creating our project since 2018
Today the CryptoTOX.com website is operational and new users are registering on it every day. We update our website on a daily basis and publish news about current crypto projects.

## Budget and Milestones

> What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

## Team

> Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community?

## Risks

> What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

## Community and Supporting Materials

> Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

Feedback from users of our platform is positive, some believe that in the future we will be able to become the center of the entire global financial system, which we ourselves sincerely believe.
Our project is actually launched, you can register on it, launch your project, publish news, as well as exchange messages, read in the general feed both world news from the world of cryptocurrencies, blockchain and new technologies, and project news. Registration, placement, as well as all the functionality available on the site is absolutely free for users.

**Comment by friedger** [comment]
The issue title should reflect the content for easier handling.

The budget is far beyond the 5000$ and therefore the proposal is likely to be rejected. Please review the guidelines..

**Comment by Valerio888** [comment]
> The issue title should reflect the content for easier handling.
> 
> The budget is far beyond the 5000$ and therefore the proposal is likely to be rejected. Please review the guidelines..

On this score, there is a good saying: "If you don't shoot, you will definitely miss."

**Comment by friedger** [comment]
Integration of Blockstack Auth would be interesting sub-goal. Is the code published somewhere?

**Comment by Valerio888** [comment]
> Integration of Blockstack Auth would be interesting sub-goal. Is the code published somewhere?

We have not published the code yet, but we are always ready for a dialogue if necessary.

**Comment by friedger** [comment]
The grant guidelines say that it is necessary.

**Comment by louiseivan** [comment]
This proposal seems half baked :)

**Comment by Valerio888** [comment]
> The grant guidelines say that it is necessary.

Yes, we are ready to open the code for you. Could you please register with our platform and write your username here to discuss the details.

**Comment by Valerio888** [comment]
> This proposal seems half baked :)

Therefore, we are participating in the grant program :)

**Comment by Valerio888** [comment]
> Интеграция Blockstack Auth была бы интересной подцелью. Код где-то опубликован?

Also, in order to integrate Blockstack Auth, we first need to enter into at least a partnership with your project. As for opening the code here, I also did not quite understand why it is needed, if only we ourselves can make changes

**Comment by friedger** [comment]
The grant is only available for work that is open sourced and usable under a permissive license.

The community is giving grants for the benefits of the community, not individuals😀

**Comment by friedger** [comment]
If you listen to the feedback and adjust your proposal you might get a grant.

**Comment by Valerio888** [comment]
We would like to receive a grant as your media partner, which is a boon to the community. We cannot risk opening the code because of the very unclear prospects for a grant. Thank you for paying attention to Us.

**Comment by blocks8** [comment]
**Review Committee Feedback from 9/8/2020: We'd like more information on your proposal.**

Thank you for your application! The content seems to be incomplete after new revisions. Please fill out the questions in your proposal above.

**Comment by blocks8** [comment]
**Review Committee Feedback from 9/15/2020: Proposal closed for missing information. Please submit a new complete proposal.**
