### ISSUE TITLE
ardkon.com, the first democratized and decentralized live crowdfunding platform... 

### ISSUE THREAD

**Issue by planet369** [stacksgov/Stacks-Grants#82]
ardkon.com, the first democratized and decentralized live crowdfunding platform...
PPR performance & productivity ratio
www.ardkon.com
ard@ardkon.com

A blockchain application that gives proof for public money use through giving stamps for the performance & productivity of an individual or entity. 
Abstract: 
To realize an “asset based sovereignty”, micro & macro public investments should have a reputation that will allow the public to examine historical data and predict future engagements based on the summary. Till date there is no digital proof of any public servant activities and the PPR aims to end this data blackout on the public. 
Hence the lack of transparency over public management that is the case in Lebanon and in a lot of countries in the world where corruption is high, the PPR aims to become the formal ratio for determining the input of an individual or organisation in the attempts of managing & investing public capital and assets.  
ardkon aims to revolutionize the way we educate our local and global communities about how blockchain tools and applications can determine the results of our human capital in managing public assets & spending. 
Public responsibilities can no longer be centralized and a global emergency is transferring the reliability and trust from influence to proof of work. To be able to educate the public about the importance of proof of work over influence, blockchain have to become the ally of the people.
Hence to be able to leverage the most of our public capacity and efficacy, the PPR aims to initiate the new era of normalizing blockchain uses and pipelines in public matters. ardkon goal is to help us all get closer to fully complete the transition to an e-citizenship & e-liberation. 
Concept:
Our vision is to use the ratio to lobby for the creation and development of NGB (non-governmental blocks) that will act as blockchain plugins that insures transparency for all public work and responsibilities, make all rights and public actions visible for the mass and support peace with blocks that give proof of work and traceability to enhance public relations and affairs. 
The ratio will replace the conventional receipt-based accounting procedures with a dedicated proof-of work system and replace trust as an emotional response that is linked to institutions with accountability through smart contracts mass integration. 
The aim is to ensure democratic means for proof of efforts so donors and projects can decentralize their trust and bypass the centralized governance of funds. 

Milestones: 
    1. Creation of Public Ledger Technology Contract v1.0.0 that saves all donations done through the platform for the different actions created. MVP was created during the hackathon. Estimated time: 33 hours. (budget: 900 usd)
    2. Creation of the MVP & v1.0.0 of a Democratized Funding Contract where the initiative and donor collectively decide on the terms of the fundraising. Estimated time: 66 hours. (budget: 1800 usd)
    3. Creation of the Productivity Performance Ratio for Initiatives. After end of each action funding a Ratio is created depending on the terms and the collective ratio calculated by the donor and the community. Estimated Time: 66 hours. (budget: 1800 usd)
    4. Creation of ardkon Neutralization Token MVP, where the token collect different currencies and neutralizes the values of all different currencies, 1 currency is used in ardkon ecosystem. Estimated time: 99 hours. (budget: 2700 usd + 10,000 usd for currency exchange protocol to fungible tokens)
    5. Creation of Vue.js open-source components to integrate Stacks.js Libraries, so that adoption of stacks in the vue.js community will become easier and faster. Estimated Time: 33 hours. (budget: 1800 usd)
    6. Creation of a 6 month program for junior developers, to learn full stack development, including learning technologies: Vue.js, Vert.x, Apache Cassandra, Docker, and including Stacks.js and Clarity smart Contracts in the Project. Estimated time: 66 hours to build the program and 6 month of program bootcamp. (budget: 3600 usd pre program)

Technical Specs: 
    • The Ledger Technology which will be built and based on Stacks Ecosystem and on Clarity Lang.
    •  The Front-end technology will be based on Vue.js, a progressive JavaScript Framework. The aim to use a scalable front-end technology with an easy adoption rate for new developers to join the team.
      
    •  Availability is key in our platform, that is why our architecture is based on a micro-services distributed architecture that increases the availability and modularity of the project our main technology used are vert.x for services, apache Cassandra for distributed databases, and Docker for service deployment which facilitates the use of any deployment methodology whether on Kubernetes, elastic Container service, or on server instances.
      
    •  Live Streaming Technologies, that uses hls to deliver compatible delivery formats and a global content delivery network.
Resources: First MVP smart contracts: 
    1. Funding Trait: https://explorer.bootcamp.stacksmena.org/txid/0xe08e2a1cefe06285e320ea8927d8086ee99a58182f52cd389e6d95e9625d6323
    2. USD wrap Contract: https://explorer.bootcamp.stacksmena.org/txid/0xf255b1fc5e5f1b24db141fe248a6298f02bc533e41fb6c7f89ee79dd44f1aba2?chain=mainnet
    3. Ard Funding Ledger Contract: https://explorer.bootcamp.stacksmena.org/txid/0x2cfcb63e11a489fd04fcdbe01954b1809029a89e0db64e3503e6685eab19a5db?chain=mainnet

**Comment by RaffiSapire** [comment]
Hi there, we discussed the grant today and unfortunately this is a pass. The milestones are confusing/unclear, and we couldn't understand what success for this project looks like. It also doesn't mention anything about stacks specifically. We couldn't convince ourselves that this will benefit the community. Marvin offered to speak to you more and help scope the grant if you'd like, you can reach him on discord.
