### ISSUE TITLE
A NFT Digital Gamecock Game Built on Stacks 

### ISSUE THREAD

**Issue by jedabomb** [stacksgov/Stacks-Grants#86]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

NFT's through games are becoming increasingly popular, but the common ERC-721 token is clogged up and expensive due to gas fees. A better and more efficient gaming and digital asset owned blockchain is needed.  

**Project Overview**
What solution are you providing? Who will it serve?

Through CryptoCock or our Digital Gamecock game we will bring to light a new and alternative way for NFT's to be built... which is on Stacks. 

Cockfighting is a very old sport that dates back to 1500 BC, and most experts believe it started in South East Asia. The gamecock was highly admired during this time and in some places the fighting cock was worshipped as divinity. The beautiful animal would put its life on the line for his master to prove his worth. The gamecock was majestic, fierce, passionate and only the best would survive. 

As cockfighting is a very cruel sport and humanity became more civilized over time the cockfight has rightfully been outlawed in most parts of the world. This game does not promote or support cockfighting of real gamecocks in anyway. We wish to bring to life the history of the gamecock and make mention to his grandiose demeanor that once symbolized manhood and godliness.

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?
We have already built out the website and designed the initial gamecocks, but both of those may change. We had the Genesis Gamecocks set-up as ERC-721 tokens, but we would like to change that now. The final project will aloe users to purchase and sell their gamecocks and game hens (or their flock) as well as breed the game cocks and game hens, and then most importantly fight their gamecocks to advance their gamecock experience and level. Users will not be betting on fights. The fighting is only to improve their gamecock levels and make them better breeders. 
**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.
We are seeking $10,000 as the development team will need $2,000 for 5 months to complete the project. This will include all aspects of the site. 

Total Grant Request: $10,000

M1: Scope of work, deliverables, and grant amount of total.

M2: Etc.

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 
Justin Embry and Casey Stettler are founders, but the developers are over seas developers from India. We have worked with them for several years. 

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?
Lat time we started this project they crypto world crashed and it seemed everyone lost interest. Our Discord Channel was abandoned, and even though we had a lot of initial interest we were not able to complete the initial sale of the genesis gamecocks. We were trying to launch on kickstarter and indigo last time and they rejected our proposals due to it being tied to crypto.  

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?
We had a recent size discord group and interest in the game back in 2018. I would need to start that again once we get close to launching the game this time. 
Here is the white paper and video of what the website looked like in 2018. It has since been taken down, but if we get the funding to build on Stacks they will easily be able to update the code and get it going again. 
https://docs.google.com/document/d/e/2PACX-1vQyXSb2Y8_Sbf2OVfR_l49JFCkPsV2JkYOnAWQU5j3L308NGrkH7tmlZbU-8H1VqQ/pub
https://youtu.be/FJhNVBTlMDY

**Comment by RaffiSapire** [comment]
Hi there, we'll discuss at committee, but initially will want to see this scoped out into 3-4 milestones with clear, user story deliverables that we will be able to go in and see whether they are complete or not.

**Comment by jedabomb** [comment]
Beautiful.. I am working on that with the development team. We did get the site back on a development url, but it’s not connected to metamask anymore. http://3.138.38.80:7700/

**Comment by jedabomb** [comment]
My developer is worried by switching it to Blockstack’s smart contracts he may get stuck developing the game. I have been trying to get developers to learn clarity for some time and am struggling as it’s not well known and not a great investment of their time... yet. :)  My developer; Gary, from
Texas is very good and I have worked with him for like 3 years on a various projects just wants to make sure you guys feel
Like this game is possible with blockstack before he jumps in 100%. 

Thoughts?

**Comment by jedabomb** [comment]
I developed the game concept/white paper
Back in 2018 and would love to see it come forth, but need some support and funding. If
You guys can help with that, Gary is willing to jump in head first  in the game if you believe it can be done.

**Comment by jedabomb** [comment]
This is timeline I was using before when we were trying to get funding with kickstarter, but they didn't like Blockchain stuff at that time and we never got any funding. I am very excited about being able to build NFT based game on the back of bitcoin this time with stacks. I truly think it is the future of the internet.
**Milestone 1** 
- understand stacks approach to NFT's and get spun up on the tech 
- redesign of original 8 genesis Gamecocks with proper DNA and fighting levels
**Milestone 2** 
- create gamecock and Hen NFT’s with proper DNA and fight levels 
- develop breeding between hens and gamecocks to breed new gamecocks and hens
- develop fighting between gamecocks with proper game levels 
**Milestone 3** 
- Create live website with full game features 
- testing

**Comment by 314159265359879** [comment]
> 
> 
> This is timeline I was using before when we were trying to get funding with kickstarter, but they didn't like Blockchain stuff at that time and we never got any funding. I am very excited about being able to build NFT based game on the back of bitcoin this time with stacks. I truly think it is the future of the internet.
> **Milestone 1**
> 
>     * understand stacks approach to NFT's and get spun up on the tech
> 
>     * redesign of original 8 genesis Gamecocks with proper DNA and fighting levels
>       **Milestone 2**
> 
>     * create gamecock and Hen NFT’s with proper DNA and fight levels
> 
>     * develop breeding between hens and gamecocks to breed new gamecocks and hens
> 
>     * develop fighting between gamecocks with proper game levels
>       **Milestone 3**
> 
>     * Create live website with full game features
> 
>     * testing

You may want to be a bit more specific with Milestone 3
Create a live website with full game features will not suffice and will get you in trouble.
i.e.
- user logs in with web wallet id on gamesite
- user is shown: breeding, start fight, browse hens (marketplace? or is this milestone 4?)
- user can start breeding/buy hens
- user can start gamecock fights (automatic pairing?)
- user can browse gamecocks owned
- user can send gamecock NFT to any stx address

Could you join the labs3 channel on github? Lets have a talk about _" If You guys can help with that, "_

**Comment by jedabomb** [comment]
Yeah.. milestone three is pulling all the tech together and having it go live.
- login with stacks ID 
- About home page and about Cryptocock page
- marketplace for buying, selling, and breeding of gamecocks and game hens 
- fight page - automated pairing of users that wish to fight their gamecock
-  user’s admin that showcases users flock

**Comment by jedabomb** [comment]
I joined the lab3 discord channel and updated milestone three above and added some timelines for each milestone

**Comment by RaffiSapire** [comment]
Hi there, we discussed and this is a pass for us for now. We haven't previously funded games, but we are open to it. What we'd want to see though, is an MVP prototype where you already have users and some evidence of stickiness: Daily active users, monthly active users, patterns of usage. If you come back with that being built, and metrics to share, we'd be open to continuing a conversation.
