### ISSUE TITLE
dsaasdasdfasdfasdf

### ISSUE THREAD

**Issue by cornelius20** [stacksgov/Stacks-Grants#886]

**Comment by stacks-foundation** [comment]
👋 @cornelius20
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will
