### ISSUE TITLE
A User-Owned Decentralized Audio / Video Streaming Distribution App Built on Bitcoin

### ISSUE THREAD

**Issue by AlfredPizzurro** [stacksgov/Stacks-Grants#90]
Name: IBN, LLC CA Corporation  
About: Bringing the network effect to STX and transactions fees to Clarity smart contracts  
Title: A Streaming Video and Distribution App on Roku    

**Background:**  
Upon completion of all three phases of DiviUp buildout the DiviUp ecosystem will be an interactive blockchain platform, App and DApp, for digital content creators to collaborate, create, store, track, share and monetize their digital content on a user-owned video streaming economy built on bitcoin. We are ready to build the DiviUp platform that will be funded, owned, and governed by the users. That is, we will flip the script placing the ownership and governance back in the hands of the creators where it belongs. DiviUp’s token will create a global business structure that will live on throughout future generations supported by multiple revenue streams that are linked to new copyrights creating a perpetual revenue stream of transaction fees through Clarity smart contracts.  
    
**What problems do you aim to solve?**  
While there are 1 billion content creators only 2% of them earn a living on social media platforms such as YouTube and Facebook. The distribution of content is highly controlled by social media platforms and the media industry, giving producers, content creators and creatives very few options to collaborate, create and monetize their digital content. These platforms lack the ability to track and monetize each element of a digital content chain.  

**How does it serve the mission of a user-owned internet?**  
We plan to give creators and their fans the ability to collaborate, track, store, vote, share, and monetize their content as well as own and govern a stake in the decentralized storage and distribution network. This is the initial stage in creating the network effect and requiring members to have a Stacks ID, agree to link storage to Gaia, agree to become Stackers, and agree to sign up for a DiviUp Wallet. Our mission is to accelerate the transition to a user-owned digital ecosystem that creates and distributes value to its members worldwide.   

**Project Overview: What solution are you providing?**  
The initial phase will involve building a DiviUpTV App Channel on Roku which will be the initial minimal viable product used to generate revenue that will create transaction fees for Clarity smart contracts to pay content creators/owner. The DiviUpTV App Channel will also provide an advertising medium that will drive fans and creators to participate in contests that will require them to become a DiviUp member, create a Stacks ID, sign up for a DiviUp Wallet, sign up for the DiviUp Stacker program and agree to link their storage to Gaia. 
 
**Who will it serve?** 
This grant is just the Minimum Viable Product (MVP) that will focus on the Content creators (YouTube (YT) channel owners with 100K to 1M+ Subscribers (Subs) will earn tenfold the CPM rate they receive on paid search by means of an OTT linear television (Roku) advertising model with an inline Ad CPM. We incentivize the Fans (Subs) as the workforce using reward contests and DiviCoins as fuel to deliver 50K content creator VOD channels and 120 million members. We increase the reach and pay rate of the YT channel owners by introducing them to another large video platform. This delivers the network effect and initial revenue stream to create Clarity smart contracts and drive members to create a Stacks ID, sign up for a DiviUp Wallet, sign up for the DiviUp Stacker program and agree to link their storage to Gaia. 

**Budget and Milestones:**  
**What grant amount are you seeking?**   
$18,000
 
**How long will the project take in hours?**  
Code build-out for Roku App - 9 hours $13,000
Code build-out for web DiviUp.TV - 4 hours $2,500
Code build-out for Google Analytics - 5 hours $2,500 

**What relevant experience do you bring to this project?**  
He currently operates multiple app platforms within the TV app/cord cutting community. He possesses an in-depth background in the application of TV broadcast apps and viewership analytics. Based on the description and application of the platforms there is no skill set gaps.

**Scope**
**What are the components of the project?** 
1.	Roku Build
2.	Web Integration
3.	Analytic Module

**What will the final deliverable look like?** 
Video App with a robust revenue stream that will deliver transaction fees to Clarity smart contracts.

**How will you measure success?** 
We will be able to measure our success through analytics based on video and advertising views that will ultimately be measured in transaction fees. We will also amplify our user-owned streaming video ecosystem via Roku ads and measure our success through our social media marketing reward token contests.  

**Are there skills sets you are missing that you are seeking from the community?** 
There are no additional skill sets needed for the DiviUp Roku build. Once the build is completed, we will solicit the Stacks Community on Discord to help test, integrate and validate the build. 

We will need additional grants and Stacks Community assistance to develop the Smart Contracts, Stacks IDs, the DiviUp Wallet and interface with Gaia storage.

**Team:**
**Who is building this?** 
Tony Rossignol
**What relevant experience do you bring to this project?** 
Rossignol has over 15 years of film, edit and production.  Experienced with OTT platform infrastructure and applications.  An expert with Roku TV, Apple TV, Apple iOS and Fire TV Apps and web-based viewing platforms, as well as Roku BrightScript and iOS Swift developer code. Tony has a robust background in optimizing in-app advertising and ad placement.

**Are there skills sets you are missing that you are seeking from the community?** 
Not for this grant build.
Please share links to previous work. https://thsn.app

**Risks:**   
**What dependencies or obstacles do you anticipate?**  
We do not anticipate any issues or obstacles based on our existing relationship with Roku on previous builds. Roku has assigned us the DiviUp channel name.   
 
**What contingency plans do you have in place?**   
Since Roku allows anyone to build Apps on their channel, we do not anticipate any development obstacles. 

**Community and Supporting Materials:**  
**Do you have previous projects, code commits, or experiences that are relevant to  
this application?**  
Yes, we currently maintain TV apps with many different delivery platforms (Roku, Amazon Fire TV, Apple TV, Apple iPhone, Apple IPAD and Web TV). 
 
**What community feedback or input have you received?** 
We have received positive feedback from everyone who has read the DiviUp Whitepaper v1.0.
We look forward to an open dialog with the Stacks community on Discord once we share our grant proposal on GitHub.
 
**How do you plan to share your plan to the community over time and as the final deliverable?** 
Through the Discord Channel for the Stacks community, and Discord is also a great way to reach Content Creators.  We will also market our plan to YouTube channels through YouTube and Facebook ads as well as other relevant social media platforms. Additionally, we will advertise our plan on our DiviUp Roku channel.

![DiviUp Grant Milestone Gantt Chart](https://user-images.githubusercontent.com/40580076/115580401-e6b17a00-a27b-11eb-9e0a-28d42904b28d.png)

**Comment by RaffiSapire** [comment]
Hi @AlfredPizzurro we discussed and unfortunately this is a pass for us. We'd suggest:
- Spend time with the community gleaning demand
- Figure out role of Clarity and token (are they really needed)
- Work on scoping project - better, more digestable milestones
Happy to review another proposal in the future.
